-- 2026-07-16 — Prérequis données de la règle « AGPM conditionnel » (commit a805072).
-- Un PPM comportant >=1 marché en « appel d'offres ouvert » exige la pièce AGPM à la soumission.
-- Les colonnes DECLENCHE_AGPM (tr_mode_passation) et CODE (t_type_piece_jointe) sont créées par
-- Hibernate (ddl-auto) ; ce script ne fait que GARNIR les deux lignes de paramétrage.
--
-- ⚠️ Schéma réel : colonnes en MAJUSCULES quotées ("ID_MODE", "CODE", …) et PK t_type_piece_jointe
-- IDENTITY BY DEFAULT (ID_TYPE_PIECE) — fournie ici en max+1 puis la séquence est resynchronisée.
-- Idempotent : réexécutable sans effet de bord (UPDATE stable ; INSERT gardé par NOT EXISTS).

SET client_encoding TO 'UTF8';
BEGIN;

-- 1) Le mode « Appel d'offres ouvert » (ID_MODE=1) déclenche l'exigence AGPM. Les autres modes
--    restent NULL (= false). Data-driven : ne jamais détecter le mode par mot-clé de libellé.
UPDATE tr_mode_passation SET "DECLENCHE_AGPM" = true WHERE "ID_MODE" = 1;

-- 2) Pièce AGPM au référentiel PPM, repérée par son code stable ; OBLIGATOIRE statique = false
--    (l'obligation est conditionnelle, évaluée à la soumission). Insérée une seule fois.
INSERT INTO t_type_piece_jointe ("ID_TYPE_PIECE", "ID_TYPE_DOSSIER", "LIBELLE_PIECE", "CODE", "OBLIGATOIRE", "ORDRE")
SELECT (SELECT COALESCE(MAX("ID_TYPE_PIECE"), 0) + 1 FROM t_type_piece_jointe),
       'PPM', 'Avis Général de Passation de Marché', 'AGPM', false, 6
WHERE NOT EXISTS (
    SELECT 1 FROM t_type_piece_jointe WHERE "CODE" = 'AGPM' AND "ID_TYPE_DOSSIER" = 'PPM'
);

-- 3) Resynchronise la séquence d'identité (les pièces initiales portent des ID explicites) afin que
--    les futurs ajouts via l'API admin (GENERATED BY DEFAULT) n'entrent pas en collision.
SELECT setval(pg_get_serial_sequence('t_type_piece_jointe', 'ID_TYPE_PIECE'),
              (SELECT MAX("ID_TYPE_PIECE") FROM t_type_piece_jointe));

COMMIT;

-- Vérifications :
--   SELECT "ID_MODE","LIBELLE","DECLENCHE_AGPM" FROM tr_mode_passation WHERE "DECLENCHE_AGPM" = true;  -> mode 1
--   SELECT * FROM t_type_piece_jointe WHERE "CODE" = 'AGPM';                                          -> 1 ligne (PPM, ordre 6)

-- Réversion :
-- UPDATE tr_mode_passation SET "DECLENCHE_AGPM" = NULL WHERE "ID_MODE" = 1;
-- DELETE FROM t_type_piece_jointe WHERE "CODE" = 'AGPM' AND "ID_TYPE_DOSSIER" = 'PPM';
