-- V18 — Versions ARCHIVÉES d'un dossier à la rectification (demande pilote du 2026-09-06, relayée
-- par le front : docs/demande-backend-2026-09-06-versions-rectification.md, commit 49fad99).
--
-- CE QUE LA RÈGLE AJOUTE. La rectification (PUT /api/saisies/ppm/{id} sur un dossier
-- EN_ATTENTE_DECISION_PRMP) corrige le PPM EN PLACE. Jusqu'ici, seul l'instantané pré-correction du
-- DERNIER cycle survivait (t_snapshot_rectif_ligne), et il ne servait que le /diff-rectification :
-- au premier PUT d'un nouveau cycle, la série précédente était effacée. Le pilote veut l'historique
-- complet : chaque version remplacée devient une VERSION ARCHIVÉE, immuable, consultable — numéro
-- d'ordre, date, auteur, itération (cycle) de rectification, et les lignes complètes.
--
-- POURQUOI UNE TABLE D'EN-TÊTE, ET NON LA MÉCANIQUE DES MISES À JOUR. Une mise à jour de PPM crée un
-- NOUVEAU t_dossier (ID_DOSSIER_PARENT) : c'est une nouvelle instruction, avec son propre circuit.
-- Une version archivée de rectification n'est pas un dossier — elle n'a ni statut, ni réception, ni
-- KPI, et ne doit apparaître dans aucune liste de dossiers. La réutiliser aurait semé des dossiers
-- fantômes. On garde donc les lignes déjà figées (t_snapshot_rectif_ligne) et on leur donne un
-- en-tête : t_version_dossier, une ligne par version, rattachée au dossier.
--
-- POURQUOI DES TABLES ENFANTS. L'instantané ne portait que des EMPREINTES normalisées des
-- collections (bénéficiaires, lots, processus) — suffisant pour dire « ça a changé », pas pour
-- RESTITUER une version (montants par bénéficiaire, dates prévisionnelles…). Les empreintes sont
-- conservées (le diff les compare toujours) et trois tables enfants figent le contenu réel.
--
-- REPRISE. La série d'instantanés déjà en base (un seul cycle par dossier, celui du dernier cycle)
-- devient la version archivée n° 1 de son dossier — pas de trou pour 00002. Ses enfants sont
-- inconnus (seules les empreintes existent) : le service les RECONSTITUE à la lecture depuis les
-- empreintes, en mode dégradé (désignations de lots normalisées en minuscules, montant unique par
-- bénéficiaire). L'auteur de la reprise est la PRMP propriétaire du dossier, faute d'historique.
--
-- IMMUABILITÉ. Un trigger BEFORE UPDATE refuse toute modification des cinq tables : une version
-- archivée se lit, ne se corrige pas. Le DELETE reste possible — la purge du circuit (retrait
-- accepté, annulation de dispatch, suppression du dossier) doit pouvoir emporter les versions avec
-- le reste de l'historique, comme elle emportait déjà l'instantané. La mise à jour de reprise
-- ci-dessous s'exécute AVANT la pose du trigger.
--
-- Idempotente : IF NOT EXISTS partout, reprise bornée aux lignes encore sans version, triggers
-- recréés après DROP IF EXISTS.

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 1. En-tête de version
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_version_dossier (
    "ID_VERSION"      integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_DOSSIER"      integer NOT NULL,
    "NUMERO"          integer NOT NULL,
    "ORIGINE"         character varying(20) NOT NULL DEFAULT 'RECTIFICATION',
    "CYCLE"           integer,
    "DATE_VERSION"    timestamp(6) without time zone NOT NULL,
    "ID_PRMP_AUTEUR"  character varying(10),
    "NOM_AUTEUR"      character varying(200),
    "AUTEUR"          character varying(100),
    "EXERCICE"        integer,
    "REFERENCE"       character varying(100),
    "SIGNATAIRE"      character varying(210),
    "DATE_SIGNATURE"  date,
    "NB_LIGNES"       integer NOT NULL DEFAULT 0,
    CONSTRAINT t_version_dossier_pkey PRIMARY KEY ("ID_VERSION"),
    CONSTRAINT uq_version_dossier_numero UNIQUE ("ID_DOSSIER", "NUMERO"),
    CONSTRAINT ck_version_dossier_origine CHECK ("ORIGINE" IN ('RECTIFICATION', 'MISE_A_JOUR')),
    CONSTRAINT fk_version_dossier_dossier FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER")
);

CREATE INDEX IF NOT EXISTS idx_version_dossier_dossier ON public.t_version_dossier USING btree ("ID_DOSSIER");

COMMENT ON TABLE public.t_version_dossier IS
    'Version ARCHIVEE (immuable) du contenu d''un dossier de planification, figee au moment ou une '
    'rectification la remplace. NUMERO = ordre d''archivage par dossier ; CYCLE = iteration de '
    'rectification (resoumissions + 1 au gel). Les lignes sont dans t_snapshot_rectif_ligne.';
COMMENT ON COLUMN public.t_version_dossier."ORIGINE" IS
    'RECTIFICATION (seule origine posee aujourd''hui) ; MISE_A_JOUR reserve a une unification future.';
COMMENT ON COLUMN public.t_version_dossier."ID_PRMP_AUTEUR" IS
    'PRMP operatrice au moment du gel (celle du jeton, ou la PRMP de tutelle d''un agent UGPM).';
COMMENT ON COLUMN public.t_version_dossier."AUTEUR" IS 'Login reel de l''auteur du geste.';

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 2. Lignes : rattachement à la version + champs qui manquaient pour restituer une ligne complète
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_snapshot_rectif_ligne
    ADD COLUMN IF NOT EXISTS "ID_VERSION"              integer,
    ADD COLUMN IF NOT EXISTS "ANCIEN_MONT_ESTIM"       numeric(38,2),
    ADD COLUMN IF NOT EXISTS "JUSTIF_MODE_DEROGATOIRE" character varying(1000),
    ADD COLUMN IF NOT EXISTS "JUSTIF_DELAI_AMENAGE"    character varying(1000);

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 3. Reprise de l'existant : chaque série d'instantanés devient une version archivée
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- Une série = (dossier, cycle). Une seule par dossier en pratique (l'ancien code effaçait la
-- précédente) ; s'il en restait plusieurs, elles sont numérotées dans l'ordre des cycles.
INSERT INTO public.t_version_dossier
    ("ID_DOSSIER", "NUMERO", "ORIGINE", "CYCLE", "DATE_VERSION", "ID_PRMP_AUTEUR", "NOM_AUTEUR", "AUTEUR", "NB_LIGNES")
SELECT serie."ID_DOSSIER",
       row_number() OVER (PARTITION BY serie."ID_DOSSIER" ORDER BY serie."CYCLE"),
       'RECTIFICATION',
       serie."CYCLE",
       serie.date_gel,
       d."ID_PRMP",
       NULLIF(trim(coalesce(p."PRENOMS_PRMP", '') || ' ' || coalesce(p."NOM_PRMP", '')), ''),
       d."ID_PRMP",
       serie.nb
  FROM (SELECT s."ID_DOSSIER", s."CYCLE", min(s."DATE_SNAPSHOT") AS date_gel, count(*) AS nb
          FROM public.t_snapshot_rectif_ligne s
         WHERE s."ID_VERSION" IS NULL
         GROUP BY s."ID_DOSSIER", s."CYCLE") serie
  JOIN public.t_dossier d ON d."ID_DOSSIER" = serie."ID_DOSSIER"
  LEFT JOIN public.t_prmp p ON p."ID_PRMP" = d."ID_PRMP";

UPDATE public.t_snapshot_rectif_ligne s
   SET "ID_VERSION" = v."ID_VERSION"
  FROM public.t_version_dossier v
 WHERE v."ID_DOSSIER" = s."ID_DOSSIER"
   AND v."CYCLE" = s."CYCLE"
   AND s."ID_VERSION" IS NULL;

-- Instantanés orphelins (dossier supprimé avant qu'une FK n'existe) : aucune version possible.
DELETE FROM public.t_snapshot_rectif_ligne WHERE "ID_VERSION" IS NULL;

ALTER TABLE public.t_snapshot_rectif_ligne ALTER COLUMN "ID_VERSION" SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_snapshot_rectif_version') THEN
        ALTER TABLE public.t_snapshot_rectif_ligne
            ADD CONSTRAINT fk_snapshot_rectif_version
            FOREIGN KEY ("ID_VERSION") REFERENCES public.t_version_dossier("ID_VERSION");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_snapshot_rectif_version ON public.t_snapshot_rectif_ligne USING btree ("ID_VERSION");

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 4. Contenu réel des collections d'une ligne figée
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_snapshot_rectif_beneficiaire (
    "ID_SNAPSHOT_BENEF" integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_SNAPSHOT"       integer NOT NULL,
    "SOA_CODE"          character varying(25),
    "NUM_COMPTE"        character varying(20),
    "ANC_MONT_BENEF"    numeric(38,2),
    "NOUV_MONT_BENEF"   numeric(38,2),
    CONSTRAINT t_snapshot_rectif_beneficiaire_pkey PRIMARY KEY ("ID_SNAPSHOT_BENEF"),
    CONSTRAINT fk_snapshot_rectif_benef_ligne FOREIGN KEY ("ID_SNAPSHOT")
        REFERENCES public.t_snapshot_rectif_ligne("ID_SNAPSHOT")
);
CREATE INDEX IF NOT EXISTS idx_snapshot_rectif_benef_ligne
    ON public.t_snapshot_rectif_beneficiaire USING btree ("ID_SNAPSHOT");

CREATE TABLE IF NOT EXISTS public.t_snapshot_rectif_lot (
    "ID_SNAPSHOT_LOT"  integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_SNAPSHOT"      integer NOT NULL,
    "DESIGNATION_LOT"  character varying(200),
    "MONT_LOT"         numeric(38,2),
    "QTE_LOT"          integer,
    "UNITE_LOT"        character varying(10),
    CONSTRAINT t_snapshot_rectif_lot_pkey PRIMARY KEY ("ID_SNAPSHOT_LOT"),
    CONSTRAINT fk_snapshot_rectif_lot_ligne FOREIGN KEY ("ID_SNAPSHOT")
        REFERENCES public.t_snapshot_rectif_ligne("ID_SNAPSHOT")
);
CREATE INDEX IF NOT EXISTS idx_snapshot_rectif_lot_ligne
    ON public.t_snapshot_rectif_lot USING btree ("ID_SNAPSHOT");

CREATE TABLE IF NOT EXISTS public.t_snapshot_rectif_prevision (
    "ID_SNAPSHOT_PREV" integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_SNAPSHOT"      integer NOT NULL,
    "ID_CAPM"          integer NOT NULL,
    "DATE_DEBUT"       date,
    "DATE_FIN"         date,
    CONSTRAINT t_snapshot_rectif_prevision_pkey PRIMARY KEY ("ID_SNAPSHOT_PREV"),
    CONSTRAINT fk_snapshot_rectif_prev_ligne FOREIGN KEY ("ID_SNAPSHOT")
        REFERENCES public.t_snapshot_rectif_ligne("ID_SNAPSHOT")
);
CREATE INDEX IF NOT EXISTS idx_snapshot_rectif_prev_ligne
    ON public.t_snapshot_rectif_prevision USING btree ("ID_SNAPSHOT");

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 5. Immuabilité : aucun UPDATE sur une version archivée ni sur son contenu
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.fn_version_archivee_immuable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Version archivee immuable : aucune modification n''est admise sur %', TG_TABLE_NAME
        USING ERRCODE = 'integrity_constraint_violation';
END;
$$;

DROP TRIGGER IF EXISTS trg_version_dossier_immuable ON public.t_version_dossier;
CREATE TRIGGER trg_version_dossier_immuable
    BEFORE UPDATE ON public.t_version_dossier
    FOR EACH ROW EXECUTE FUNCTION public.fn_version_archivee_immuable();

DROP TRIGGER IF EXISTS trg_snapshot_rectif_ligne_immuable ON public.t_snapshot_rectif_ligne;
CREATE TRIGGER trg_snapshot_rectif_ligne_immuable
    BEFORE UPDATE ON public.t_snapshot_rectif_ligne
    FOR EACH ROW EXECUTE FUNCTION public.fn_version_archivee_immuable();

DROP TRIGGER IF EXISTS trg_snapshot_rectif_benef_immuable ON public.t_snapshot_rectif_beneficiaire;
CREATE TRIGGER trg_snapshot_rectif_benef_immuable
    BEFORE UPDATE ON public.t_snapshot_rectif_beneficiaire
    FOR EACH ROW EXECUTE FUNCTION public.fn_version_archivee_immuable();

DROP TRIGGER IF EXISTS trg_snapshot_rectif_lot_immuable ON public.t_snapshot_rectif_lot;
CREATE TRIGGER trg_snapshot_rectif_lot_immuable
    BEFORE UPDATE ON public.t_snapshot_rectif_lot
    FOR EACH ROW EXECUTE FUNCTION public.fn_version_archivee_immuable();

DROP TRIGGER IF EXISTS trg_snapshot_rectif_prev_immuable ON public.t_snapshot_rectif_prevision;
CREATE TRIGGER trg_snapshot_rectif_prev_immuable
    BEFORE UPDATE ON public.t_snapshot_rectif_prevision
    FOR EACH ROW EXECUTE FUNCTION public.fn_version_archivee_immuable();
