-- V1 — BASELINE du schéma PRS2.0 (Flyway, chantier LOT 2, 2026-08-26).
-- Source : pg_dump --schema-only de DBPRS20 (PostgreSQL 17.11), conteneur prs20-db.
-- Une base DÉJÀ peuplée est baselinée (spring.flyway.baseline-on-migrate=true) : V1 n'y est
-- jamais rejouée. Une base NEUVE (Testcontainers, nouveau poste) est créée par ce script.
-- Historique antérieur : ddl-auto=update + les 32 scripts de docs/migrations/ (gelés).
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: seq_dossier; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_dossier
    START WITH 100001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_marche; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_marche
    START WITH 300001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_ppm; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_ppm
    START WITH 200001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seq_reception; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seq_reception
    START WITH 1100001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: t_action_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_action_dossier (
    "ID_ACTION" bigint NOT NULL,
    "AUTEUR" character varying(100),
    "DATE_ACTION" timestamp(6) without time zone NOT NULL,
    "DETAIL" character varying(500),
    "ID_DOSSIER" integer NOT NULL,
    "ID_MANDAT_OPERATEUR" integer,
    "ID_PRMP_OPERATEUR" character varying(10),
    "NOM_OPERATEUR" character varying(200),
    "TYPE_ACTION" character varying(40) NOT NULL
);


--
-- Name: t_action_dossier_ID_ACTION_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_action_dossier ALTER COLUMN "ID_ACTION" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_action_dossier_ID_ACTION_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_actualite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_actualite (
    "ID_ACTUALITE" integer NOT NULL,
    "CONTENU_MD" text NOT NULL,
    "DATE_ARCHIVAGE" timestamp(6) without time zone,
    "DATE_CREATION" timestamp(6) without time zone NOT NULL,
    "DATE_EXPIRATION" date,
    "DATE_PUBLICATION" date,
    "IM_ARCHIVEUR" character varying(10),
    "IM_AUTEUR" character varying(10),
    "STATUT" character varying(20) NOT NULL,
    "TITRE" character varying(200) NOT NULL
);


--
-- Name: t_actualite_ID_ACTUALITE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_actualite ALTER COLUMN "ID_ACTUALITE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_actualite_ID_ACTUALITE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_actualite_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_actualite_image (
    "ID_IMAGE" integer NOT NULL,
    "CONTENU" bytea,
    "DATE_DEPOT" timestamp(6) without time zone,
    "FORMAT" character varying(100),
    "ID_ACTUALITE" integer NOT NULL,
    "NOM_FICHIER" character varying(255),
    "ORDRE" integer NOT NULL,
    "SHA_256" character varying(64),
    "TAILLE_OCTETS" bigint
);


--
-- Name: t_actualite_image_ID_IMAGE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_actualite_image ALTER COLUMN "ID_IMAGE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_actualite_image_ID_IMAGE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_actualite_profil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_actualite_profil (
    "ID_ACTUALITE_PROFIL" integer NOT NULL,
    "ID_ACTUALITE" integer NOT NULL,
    "PROFIL" character varying(30) NOT NULL
);


--
-- Name: t_actualite_profil_ID_ACTUALITE_PROFIL_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_actualite_profil ALTER COLUMN "ID_ACTUALITE_PROFIL" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_actualite_profil_ID_ACTUALITE_PROFIL_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_anomalie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_anomalie (
    "ID_ANOMALIE" integer NOT NULL,
    "COMMENTAIRE_TRAITEMENT" text,
    "DATE_DETECTION" timestamp(6) without time zone,
    "DATE_TRAITEMENT" timestamp(6) without time zone,
    "DESCRIPTION" text,
    "GRAVITE" character varying(10),
    "ID_DETAIL" integer,
    "ID_PPM" integer,
    "ID_REGLE_ANOMALIE" integer NOT NULL,
    "IM_TRAITEMENT" character varying(7),
    "SOURCE" character varying(20),
    "STATUT" character varying(20),
    "TYPE_ANOMALIE" character varying(50)
);


--
-- Name: t_audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_audit_log (
    "ID_LOG" bigint NOT NULL,
    "ANCIENNE_VALEUR" text,
    "CHAMP_MODIFIE" character varying(50),
    "DATE_ACTION" timestamp(6) without time zone NOT NULL,
    "ID_ENREGISTREMENT" character varying(20),
    "IM_ACTEUR" character varying(10),
    "IP_ADRESSE" character varying(45),
    "NOM_TABLE" character varying(50),
    "NOUVELLE_VALEUR" text,
    "SESSION_ID" character varying(100),
    "TYPE_ACTION" character varying(30)
);


--
-- Name: t_capm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_capm (
    "ID_CAPM" integer NOT NULL,
    "GROUPE" character varying(150),
    "ID_MODE" integer,
    "LIBELLE_PROCESSUS" character varying(300),
    "ORDRE" integer
);


--
-- Name: t_changement_ligne; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_changement_ligne (
    "ID_CHANGEMENT" integer NOT NULL,
    "CHAMP" character varying(50),
    "DESIGNATION" character varying(500),
    "ID_DOSSIER" integer NOT NULL,
    "ID_LIGNE_ORIGINE" integer NOT NULL,
    "TYPE_CHANGEMENT" character varying(20) NOT NULL,
    "VALEUR_APRES" character varying(500),
    "VALEUR_AVANT" character varying(500)
);


--
-- Name: t_compte_auth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_compte_auth (
    "LOGIN" character varying(100) NOT NULL,
    "ACTIF" boolean NOT NULL,
    "DATE_DECISION" timestamp(6) without time zone,
    "IM_VALIDATEUR" character varying(10),
    "MOT_DE_PASSE" character varying(100) NOT NULL,
    "MOTIF_REFUS" character varying(500),
    "REF_ACTEUR" character varying(10) NOT NULL,
    "STATUT" character varying(20),
    "TYPE_ACTEUR" character varying(20) NOT NULL
);


--
-- Name: t_copie_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_copie_dossier (
    "ID_COPIE" integer NOT NULL,
    "ACCUSE_RECEPTION" boolean NOT NULL,
    "DATE_ACCUSE" timestamp(6) without time zone,
    "DATE_TRANSMISSION" timestamp(6) without time zone NOT NULL,
    "ID_DISPATCH" integer NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "IM_DESTINATAIRE" character varying(7) NOT NULL,
    "OBSERVATION" character varying(300),
    "TYPE_COPIE" character varying(30) NOT NULL
);


--
-- Name: t_delegation_profil; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_delegation_profil (
    "ID_DELEGATION" integer NOT NULL,
    "ACTIF" boolean NOT NULL,
    "ID_PROFILE_DELEGANT" integer NOT NULL,
    "ID_PROFILE_DELEGUE" integer NOT NULL
);


--
-- Name: t_demande_retrait; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_demande_retrait (
    "ID_DEMANDE_RETRAIT" integer NOT NULL,
    "DATE_DECISION" timestamp(6) without time zone,
    "DATE_DEMANDE" timestamp(6) without time zone NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL,
    "IM_CTRL_CC" character varying(7),
    "MOTIF_RETRAIT" text NOT NULL,
    "OBS_DECISION" character varying(500),
    "STATUT" character varying(20) NOT NULL
);


--
-- Name: t_demande_retrait_ID_DEMANDE_RETRAIT_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_demande_retrait ALTER COLUMN "ID_DEMANDE_RETRAIT" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_demande_retrait_ID_DEMANDE_RETRAIT_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_demande_retrait_vue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_demande_retrait_vue (
    "ID_VUE" integer NOT NULL,
    "DATE_DERNIERE_VUE" timestamp(6) without time zone NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL
);


--
-- Name: t_demande_retrait_vue_ID_VUE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_demande_retrait_vue ALTER COLUMN "ID_VUE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_demande_retrait_vue_ID_VUE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_dispatch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_dispatch (
    "ID_DISPATCH" integer NOT NULL,
    "DATE_CTRL_ASSIGNE" date,
    "DATE_DISPATCH" timestamp without time zone,
    "ID_RECEPTION" integer NOT NULL,
    "IM_CTRL_CC" character varying(7),
    "IM_CTRL_DISPATCH" character varying(7),
    "IM_CTRL_MEMBRE" character varying(7),
    "INSTRUCTIONS" character varying(500),
    "INTERIM_DISPATCH" boolean NOT NULL
);


--
-- Name: t_document_public; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_document_public (
    "ID_DOC_PUBLIC" integer NOT NULL,
    "CHEMIN_FICHIER" character varying(500),
    "DATE_DEPOT" timestamp(6) without time zone,
    "FORMAT" character varying(10),
    "HASH_SHA256" character varying(64),
    "ID_PUBLICATION" integer NOT NULL,
    "LIBELLE_DOC" character varying(200),
    "TAILLE_OCTETS" bigint,
    "TYPE_DOC" character varying(30)
);


--
-- Name: t_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_dossier (
    "ID_DOSSIER" integer NOT NULL,
    "CREE_PAR" character varying(100),
    "DATE_REF" date,
    "DATE_SOUMISSION" timestamp(6) without time zone,
    "ID_DOSSIER_PARENT" integer,
    "ID_ENTITE_CONTRACT" integer,
    "ID_LOCALITE" character varying(5),
    "ID_MANDAT_ATTRIB" integer,
    "ID_PRMP" character varying(10),
    "ID_SOUS_TYPE" character varying(20),
    "ID_TYPE_DOSSIER" character varying(10),
    "REFE_DOSSIER" character varying(100),
    "SOUMIS_PAR" character varying(100),
    "STATUT" character varying(30)
);


--
-- Name: t_dossier_mec; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_dossier_mec (
    "ID_DMC" bigint NOT NULL,
    "DATE_CREATION" timestamp(6) without time zone NOT NULL,
    "ID_DETAIL" integer NOT NULL,
    "ID_TYPE_DMC" bigint NOT NULL,
    "REFERENCE" character varying(60),
    "STATUT" character varying(30) NOT NULL,
    CONSTRAINT "t_dossier_mec_STATUT_check" CHECK ((("STATUT")::text = ANY ((ARRAY['A_PREPARER'::character varying, 'ENGAGE'::character varying])::text[])))
);


--
-- Name: t_dossier_mec_ID_DMC_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_dossier_mec ALTER COLUMN "ID_DMC" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_dossier_mec_ID_DMC_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_echeance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_echeance (
    "ID_ECHEANCE" integer NOT NULL,
    "ALERTE_ENVOYEE" boolean,
    "DATE_PREVUE" date NOT NULL,
    "DATE_REELLE" date,
    "ECART_JOURS" integer,
    "ID_DETAIL" integer NOT NULL,
    "STATUT_JALON" character varying(20),
    "TYPE_JALON" character varying(30) NOT NULL
);


--
-- Name: t_examen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_examen (
    "ID_EXAMEN" integer NOT NULL,
    "DATE_EXAMEN" date,
    "ID_DISPATCH" integer NOT NULL,
    "IM_CTRL_MEMBRE" character varying(7)
);


--
-- Name: t_examen_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_examen_detail (
    "ID_DETAIL_EXAMEN" integer NOT NULL,
    "CONFORME" boolean NOT NULL,
    "ID_DETAIL" integer,
    "ID_EXAMEN" integer NOT NULL,
    "ID_PT_CONTROLE" integer NOT NULL,
    "OBS_SI_NON_CONFORME" character varying(500)
);


--
-- Name: t_examen_piece; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_examen_piece (
    "ID_EXAMEN_PIECE" integer NOT NULL,
    "CONFORME" boolean NOT NULL,
    "ID_EXAMEN" integer NOT NULL,
    "ID_PIECE" integer NOT NULL,
    "OBSERVATION" character varying(500)
);


--
-- Name: t_indicateur_ctrl; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_indicateur_ctrl (
    "ID_INDICATEUR" integer NOT NULL,
    "DELAI_MOYEN_EXAMEN" numeric(38,2),
    "IM_CONTROLEUR" character varying(7) NOT NULL,
    "NB_CONFORMES" integer,
    "NB_EXAMENS" integer,
    "NB_OBS_EMISES" integer,
    "PERIODE" character varying(7) NOT NULL
);


--
-- Name: t_indicateur_prmp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_indicateur_prmp (
    "ID_INDICATEUR_PRMP" integer NOT NULL,
    "DATE_MAJ" timestamp(6) without time zone,
    "DELAI_MOY_CORRECTION_JOURS" numeric(38,2),
    "EXERCICE" integer NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL,
    "MONT_TOTAL_SOUMIS" numeric(38,2),
    "NB_DOSSIERS_CONFORMES" integer NOT NULL,
    "NB_DOSSIERS_NON_CONFORMES" integer NOT NULL,
    "NB_DOSSIERS_SOUMIS" integer NOT NULL,
    "NB_PPM_SOUMIS" integer NOT NULL,
    "NB_RETOURS" integer NOT NULL,
    "NB_RETRAITS" integer NOT NULL,
    "TAUX_CONFORMITE" numeric(38,2)
);


--
-- Name: t_lettre_renvoi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_lettre_renvoi (
    "ID_LETTRE" integer NOT NULL,
    "CHEMIN_DOCUMENT" character varying(500),
    "CORPS_LETTRE" text,
    "DATE_ARCHIVAGE" date,
    "DATE_EXAMEN" date,
    "DATE_LETTRE" date,
    "DOCUMENT_PDF" bytea,
    "ID_DOSSIER" integer NOT NULL,
    "ID_EXAMEN" integer NOT NULL,
    "IM_ARCHIVEUR" character varying(7),
    "IM_SIGNATAIRE" character varying(7),
    "OBJET_LETTRE" character varying(500),
    "REF_LETTRE" character varying(50),
    "STATUT" character varying(20)
);


--
-- Name: t_lettre_renvoi_ID_LETTRE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_lettre_renvoi ALTER COLUMN "ID_LETTRE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_lettre_renvoi_ID_LETTRE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_lettre_renvoi_lue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_lettre_renvoi_lue (
    "ID_LECTURE" integer NOT NULL,
    "DATE_LECTURE" timestamp(6) without time zone NOT NULL,
    "ID_LETTRE" integer NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL
);


--
-- Name: t_lettre_renvoi_lue_ID_LECTURE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_lettre_renvoi_lue ALTER COLUMN "ID_LECTURE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_lettre_renvoi_lue_ID_LECTURE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_lot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_lot (
    "ID_LOT" integer NOT NULL,
    "DESIGNATION_LOT" character varying(200) NOT NULL,
    "ID_DETAIL" integer NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "MONT_LOT" numeric(38,2),
    "QTE_LOT" integer,
    "UNITE_LOT" character varying(10)
);


--
-- Name: t_mandat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_mandat (
    "ID_MANDAT" integer NOT NULL,
    "DATE_ABROGATION" date,
    "DATE_DEBUT" date NOT NULL,
    "DATE_FIN" date NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL,
    "MOTIF_ABROGATION" character varying(255),
    "NUMERO_MANDAT" integer NOT NULL,
    "REF_ARRETE" character varying(100) NOT NULL,
    "STATUT" character varying(20) NOT NULL,
    "TITULAIRE" character varying(200) NOT NULL
);


--
-- Name: t_mandat_ID_MANDAT_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_mandat ALTER COLUMN "ID_MANDAT" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_mandat_ID_MANDAT_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_marche; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_marche (
    "ID_DETAIL" integer NOT NULL,
    "ANCIEN_MONT_ESTIM" numeric(38,2),
    "DESIGNATION_MARCHE" character varying(500),
    "FINANCEMENT" character varying(20),
    "FORME_MARCHE" character varying(20),
    "ID_DOSSIER" integer NOT NULL,
    "ID_LIGNE_ORIGINE" integer,
    "ID_MODE" integer,
    "ID_NATURE" integer,
    "ID_PPM" integer NOT NULL,
    "MONT_ESTIM" numeric(38,2),
    "NOUV_MONT_ESTIM" numeric(38,2),
    "NUM_COMPTE" character varying(20),
    "STATUT" character varying(20),
    "SUPPRIMEE" boolean,
    CONSTRAINT "t_marche_FORME_MARCHE_check" CHECK ((("FORME_MARCHE")::text = ANY ((ARRAY['A_COMMANDE'::character varying, 'CONTRAT_CADRE'::character varying, 'QUANTITE_FIXE'::character varying])::text[])))
);


--
-- Name: t_marche_prevision; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_marche_prevision (
    "ID_PREVISION" integer NOT NULL,
    "DATE_DEBUT" date,
    "DATE_FIN" date,
    "ID_CAPM" integer NOT NULL,
    "ID_DETAIL" integer NOT NULL
);


--
-- Name: t_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_message (
    "ID_MESSAGE" integer NOT NULL,
    "CORPS" text,
    "DATE_ENVOI" timestamp(6) without time zone,
    "DESTINATAIRE_IM" character varying(7) NOT NULL,
    "EXPEDITEUR_IM" character varying(7) NOT NULL,
    "ID_DOSSIER" integer,
    "ID_MESSAGE_PARENT" integer,
    "LU" boolean,
    "SUJET" character varying(200)
);


--
-- Name: t_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_notification (
    "ID_NOTIFICATION" integer NOT NULL,
    "CANAL" character varying(20),
    "CORPS" text,
    "DATE_ENVOI" timestamp(6) without time zone,
    "DATE_LECTURE" timestamp(6) without time zone,
    "DESTINATAIRE_EMAIL" character varying(100),
    "DESTINATAIRE_IM" character varying(7),
    "DESTINATAIRE_REF" character varying(10),
    "DESTINATAIRE_TYPE" character varying(20),
    "ID_DOSSIER" integer,
    "ID_OBJET" integer,
    "LU" boolean,
    "TITRE" character varying(200),
    "TYPE_NOTIF" character varying(30) NOT NULL,
    "TYPE_OBJET" character varying(20)
);


--
-- Name: t_observation_controle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_observation_controle (
    "ID_OBSERVATION" integer NOT NULL,
    "AU_LIEU_DE" character varying(500),
    "ID_DETAIL" integer NOT NULL,
    "LIRE" character varying(500),
    "ORDRE" integer
);


--
-- Name: t_observation_controle_ID_OBSERVATION_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_observation_controle ALTER COLUMN "ID_OBSERVATION" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_observation_controle_ID_OBSERVATION_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_observation_pv; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_observation_pv (
    "ID_OBSERVATION_PV" integer NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_EXAMEN_PIECE" integer,
    "ID_OBSERVATION_CTRL" integer,
    "ID_PV" integer NOT NULL,
    "LIBELLE" character varying(1000) NOT NULL,
    "ORDRE" integer,
    "SOURCE" character varying(10) NOT NULL
);


--
-- Name: t_observation_pv_ID_OBSERVATION_PV_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_observation_pv ALTER COLUMN "ID_OBSERVATION_PV" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_observation_pv_ID_OBSERVATION_PV_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_organigramme; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_organigramme (
    "ID_ORGANIGRAMME" integer NOT NULL,
    "ACTIF" boolean NOT NULL,
    "DATE_VALIDATION" date,
    "ID_MINISTERE" integer NOT NULL,
    "LIBELLE" character varying(200),
    "VERSION" character varying(20)
);


--
-- Name: t_parametre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_parametre (
    "CLE" character varying(50) NOT NULL,
    "DATE_MAJ" timestamp(6) without time zone,
    "IM_ACTEUR" character varying(10),
    "VALEUR" character varying(200)
);


--
-- Name: t_piece_demande_retrait; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_piece_demande_retrait (
    "ID_PIECE" integer NOT NULL,
    "CONTENU" bytea,
    "DATE_DEPOT" timestamp(6) without time zone,
    "FORMAT" character varying(100),
    "HASH_SHA256" character varying(64),
    "ID_DEMANDE_RETRAIT" integer NOT NULL,
    "NOM_FICHIER" character varying(255),
    "TAILLE_OCTETS" bigint
);


--
-- Name: t_piece_demande_retrait_ID_PIECE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_piece_demande_retrait ALTER COLUMN "ID_PIECE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_piece_demande_retrait_ID_PIECE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_piece_jointe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_piece_jointe (
    "ID_PIECE" integer NOT NULL,
    "CONTENU" bytea,
    "DATE_DEPOT" timestamp(6) without time zone,
    "FORMAT" character varying(100),
    "HASH_SHA256" character varying(64),
    "LIBELLE" character varying(200),
    "LOGIN" character varying(100) NOT NULL,
    "TAILLE_OCTETS" bigint,
    "TYPE_PIECE" character varying(20) NOT NULL
);


--
-- Name: t_piece_jointe_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_piece_jointe_dossier (
    "ID_PIECE" integer NOT NULL,
    "APRES_LETTRE_RENVOI" boolean NOT NULL,
    "CONTENU" bytea,
    "DATE_UPLOAD" timestamp(6) without time zone,
    "FORMAT" character varying(10),
    "ID_DOSSIER" integer NOT NULL,
    "ID_LETTRE" integer,
    "ID_TYPE_PIECE" integer NOT NULL,
    "NOM_FICHIER" character varying(255),
    "TAILLE" bigint,
    "VERSION_CORRIGEE" boolean
);


--
-- Name: t_piece_jointe_dossier_ID_PIECE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_piece_jointe_dossier ALTER COLUMN "ID_PIECE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_piece_jointe_dossier_ID_PIECE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_ppm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_ppm (
    "ID_PPM" integer NOT NULL,
    "DATE_MAJ" date,
    "DATE_MAJ_PREC" date,
    "DATE_PPM_INIT" date,
    "DATE_RECEPTION_CNM" date,
    "DATE_SIGNATURE" date NOT NULL,
    "EXERCICE" integer NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_LOCALITE" character varying(5),
    "ID_PRMP" character varying(10),
    "LIBELLE" character varying(200),
    "MOTIF_MAJ" character varying(500),
    "NUM_MAJ" integer,
    "NUM_MAJ_PREC" integer,
    "REFERENCE" character varying(100) NOT NULL,
    "SIGNATAIRE" character varying(210) NOT NULL,
    "VU" character varying(100)
);


--
-- Name: t_prmp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_prmp (
    "ID_PRMP" character varying(10) NOT NULL,
    "ARRETE_NOMIN" character varying(100) NOT NULL,
    "CIN" character varying(12) NOT NULL,
    "DATE_CIN" date NOT NULL,
    "DATE_NOMIN" date NOT NULL,
    "EMAIL_PRMP" character varying(100) NOT NULL,
    "LIEU_CIN" character varying(50) NOT NULL,
    "NOM_PRMP" character varying(100) NOT NULL,
    "PRENOMS_PRMP" character varying(100) NOT NULL,
    "TEL_PRMP" character varying(20) NOT NULL
);


--
-- Name: t_prmp_entite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_prmp_entite (
    "ID_PRMP_ENTITE" integer NOT NULL,
    "ACTIF" boolean NOT NULL,
    "DATE_AFFECTATION" date,
    "ID_ENTITE_CONTRACT" integer NOT NULL,
    "ID_PRMP" character varying(10) NOT NULL
);


--
-- Name: t_prmp_entite_demande; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_prmp_entite_demande (
    "ID_DEMANDE" integer NOT NULL,
    "ADRESSE_PROPOSE" character varying(200),
    "CATEGORIE_PROPOSE" character varying(20),
    "DATE_DECLARATION" date,
    "ID_ENTITE_CONTRACT" integer,
    "ID_LOCALITE_PROPOSE" character varying(5),
    "LIBELLE_PROPOSE" character varying(50),
    "LOGIN" character varying(100) NOT NULL,
    "MOTIF" character varying(500),
    "STATUT_DEMANDE" character varying(20) NOT NULL
);


--
-- Name: t_publication; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_publication (
    "ID_PUBLICATION" integer NOT NULL,
    "DATE_PUBLICATION" timestamp(6) without time zone,
    "DATE_RETRAIT" date,
    "ID_OBJET" integer NOT NULL,
    "IM_PUBLIE_PAR" character varying(7),
    "MOTIF_RETRAIT" character varying(300),
    "NB_CONSULTATIONS" integer,
    "STATUT_PUBLI" character varying(20),
    "TYPE_OBJET" character varying(20) NOT NULL
);


--
-- Name: t_pv_examen; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pv_examen (
    "ID_PV" integer NOT NULL,
    "CHEMIN_DOCUMENT" character varying(500),
    "DATE_ACCEPTATION" date,
    "DATE_ARCHIVAGE" date,
    "DATE_PV" date,
    "DATE_SIGNATURE_CC" date,
    "DATE_SIGNATURE_MEMBRE" date,
    "DATE_SIGNATURE_PRESIDENT" date,
    "DATE_SOUMISSION_INITIALE" date,
    "ID_AVIS" character varying(10),
    "ID_EXAMEN" integer NOT NULL,
    "ID_SECRETAIRE_SEANCE" character varying(7),
    "IM_ARCHIVEUR" character varying(7),
    "IM_CTRL_CC" character varying(7),
    "IM_CTRL_MEMBRE" character varying(7) NOT NULL,
    "IM_CTRL_PRESIDENT" character varying(7),
    "NB_NAVETTES" integer NOT NULL,
    "REFE_PV" character varying(120),
    "REFERENCE_PV" character varying(100),
    "STATUT_PV" character varying(20) NOT NULL,
    "SYNTHESE_OBSERVATIONS" text,
    CONSTRAINT t_pv_examen_cosignataire_check CHECK (((("STATUT_PV")::text <> 'SIGNE'::text) OR (("DATE_SIGNATURE_MEMBRE" IS NOT NULL) AND (("DATE_SIGNATURE_PRESIDENT" IS NOT NULL) OR ("DATE_SIGNATURE_CC" IS NOT NULL)))))
);


--
-- Name: t_pv_navette; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_pv_navette (
    "ID_NAVETTE" integer NOT NULL,
    "COMMENTAIRE" text,
    "DATE_ACTION" timestamp(6) without time zone NOT NULL,
    "ID_PV" integer NOT NULL,
    "IM_ACTEUR" character varying(7) NOT NULL,
    "NUM_NAVETTE" integer NOT NULL,
    "SENS" character varying(20) NOT NULL
);


--
-- Name: t_reception; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_reception (
    "ID_RECEPTION" integer NOT NULL,
    "COMPLET" boolean,
    "DATE_RECEPTION" timestamp without time zone,
    "ID_DOSSIER" integer NOT NULL,
    "ID_RECEPTION_PREC" integer,
    "IM_CTRL_RECEPT" character varying(7),
    "NUM_PASSAGE" integer NOT NULL,
    "OBSERVATION" character varying(500),
    "REFERENCE" character varying(100),
    "TYPE_PASSAGE" character varying(10) NOT NULL
);


--
-- Name: t_regle_alerte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_regle_alerte (
    "ID_REGLE_ALERTE" integer NOT NULL,
    "ACTIF" boolean,
    "DESTINATAIRE_PROFIL" integer,
    "JOURS_AVANT" integer NOT NULL,
    "TYPE_JALON" character varying(30) NOT NULL
);


--
-- Name: t_regle_anomalie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_regle_anomalie (
    "ID_REGLE_ANOMALIE" integer NOT NULL,
    "ACTIF" boolean,
    "CODE_REGLE" character varying(30) NOT NULL,
    "GRAVITE_DEFAUT" character varying(10),
    "LIBELLE" character varying(200),
    "PARAMETRE_NUM" numeric(38,2),
    "PARAMETRE_TXT" character varying(200)
);


--
-- Name: t_sequence_reference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_sequence_reference (
    "ANNEE_EXERCICE" integer NOT NULL,
    "CODE_LOCALITE" character varying(20) NOT NULL,
    "TYPE_DOSSIER" character varying(10) NOT NULL,
    "DERNIERE_VALEUR" bigint NOT NULL
);


--
-- Name: t_service_beneficiaire; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_service_beneficiaire (
    "ID_BENEF" integer NOT NULL,
    "ANC_MONT_BENEF" numeric(38,2),
    "ID_DETAIL" integer NOT NULL,
    "NOUV_MONT_BENEF" numeric(38,2),
    "NUM_COMPTE" character varying(20),
    "SOA_CODE" character varying(25)
);


--
-- Name: t_session_utilisateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_session_utilisateur (
    "ID_SESSION" character varying(100) NOT NULL,
    "DATE_CONNEXION" timestamp(6) without time zone,
    "DATE_DECONNEXION" timestamp(6) without time zone,
    "IM_CONTROLEUR" character varying(7),
    "IP_ADRESSE" character varying(45),
    "SUCCES" boolean,
    "USER_AGENT" character varying(300)
);


--
-- Name: t_snapshot_rectif_ligne; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_snapshot_rectif_ligne (
    "ID_SNAPSHOT" integer NOT NULL,
    "CYCLE" integer NOT NULL,
    "DATE_SNAPSHOT" timestamp(6) without time zone NOT NULL,
    "DESIGNATION_MARCHE" character varying(500),
    "EMP_BENEFICIAIRES" character varying(2000),
    "EMP_LOTS" character varying(2000),
    "EMP_PROCESSUS" character varying(2000),
    "FINANCEMENT" character varying(100),
    "FORME_MARCHE" character varying(20),
    "ID_DETAIL" integer NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_LIGNE_ORIGINE" integer,
    "ID_MODE" integer,
    "ID_NATURE" integer,
    "MONT_ESTIM" numeric(38,2),
    "NOUV_MONT_ESTIM" numeric(38,2),
    "NUM_COMPTE" character varying(20),
    "STATUT" character varying(20),
    "SUPPRIMEE" boolean
);


--
-- Name: t_snapshot_rectif_ligne_ID_SNAPSHOT_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_snapshot_rectif_ligne ALTER COLUMN "ID_SNAPSHOT" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_snapshot_rectif_ligne_ID_SNAPSHOT_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_snapshot_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_snapshot_stats (
    "ID_SNAPSHOT" integer NOT NULL,
    "DATE_SNAPSHOT" date NOT NULL,
    "DELAI_MOYEN_JOURS" numeric(38,2),
    "EXERCICE" integer NOT NULL,
    "ID_LOCALITE" character varying(5),
    "MONT_TOTAL_CONTROLE" numeric(38,2),
    "NB_DOSSIERS_CLOTURES" integer,
    "NB_DOSSIERS_EN_COURS" integer,
    "NB_DOSSIERS_RECUS" integer,
    "NB_RETOURS_MOYEN" numeric(38,2),
    "TAUX_CONFORMITE" numeric(38,2)
);


--
-- Name: t_suivi_observation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_suivi_observation (
    "ID_SUIVI" integer NOT NULL,
    "DATE_DECISION" timestamp(6) without time zone NOT NULL,
    "DECISION" character varying(10) NOT NULL,
    "ID_OBSERVATION_PV" integer NOT NULL,
    "IM_VERIFICATEUR" character varying(7) NOT NULL,
    "ITERATION" integer NOT NULL,
    "PRECISION_VERIF" character varying(500)
);


--
-- Name: t_suivi_observation_ID_SUIVI_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_suivi_observation ALTER COLUMN "ID_SUIVI" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_suivi_observation_ID_SUIVI_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_tranche; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_tranche (
    "ID_TRANCHE" integer NOT NULL,
    "ID_LOT" integer NOT NULL,
    "LIEU_TRC" character varying(100),
    "MONT_TRC" numeric(38,2)
);


--
-- Name: t_transmission_sigmp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_transmission_sigmp (
    "ID_TRANSMISSION" integer NOT NULL,
    "DATE_TRANSMISSION" timestamp(6) without time zone NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_PV" integer NOT NULL,
    "IM_VERIFICATEUR" character varying(7),
    "LEVEE_OBSERVATIONS" boolean NOT NULL,
    "SENS" character varying(20) NOT NULL,
    "STATUT_ENVOI" character varying(20) NOT NULL
);


--
-- Name: t_transmission_sigmp_ID_TRANSMISSION_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_transmission_sigmp ALTER COLUMN "ID_TRANSMISSION" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_transmission_sigmp_ID_TRANSMISSION_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_type_dmc; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_type_dmc (
    "ID_TYPE_DMC" bigint NOT NULL,
    "ACTIF" boolean NOT NULL,
    "CODE" character varying(10) NOT NULL,
    "LIBELLE" character varying(120) NOT NULL
);


--
-- Name: t_type_dmc_ID_TYPE_DMC_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_type_dmc ALTER COLUMN "ID_TYPE_DMC" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_type_dmc_ID_TYPE_DMC_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_type_piece_jointe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_type_piece_jointe (
    "ID_TYPE_PIECE" integer NOT NULL,
    "CODE" character varying(20),
    "ID_TYPE_DOSSIER" character varying(10),
    "LIBELLE_PIECE" character varying(200) NOT NULL,
    "OBLIGATOIRE" boolean NOT NULL,
    "ORDRE" integer
);


--
-- Name: t_type_piece_jointe_ID_TYPE_PIECE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_type_piece_jointe ALTER COLUMN "ID_TYPE_PIECE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_type_piece_jointe_ID_TYPE_PIECE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_ugpm; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_ugpm (
    "ID_UGPM" character varying(10) NOT NULL,
    "CIN" character varying(12) NOT NULL,
    "DATE_CIN" date NOT NULL,
    "EMAIL_UGPM" character varying(100) NOT NULL,
    "ID_PRMP_TUTELLE" character varying(10) NOT NULL,
    "LIBELLE" character varying(100),
    "LIEU_CIN" character varying(50) NOT NULL,
    "NOM_UGPM" character varying(50) NOT NULL,
    "PRENOMS_UGPM" character varying(100) NOT NULL,
    "TEL_UGPM" character varying(20) NOT NULL
);


--
-- Name: t_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_verification (
    "ID_VERIFICATION" integer NOT NULL,
    "DATE_VERIF" date,
    "ID_PV" integer NOT NULL,
    "ID_RECEPTION" integer NOT NULL,
    "IM_CTRL_VERIF" character varying(7),
    "MOTIF_RECTIF" character varying(255),
    "OBS_LEVEES" boolean,
    "OBSERVATION" character varying(500)
);


--
-- Name: t_verification_ID_VERIFICATION_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_verification ALTER COLUMN "ID_VERIFICATION" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_verification_ID_VERIFICATION_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_verification_piece_depot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_verification_piece_depot (
    "ID_VERIF_PIECE" integer NOT NULL,
    "DATE_VERIF" timestamp(6) without time zone NOT NULL,
    "DECISION" character varying(20) NOT NULL,
    "ID_DOSSIER" integer NOT NULL,
    "ID_PIECE" integer,
    "ID_TYPE_PIECE" integer NOT NULL,
    "IM_SECRETAIRE" character varying(7),
    "OBSERVATION" character varying(500)
);


--
-- Name: t_verification_piece_depot_ID_VERIF_PIECE_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_verification_piece_depot ALTER COLUMN "ID_VERIF_PIECE" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."t_verification_piece_depot_ID_VERIF_PIECE_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tr_avis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_avis (
    "ID_AVIS" character varying(10) NOT NULL,
    "LIBELLE_AVIS" character varying(100)
);


--
-- Name: tr_cat_compte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_cat_compte (
    "ID_CAT_COMPTE" character varying(10) NOT NULL,
    "CAT_COMPTE" character varying(50)
);


--
-- Name: tr_categorie_entite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_categorie_entite (
    "LIBELLE" character varying(20) NOT NULL,
    "NIVEAU_HIERARCHIQUE" integer NOT NULL
);


--
-- Name: tr_compte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_compte (
    "NUM_COMPTE" character varying(20) NOT NULL,
    "ID_CAT_COMPTE" character varying(10),
    "LIBELLE" character varying(100)
);


--
-- Name: tr_controleur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_controleur (
    "IM_CONTROLEUR" character varying(7) NOT NULL,
    "EMAIL_CONT" character varying(100),
    "ID_LOCALITE" character varying(5),
    "ID_PROFILE" integer,
    "ID_SUPERIEUR" character varying(7),
    "NOM_CONT" character varying(100),
    "PRENOMS_CONT" character varying(100),
    "TEL_CONT" character varying(20),
    "TRANSVERSAL" boolean NOT NULL
);


--
-- Name: tr_entite_contract; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_entite_contract (
    "ID_ENTITE_CONTRACT" integer NOT NULL,
    "ADRESSE" character varying(200) NOT NULL,
    "CATEGORIE_ENTITE" character varying(20),
    "ID_ENTITE_PARENT" integer,
    "ID_LOCALITE" character varying(5),
    "ID_ORGANIGRAMME" integer NOT NULL,
    "LIBELLE_ENTITE" character varying(150) NOT NULL,
    "NIVEAU_HIERARCHIQUE" integer
);


--
-- Name: tr_localite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_localite (
    "ID_LOCALITE" character varying(5) NOT NULL,
    "CHEF_LIEU" character varying(50),
    "LIBELLE_LOCALITE" character varying(50) NOT NULL
);


--
-- Name: tr_ministere; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_ministere (
    "ID_MINISTERE" integer NOT NULL,
    "LIBELLE_MINISTERE" character varying(150) NOT NULL,
    "SIGLE" character varying(20)
);


--
-- Name: tr_mode_passation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_mode_passation (
    "ID_MODE" integer NOT NULL,
    "BASE_LEGALE" character varying(200),
    "CATEGORIE" character varying(20),
    "DECLENCHE_AGPM" boolean,
    "DELAI_MIN_JOURS" integer,
    "DESCRIPTION" character varying(500),
    "ID_MODE_MODELE_CAPM" integer,
    "ID_TYPE_DMC" bigint,
    "LIBELLE" character varying(100),
    "PUBLICITE_REQUISE" boolean,
    CONSTRAINT "tr_mode_passation_CATEGORIE_check" CHECK ((("CATEGORIE")::text = ANY ((ARRAY['NORMAL'::character varying, 'DEROGATOIRE'::character varying])::text[])))
);


--
-- Name: tr_nature; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_nature (
    "ID_NATURE" integer NOT NULL,
    "DESCRIPTION" character varying(500),
    "LIBELLE" character varying(100)
);


--
-- Name: tr_points_ctrl; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_points_ctrl (
    "ID_POINT_CTRL" integer NOT NULL,
    "DECRIPT_POINT_CTRL" character varying(255),
    "ID_SOUS_TYPE" character varying(20),
    "ID_TYPE_DOSSIER" character varying(255) NOT NULL,
    "LIBEL_POINT_CTRL" character varying(255),
    "OBLIGATOIRE" boolean NOT NULL,
    "ORDRE_POINT_CTRL" integer,
    "PORTEE" character varying(10),
    CONSTRAINT "tr_points_ctrl_PORTEE_check" CHECK ((("PORTEE")::text = ANY ((ARRAY['LIGNE'::character varying, 'DOSSIER'::character varying])::text[])))
);


--
-- Name: tr_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_profile (
    "ID_PROFILE" integer NOT NULL,
    "PROFILE" character varying(50)
);


--
-- Name: tr_soa_beneficiaire; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_soa_beneficiaire (
    "SOA_CODE" character varying(25) NOT NULL,
    "LIBELLE" character varying(100)
);


--
-- Name: tr_sous_type_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_sous_type_dossier (
    "ID_SOUS_TYPE" character varying(20) NOT NULL,
    "ID_TYPE_DOSSIER" character varying(10) NOT NULL,
    "LIBELLE_SOUS_TYPE" character varying(150)
);


--
-- Name: tr_type_dossier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tr_type_dossier (
    "ID_TYPE_DOSSIER" character varying(10) NOT NULL,
    "LIBELLE_TYPE" character varying(100)
);


--
-- Name: t_dossier_mec UK55qp3ub79u667o66ax9rgwcd6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier_mec
    ADD CONSTRAINT "UK55qp3ub79u667o66ax9rgwcd6" UNIQUE ("ID_DETAIL");


--
-- Name: t_type_dmc UKig22r26pbbrqw1pakrdm2gwqk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_type_dmc
    ADD CONSTRAINT "UKig22r26pbbrqw1pakrdm2gwqk" UNIQUE ("CODE");


--
-- Name: t_piece_demande_retrait UKiwnwjwm1yq4kc18a7hmwbks7s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_piece_demande_retrait
    ADD CONSTRAINT "UKiwnwjwm1yq4kc18a7hmwbks7s" UNIQUE ("ID_DEMANDE_RETRAIT");


--
-- Name: t_actualite_profil UKp1po9011h13xjoydwpd083pne; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_actualite_profil
    ADD CONSTRAINT "UKp1po9011h13xjoydwpd083pne" UNIQUE ("ID_ACTUALITE", "PROFIL");


--
-- Name: t_delegation_profil UQ_DELEGATION_PAIRE; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delegation_profil
    ADD CONSTRAINT "UQ_DELEGATION_PAIRE" UNIQUE ("ID_PROFILE_DELEGANT", "ID_PROFILE_DELEGUE");


--
-- Name: t_action_dossier t_action_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_action_dossier
    ADD CONSTRAINT t_action_dossier_pkey PRIMARY KEY ("ID_ACTION");


--
-- Name: t_actualite_image t_actualite_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_actualite_image
    ADD CONSTRAINT t_actualite_image_pkey PRIMARY KEY ("ID_IMAGE");


--
-- Name: t_actualite t_actualite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_actualite
    ADD CONSTRAINT t_actualite_pkey PRIMARY KEY ("ID_ACTUALITE");


--
-- Name: t_actualite_profil t_actualite_profil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_actualite_profil
    ADD CONSTRAINT t_actualite_profil_pkey PRIMARY KEY ("ID_ACTUALITE_PROFIL");


--
-- Name: t_anomalie t_anomalie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_anomalie
    ADD CONSTRAINT t_anomalie_pkey PRIMARY KEY ("ID_ANOMALIE");


--
-- Name: t_audit_log t_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_audit_log
    ADD CONSTRAINT t_audit_log_pkey PRIMARY KEY ("ID_LOG");


--
-- Name: t_capm t_capm_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_capm
    ADD CONSTRAINT t_capm_pkey PRIMARY KEY ("ID_CAPM");


--
-- Name: t_changement_ligne t_changement_ligne_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_changement_ligne
    ADD CONSTRAINT t_changement_ligne_pkey PRIMARY KEY ("ID_CHANGEMENT");


--
-- Name: t_compte_auth t_compte_auth_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_compte_auth
    ADD CONSTRAINT t_compte_auth_pkey PRIMARY KEY ("LOGIN");


--
-- Name: t_copie_dossier t_copie_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_copie_dossier
    ADD CONSTRAINT t_copie_dossier_pkey PRIMARY KEY ("ID_COPIE");


--
-- Name: t_delegation_profil t_delegation_profil_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delegation_profil
    ADD CONSTRAINT t_delegation_profil_pkey PRIMARY KEY ("ID_DELEGATION");


--
-- Name: t_demande_retrait t_demande_retrait_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait
    ADD CONSTRAINT t_demande_retrait_pkey PRIMARY KEY ("ID_DEMANDE_RETRAIT");


--
-- Name: t_demande_retrait_vue t_demande_retrait_vue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait_vue
    ADD CONSTRAINT t_demande_retrait_vue_pkey PRIMARY KEY ("ID_VUE");


--
-- Name: t_dispatch t_dispatch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dispatch
    ADD CONSTRAINT t_dispatch_pkey PRIMARY KEY ("ID_DISPATCH");


--
-- Name: t_document_public t_document_public_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_document_public
    ADD CONSTRAINT t_document_public_pkey PRIMARY KEY ("ID_DOC_PUBLIC");


--
-- Name: t_dossier_mec t_dossier_mec_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier_mec
    ADD CONSTRAINT t_dossier_mec_pkey PRIMARY KEY ("ID_DMC");


--
-- Name: t_dossier t_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT t_dossier_pkey PRIMARY KEY ("ID_DOSSIER");


--
-- Name: t_echeance t_echeance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_echeance
    ADD CONSTRAINT t_echeance_pkey PRIMARY KEY ("ID_ECHEANCE");


--
-- Name: t_examen_detail t_examen_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen_detail
    ADD CONSTRAINT t_examen_detail_pkey PRIMARY KEY ("ID_DETAIL_EXAMEN");


--
-- Name: t_examen_piece t_examen_piece_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen_piece
    ADD CONSTRAINT t_examen_piece_pkey PRIMARY KEY ("ID_EXAMEN_PIECE");


--
-- Name: t_examen t_examen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen
    ADD CONSTRAINT t_examen_pkey PRIMARY KEY ("ID_EXAMEN");


--
-- Name: t_indicateur_ctrl t_indicateur_ctrl_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_indicateur_ctrl
    ADD CONSTRAINT t_indicateur_ctrl_pkey PRIMARY KEY ("ID_INDICATEUR");


--
-- Name: t_indicateur_prmp t_indicateur_prmp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_indicateur_prmp
    ADD CONSTRAINT t_indicateur_prmp_pkey PRIMARY KEY ("ID_INDICATEUR_PRMP");


--
-- Name: t_lettre_renvoi_lue t_lettre_renvoi_lue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi_lue
    ADD CONSTRAINT t_lettre_renvoi_lue_pkey PRIMARY KEY ("ID_LECTURE");


--
-- Name: t_lettre_renvoi t_lettre_renvoi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi
    ADD CONSTRAINT t_lettre_renvoi_pkey PRIMARY KEY ("ID_LETTRE");


--
-- Name: t_lot t_lot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lot
    ADD CONSTRAINT t_lot_pkey PRIMARY KEY ("ID_LOT");


--
-- Name: t_mandat t_mandat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_mandat
    ADD CONSTRAINT t_mandat_pkey PRIMARY KEY ("ID_MANDAT");


--
-- Name: t_marche t_marche_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT t_marche_pkey PRIMARY KEY ("ID_DETAIL");


--
-- Name: t_marche_prevision t_marche_prevision_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche_prevision
    ADD CONSTRAINT t_marche_prevision_pkey PRIMARY KEY ("ID_PREVISION");


--
-- Name: t_message t_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_message
    ADD CONSTRAINT t_message_pkey PRIMARY KEY ("ID_MESSAGE");


--
-- Name: t_notification t_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_notification
    ADD CONSTRAINT t_notification_pkey PRIMARY KEY ("ID_NOTIFICATION");


--
-- Name: t_observation_controle t_observation_controle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_observation_controle
    ADD CONSTRAINT t_observation_controle_pkey PRIMARY KEY ("ID_OBSERVATION");


--
-- Name: t_observation_pv t_observation_pv_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_observation_pv
    ADD CONSTRAINT t_observation_pv_pkey PRIMARY KEY ("ID_OBSERVATION_PV");


--
-- Name: t_organigramme t_organigramme_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_organigramme
    ADD CONSTRAINT t_organigramme_pkey PRIMARY KEY ("ID_ORGANIGRAMME");


--
-- Name: t_parametre t_parametre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_parametre
    ADD CONSTRAINT t_parametre_pkey PRIMARY KEY ("CLE");


--
-- Name: t_piece_demande_retrait t_piece_demande_retrait_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_piece_demande_retrait
    ADD CONSTRAINT t_piece_demande_retrait_pkey PRIMARY KEY ("ID_PIECE");


--
-- Name: t_piece_jointe_dossier t_piece_jointe_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_piece_jointe_dossier
    ADD CONSTRAINT t_piece_jointe_dossier_pkey PRIMARY KEY ("ID_PIECE");


--
-- Name: t_piece_jointe t_piece_jointe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_piece_jointe
    ADD CONSTRAINT t_piece_jointe_pkey PRIMARY KEY ("ID_PIECE");


--
-- Name: t_ppm t_ppm_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ppm
    ADD CONSTRAINT t_ppm_pkey PRIMARY KEY ("ID_PPM");


--
-- Name: t_prmp_entite_demande t_prmp_entite_demande_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_prmp_entite_demande
    ADD CONSTRAINT t_prmp_entite_demande_pkey PRIMARY KEY ("ID_DEMANDE");


--
-- Name: t_prmp_entite t_prmp_entite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_prmp_entite
    ADD CONSTRAINT t_prmp_entite_pkey PRIMARY KEY ("ID_PRMP_ENTITE");


--
-- Name: t_prmp t_prmp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_prmp
    ADD CONSTRAINT t_prmp_pkey PRIMARY KEY ("ID_PRMP");


--
-- Name: t_publication t_publication_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_publication
    ADD CONSTRAINT t_publication_pkey PRIMARY KEY ("ID_PUBLICATION");


--
-- Name: t_pv_examen t_pv_examen_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT t_pv_examen_pkey PRIMARY KEY ("ID_PV");


--
-- Name: t_pv_navette t_pv_navette_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_navette
    ADD CONSTRAINT t_pv_navette_pkey PRIMARY KEY ("ID_NAVETTE");


--
-- Name: t_reception t_reception_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reception
    ADD CONSTRAINT t_reception_pkey PRIMARY KEY ("ID_RECEPTION");


--
-- Name: t_regle_alerte t_regle_alerte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_regle_alerte
    ADD CONSTRAINT t_regle_alerte_pkey PRIMARY KEY ("ID_REGLE_ALERTE");


--
-- Name: t_regle_anomalie t_regle_anomalie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_regle_anomalie
    ADD CONSTRAINT t_regle_anomalie_pkey PRIMARY KEY ("ID_REGLE_ANOMALIE");


--
-- Name: t_sequence_reference t_sequence_reference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_sequence_reference
    ADD CONSTRAINT t_sequence_reference_pkey PRIMARY KEY ("ANNEE_EXERCICE", "CODE_LOCALITE", "TYPE_DOSSIER");


--
-- Name: t_service_beneficiaire t_service_beneficiaire_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_service_beneficiaire
    ADD CONSTRAINT t_service_beneficiaire_pkey PRIMARY KEY ("ID_BENEF");


--
-- Name: t_session_utilisateur t_session_utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_session_utilisateur
    ADD CONSTRAINT t_session_utilisateur_pkey PRIMARY KEY ("ID_SESSION");


--
-- Name: t_snapshot_rectif_ligne t_snapshot_rectif_ligne_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_snapshot_rectif_ligne
    ADD CONSTRAINT t_snapshot_rectif_ligne_pkey PRIMARY KEY ("ID_SNAPSHOT");


--
-- Name: t_snapshot_stats t_snapshot_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_snapshot_stats
    ADD CONSTRAINT t_snapshot_stats_pkey PRIMARY KEY ("ID_SNAPSHOT");


--
-- Name: t_suivi_observation t_suivi_observation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_suivi_observation
    ADD CONSTRAINT t_suivi_observation_pkey PRIMARY KEY ("ID_SUIVI");


--
-- Name: t_tranche t_tranche_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_tranche
    ADD CONSTRAINT t_tranche_pkey PRIMARY KEY ("ID_TRANCHE");


--
-- Name: t_transmission_sigmp t_transmission_sigmp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_transmission_sigmp
    ADD CONSTRAINT t_transmission_sigmp_pkey PRIMARY KEY ("ID_TRANSMISSION");


--
-- Name: t_type_dmc t_type_dmc_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_type_dmc
    ADD CONSTRAINT t_type_dmc_pkey PRIMARY KEY ("ID_TYPE_DMC");


--
-- Name: t_type_piece_jointe t_type_piece_jointe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_type_piece_jointe
    ADD CONSTRAINT t_type_piece_jointe_pkey PRIMARY KEY ("ID_TYPE_PIECE");


--
-- Name: t_ugpm t_ugpm_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ugpm
    ADD CONSTRAINT t_ugpm_pkey PRIMARY KEY ("ID_UGPM");


--
-- Name: t_verification_piece_depot t_verification_piece_depot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_verification_piece_depot
    ADD CONSTRAINT t_verification_piece_depot_pkey PRIMARY KEY ("ID_VERIF_PIECE");


--
-- Name: t_verification t_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_verification
    ADD CONSTRAINT t_verification_pkey PRIMARY KEY ("ID_VERIFICATION");


--
-- Name: tr_avis tr_avis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_avis
    ADD CONSTRAINT tr_avis_pkey PRIMARY KEY ("ID_AVIS");


--
-- Name: tr_cat_compte tr_cat_compte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_cat_compte
    ADD CONSTRAINT tr_cat_compte_pkey PRIMARY KEY ("ID_CAT_COMPTE");


--
-- Name: tr_categorie_entite tr_categorie_entite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_categorie_entite
    ADD CONSTRAINT tr_categorie_entite_pkey PRIMARY KEY ("LIBELLE");


--
-- Name: tr_compte tr_compte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_compte
    ADD CONSTRAINT tr_compte_pkey PRIMARY KEY ("NUM_COMPTE");


--
-- Name: tr_controleur tr_controleur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_controleur
    ADD CONSTRAINT tr_controleur_pkey PRIMARY KEY ("IM_CONTROLEUR");


--
-- Name: tr_entite_contract tr_entite_contract_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_entite_contract
    ADD CONSTRAINT tr_entite_contract_pkey PRIMARY KEY ("ID_ENTITE_CONTRACT");


--
-- Name: tr_localite tr_localite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_localite
    ADD CONSTRAINT tr_localite_pkey PRIMARY KEY ("ID_LOCALITE");


--
-- Name: tr_ministere tr_ministere_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_ministere
    ADD CONSTRAINT tr_ministere_pkey PRIMARY KEY ("ID_MINISTERE");


--
-- Name: tr_mode_passation tr_mode_passation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_mode_passation
    ADD CONSTRAINT tr_mode_passation_pkey PRIMARY KEY ("ID_MODE");


--
-- Name: tr_nature tr_nature_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_nature
    ADD CONSTRAINT tr_nature_pkey PRIMARY KEY ("ID_NATURE");


--
-- Name: tr_points_ctrl tr_points_ctrl_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_points_ctrl
    ADD CONSTRAINT tr_points_ctrl_pkey PRIMARY KEY ("ID_POINT_CTRL");


--
-- Name: tr_profile tr_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_profile
    ADD CONSTRAINT tr_profile_pkey PRIMARY KEY ("ID_PROFILE");


--
-- Name: tr_soa_beneficiaire tr_soa_beneficiaire_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_soa_beneficiaire
    ADD CONSTRAINT tr_soa_beneficiaire_pkey PRIMARY KEY ("SOA_CODE");


--
-- Name: tr_sous_type_dossier tr_sous_type_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_sous_type_dossier
    ADD CONSTRAINT tr_sous_type_dossier_pkey PRIMARY KEY ("ID_SOUS_TYPE");


--
-- Name: tr_type_dossier tr_type_dossier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_type_dossier
    ADD CONSTRAINT tr_type_dossier_pkey PRIMARY KEY ("ID_TYPE_DOSSIER");


--
-- Name: t_demande_retrait_vue uk_demande_retrait_vue_prmp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait_vue
    ADD CONSTRAINT uk_demande_retrait_vue_prmp UNIQUE ("ID_PRMP");


--
-- Name: t_lettre_renvoi_lue uk_lettre_lue; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi_lue
    ADD CONSTRAINT uk_lettre_lue UNIQUE ("ID_LETTRE", "ID_PRMP");


--
-- Name: t_delegation_profil uq_delegation_paire; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delegation_profil
    ADD CONSTRAINT uq_delegation_paire UNIQUE ("ID_PROFILE_DELEGANT", "ID_PROFILE_DELEGUE");


--
-- Name: t_pv_examen uq_pv_examen_refe_pv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT uq_pv_examen_refe_pv UNIQUE ("REFE_PV");


--
-- Name: idx_action_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_dossier ON public.t_action_dossier USING btree ("ID_DOSSIER");


--
-- Name: idx_action_dossier_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_action_dossier_date ON public.t_action_dossier USING btree ("DATE_ACTION");


--
-- Name: idx_changement_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_changement_dossier ON public.t_changement_ligne USING btree ("ID_DOSSIER");


--
-- Name: idx_changement_ligne_origine; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_changement_ligne_origine ON public.t_changement_ligne USING btree ("ID_LIGNE_ORIGINE");


--
-- Name: idx_dossier_localite; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dossier_localite ON public.t_dossier USING btree ("ID_LOCALITE");


--
-- Name: idx_dossier_prmp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dossier_prmp ON public.t_dossier USING btree ("ID_PRMP");


--
-- Name: idx_dossier_statut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dossier_statut ON public.t_dossier USING btree ("STATUT");


--
-- Name: idx_mandat_prmp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mandat_prmp ON public.t_mandat USING btree ("ID_PRMP");


--
-- Name: idx_mandat_statut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mandat_statut ON public.t_mandat USING btree ("STATUT");


--
-- Name: idx_marche_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_marche_dossier ON public.t_marche USING btree ("ID_DOSSIER");


--
-- Name: idx_marche_ppm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_marche_ppm ON public.t_marche USING btree ("ID_PPM");


--
-- Name: idx_ppm_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ppm_dossier ON public.t_ppm USING btree ("ID_DOSSIER");


--
-- Name: idx_ppm_localite; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ppm_localite ON public.t_ppm USING btree ("ID_LOCALITE");


--
-- Name: idx_ppm_prmp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ppm_prmp ON public.t_ppm USING btree ("ID_PRMP");


--
-- Name: idx_reception_dossier; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reception_dossier ON public.t_reception USING btree ("ID_DOSSIER");


--
-- Name: t_notification FK11jcl4ja61nh7k3ldb09g5s1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_notification
    ADD CONSTRAINT "FK11jcl4ja61nh7k3ldb09g5s1" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_lettre_renvoi FK1b4533k0ohutc4eg0e5ecr36p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi
    ADD CONSTRAINT "FK1b4533k0ohutc4eg0e5ecr36p" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_delegation_profil FK1cy0abihvvklluwnx8vjosgyt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delegation_profil
    ADD CONSTRAINT "FK1cy0abihvvklluwnx8vjosgyt" FOREIGN KEY ("ID_PROFILE_DELEGUE") REFERENCES public.tr_profile("ID_PROFILE");


--
-- Name: t_dossier FK1jrrab8kaqqxg8c9xog45w5jj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FK1jrrab8kaqqxg8c9xog45w5jj" FOREIGN KEY ("ID_TYPE_DOSSIER") REFERENCES public.tr_type_dossier("ID_TYPE_DOSSIER");


--
-- Name: t_service_beneficiaire FK209f9t974xj6n1p5m9dfts49s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_service_beneficiaire
    ADD CONSTRAINT "FK209f9t974xj6n1p5m9dfts49s" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_marche("ID_DETAIL");


--
-- Name: t_marche_prevision FK20a2nx3h983as38g72pmny1up; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche_prevision
    ADD CONSTRAINT "FK20a2nx3h983as38g72pmny1up" FOREIGN KEY ("ID_CAPM") REFERENCES public.t_capm("ID_CAPM");


--
-- Name: t_examen FK20vhg3nvowmawly082m404vsn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen
    ADD CONSTRAINT "FK20vhg3nvowmawly082m404vsn" FOREIGN KEY ("IM_CTRL_MEMBRE") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_anomalie FK2elv3u8m5r9howswkedus50be; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_anomalie
    ADD CONSTRAINT "FK2elv3u8m5r9howswkedus50be" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_marche("ID_DETAIL");


--
-- Name: t_marche FK2utvghs2o5nb6g8gfhwa39txu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT "FK2utvghs2o5nb6g8gfhwa39txu" FOREIGN KEY ("ID_NATURE") REFERENCES public.tr_nature("ID_NATURE");


--
-- Name: t_pv_examen FK3b98sk8nbumju6iyh9raxy9m6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT "FK3b98sk8nbumju6iyh9raxy9m6" FOREIGN KEY ("ID_AVIS") REFERENCES public.tr_avis("ID_AVIS");


--
-- Name: t_examen FK3iiu9nnsqqq1ptcwmwehxrsv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen
    ADD CONSTRAINT "FK3iiu9nnsqqq1ptcwmwehxrsv" FOREIGN KEY ("ID_DISPATCH") REFERENCES public.t_dispatch("ID_DISPATCH");


--
-- Name: t_indicateur_prmp FK3lpo03uyhtqebmj9o1i7cywnu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_indicateur_prmp
    ADD CONSTRAINT "FK3lpo03uyhtqebmj9o1i7cywnu" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_anomalie FK46sxegbovs81uk7h7bx7634hx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_anomalie
    ADD CONSTRAINT "FK46sxegbovs81uk7h7bx7634hx" FOREIGN KEY ("IM_TRAITEMENT") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_regle_alerte FK4mqw0t5s6aqo0vhjf0vxmdvvw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_regle_alerte
    ADD CONSTRAINT "FK4mqw0t5s6aqo0vhjf0vxmdvvw" FOREIGN KEY ("DESTINATAIRE_PROFIL") REFERENCES public.tr_profile("ID_PROFILE");


--
-- Name: t_copie_dossier FK4wykn9u1lg0d5vg09t4qb9pew; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_copie_dossier
    ADD CONSTRAINT "FK4wykn9u1lg0d5vg09t4qb9pew" FOREIGN KEY ("IM_DESTINATAIRE") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_observation_controle FK56m8qjsc4xog5q9v5qgc1p1aw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_observation_controle
    ADD CONSTRAINT "FK56m8qjsc4xog5q9v5qgc1p1aw" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_examen_detail("ID_DETAIL_EXAMEN");


--
-- Name: t_ppm FK5s0f3rkd6ai8dr08otndqck6o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ppm
    ADD CONSTRAINT "FK5s0f3rkd6ai8dr08otndqck6o" FOREIGN KEY ("ID_LOCALITE") REFERENCES public.tr_localite("ID_LOCALITE");


--
-- Name: t_dossier FK64lnv2ix3g86rfkmjnsepwl0s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FK64lnv2ix3g86rfkmjnsepwl0s" FOREIGN KEY ("ID_DOSSIER_PARENT") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_pv_examen FK67fm2pk9lapysmrgo3uu0dh1u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT "FK67fm2pk9lapysmrgo3uu0dh1u" FOREIGN KEY ("IM_CTRL_CC") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: tr_points_ctrl FK6aafbj7t8gvgtd4wyk696hka8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_points_ctrl
    ADD CONSTRAINT "FK6aafbj7t8gvgtd4wyk696hka8" FOREIGN KEY ("ID_SOUS_TYPE") REFERENCES public.tr_sous_type_dossier("ID_SOUS_TYPE");


--
-- Name: t_ugpm FK6kwr374rv7amfatn17c9hlpf2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ugpm
    ADD CONSTRAINT "FK6kwr374rv7amfatn17c9hlpf2" FOREIGN KEY ("ID_PRMP_TUTELLE") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_publication FK6wywithpygbrt0klhwobmkikx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_publication
    ADD CONSTRAINT "FK6wywithpygbrt0klhwobmkikx" FOREIGN KEY ("IM_PUBLIE_PAR") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_document_public FK742g91kcwycxttolx2ndtni0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_document_public
    ADD CONSTRAINT "FK742g91kcwycxttolx2ndtni0y" FOREIGN KEY ("ID_PUBLICATION") REFERENCES public.t_publication("ID_PUBLICATION");


--
-- Name: t_dispatch FK746urs32wf25m2b3nw6f1y89j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dispatch
    ADD CONSTRAINT "FK746urs32wf25m2b3nw6f1y89j" FOREIGN KEY ("IM_CTRL_CC") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_pv_examen FK7m6g8g58vmtnryro6t2j78ugm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT "FK7m6g8g58vmtnryro6t2j78ugm" FOREIGN KEY ("IM_CTRL_PRESIDENT") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_notification FK8clns0dq2qffo8fj1giivks3r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_notification
    ADD CONSTRAINT "FK8clns0dq2qffo8fj1giivks3r" FOREIGN KEY ("DESTINATAIRE_IM") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_service_beneficiaire FK8d0jrw0se02dp5gjlc89p5o0n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_service_beneficiaire
    ADD CONSTRAINT "FK8d0jrw0se02dp5gjlc89p5o0n" FOREIGN KEY ("SOA_CODE") REFERENCES public.tr_soa_beneficiaire("SOA_CODE");


--
-- Name: tr_sous_type_dossier FK8gu2vf1gbf7c5u6f28pk6wvyv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_sous_type_dossier
    ADD CONSTRAINT "FK8gu2vf1gbf7c5u6f28pk6wvyv" FOREIGN KEY ("ID_TYPE_DOSSIER") REFERENCES public.tr_type_dossier("ID_TYPE_DOSSIER");


--
-- Name: t_copie_dossier FK8mbkd4ojbw80p2mj0ptaexpeu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_copie_dossier
    ADD CONSTRAINT "FK8mbkd4ojbw80p2mj0ptaexpeu" FOREIGN KEY ("ID_DISPATCH") REFERENCES public.t_dispatch("ID_DISPATCH");


--
-- Name: t_mandat FK8ux055qi9knfv1f6j8nmnhgsd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_mandat
    ADD CONSTRAINT "FK8ux055qi9knfv1f6j8nmnhgsd" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_dossier_mec FK933k18nkoa6puaqxg79w85kd6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier_mec
    ADD CONSTRAINT "FK933k18nkoa6puaqxg79w85kd6" FOREIGN KEY ("ID_TYPE_DMC") REFERENCES public.t_type_dmc("ID_TYPE_DMC");


--
-- Name: t_indicateur_ctrl FK963ihop9mjhhhrw51rtow2iel; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_indicateur_ctrl
    ADD CONSTRAINT "FK963ihop9mjhhhrw51rtow2iel" FOREIGN KEY ("IM_CONTROLEUR") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_demande_retrait FK9cchds4pn3epb13999tjv6dy4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait
    ADD CONSTRAINT "FK9cchds4pn3epb13999tjv6dy4" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_examen_detail FK9txjccg87cvtrel380e225luw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen_detail
    ADD CONSTRAINT "FK9txjccg87cvtrel380e225luw" FOREIGN KEY ("ID_PT_CONTROLE") REFERENCES public.tr_points_ctrl("ID_POINT_CTRL");


--
-- Name: t_prmp_entite FK9uvq1eb6c70xwnm56p8x8830d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_prmp_entite
    ADD CONSTRAINT "FK9uvq1eb6c70xwnm56p8x8830d" FOREIGN KEY ("ID_ENTITE_CONTRACT") REFERENCES public.tr_entite_contract("ID_ENTITE_CONTRACT");


--
-- Name: t_session_utilisateur FKamgm0ujyucg4w96x1dgfuqpi4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_session_utilisateur
    ADD CONSTRAINT "FKamgm0ujyucg4w96x1dgfuqpi4" FOREIGN KEY ("IM_CONTROLEUR") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_dossier FKb3bwd88khmi5yrib3ujotupye; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FKb3bwd88khmi5yrib3ujotupye" FOREIGN KEY ("ID_ENTITE_CONTRACT") REFERENCES public.tr_entite_contract("ID_ENTITE_CONTRACT");


--
-- Name: t_lot FKbe24kyxuiuxfg2xv3glt66uu4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lot
    ADD CONSTRAINT "FKbe24kyxuiuxfg2xv3glt66uu4" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_examen_detail FKbqedcfw0e6fvqnqb32d53um37; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen_detail
    ADD CONSTRAINT "FKbqedcfw0e6fvqnqb32d53um37" FOREIGN KEY ("ID_EXAMEN") REFERENCES public.t_examen("ID_EXAMEN");


--
-- Name: t_dispatch FKcncvk9d22e3glwvhstrh2yym4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dispatch
    ADD CONSTRAINT "FKcncvk9d22e3glwvhstrh2yym4" FOREIGN KEY ("ID_RECEPTION") REFERENCES public.t_reception("ID_RECEPTION");


--
-- Name: t_verification FKcnu17nvmv41virkwmry6rk60f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_verification
    ADD CONSTRAINT "FKcnu17nvmv41virkwmry6rk60f" FOREIGN KEY ("ID_RECEPTION") REFERENCES public.t_reception("ID_RECEPTION");


--
-- Name: t_marche FKcoba8mi37ciu82mr6y3vc8j0c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT "FKcoba8mi37ciu82mr6y3vc8j0c" FOREIGN KEY ("ID_PPM") REFERENCES public.t_ppm("ID_PPM");


--
-- Name: tr_compte FKd1hlv69ywnb0676jbg4bj4adk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_compte
    ADD CONSTRAINT "FKd1hlv69ywnb0676jbg4bj4adk" FOREIGN KEY ("ID_CAT_COMPTE") REFERENCES public.tr_cat_compte("ID_CAT_COMPTE");


--
-- Name: t_dispatch FKehla67x46fbxqykalrk0qjx71; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dispatch
    ADD CONSTRAINT "FKehla67x46fbxqykalrk0qjx71" FOREIGN KEY ("IM_CTRL_DISPATCH") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: tr_points_ctrl FKehybxxjofkxrr97okrsb5plm0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_points_ctrl
    ADD CONSTRAINT "FKehybxxjofkxrr97okrsb5plm0" FOREIGN KEY ("ID_TYPE_DOSSIER") REFERENCES public.tr_type_dossier("ID_TYPE_DOSSIER");


--
-- Name: t_dossier FKf7h7pb9sey90ie3rkc6xek009; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FKf7h7pb9sey90ie3rkc6xek009" FOREIGN KEY ("ID_SOUS_TYPE") REFERENCES public.tr_sous_type_dossier("ID_SOUS_TYPE");


--
-- Name: t_service_beneficiaire FKfqurxtohtw0ykuj31vtg8pmsk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_service_beneficiaire
    ADD CONSTRAINT "FKfqurxtohtw0ykuj31vtg8pmsk" FOREIGN KEY ("NUM_COMPTE") REFERENCES public.tr_compte("NUM_COMPTE");


--
-- Name: t_ppm FKfvbm25q7mx2vy7shryk9xqlwj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ppm
    ADD CONSTRAINT "FKfvbm25q7mx2vy7shryk9xqlwj" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: tr_entite_contract FKg5itnnh5s1t1dxcwe1kr4hqj5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_entite_contract
    ADD CONSTRAINT "FKg5itnnh5s1t1dxcwe1kr4hqj5" FOREIGN KEY ("ID_ORGANIGRAMME") REFERENCES public.t_organigramme("ID_ORGANIGRAMME");


--
-- Name: tr_controleur FKg7m514x391urqrhwbesopw66c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_controleur
    ADD CONSTRAINT "FKg7m514x391urqrhwbesopw66c" FOREIGN KEY ("ID_SUPERIEUR") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: tr_entite_contract FKgdmpyerpruav96old7la9yxea; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_entite_contract
    ADD CONSTRAINT "FKgdmpyerpruav96old7la9yxea" FOREIGN KEY ("ID_LOCALITE") REFERENCES public.tr_localite("ID_LOCALITE");


--
-- Name: t_copie_dossier FKgee3q2ks2y0yo6ey8jsxw2pa3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_copie_dossier
    ADD CONSTRAINT "FKgee3q2ks2y0yo6ey8jsxw2pa3" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_pv_navette FKgqgmkxfj9f1fh3gd75e1ht9dl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_navette
    ADD CONSTRAINT "FKgqgmkxfj9f1fh3gd75e1ht9dl" FOREIGN KEY ("IM_ACTEUR") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: tr_mode_passation FKh32ghl6wl5kvqqofdvs58u6y7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_mode_passation
    ADD CONSTRAINT "FKh32ghl6wl5kvqqofdvs58u6y7" FOREIGN KEY ("ID_TYPE_DMC") REFERENCES public.t_type_dmc("ID_TYPE_DMC");


--
-- Name: t_marche FKhv3wd6p6rd75uvk5hj56va3cp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT "FKhv3wd6p6rd75uvk5hj56va3cp" FOREIGN KEY ("NUM_COMPTE") REFERENCES public.tr_compte("NUM_COMPTE");


--
-- Name: t_marche FKii39o3gxpa4jy75j3ofj6yp99; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT "FKii39o3gxpa4jy75j3ofj6yp99" FOREIGN KEY ("ID_MODE") REFERENCES public.tr_mode_passation("ID_MODE");


--
-- Name: t_marche_prevision FKjctbv1qq7dclb34kmp02ie1yd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche_prevision
    ADD CONSTRAINT "FKjctbv1qq7dclb34kmp02ie1yd" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_marche("ID_DETAIL");


--
-- Name: t_type_piece_jointe FKjmt3yshx5072mf7wgalkxkgqh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_type_piece_jointe
    ADD CONSTRAINT "FKjmt3yshx5072mf7wgalkxkgqh" FOREIGN KEY ("ID_TYPE_DOSSIER") REFERENCES public.tr_type_dossier("ID_TYPE_DOSSIER");


--
-- Name: t_lot FKjrmp0un3xxn5oxp260pntqrpw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lot
    ADD CONSTRAINT "FKjrmp0un3xxn5oxp260pntqrpw" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_marche("ID_DETAIL");


--
-- Name: t_verification FKjsog0c0pqlgukgum37jeyn3e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_verification
    ADD CONSTRAINT "FKjsog0c0pqlgukgum37jeyn3e" FOREIGN KEY ("IM_CTRL_VERIF") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_dossier FKjtnadmkxbt5iu2cefbpka1e86; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FKjtnadmkxbt5iu2cefbpka1e86" FOREIGN KEY ("ID_LOCALITE") REFERENCES public.tr_localite("ID_LOCALITE");


--
-- Name: t_pv_navette FKjuxhd8xpb46g3tqleoxjano9c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_navette
    ADD CONSTRAINT "FKjuxhd8xpb46g3tqleoxjano9c" FOREIGN KEY ("ID_PV") REFERENCES public.t_pv_examen("ID_PV");


--
-- Name: t_examen_piece FKkbf53w54ntcl1cfq172kxp3gl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_examen_piece
    ADD CONSTRAINT "FKkbf53w54ntcl1cfq172kxp3gl" FOREIGN KEY ("ID_EXAMEN") REFERENCES public.t_examen("ID_EXAMEN");


--
-- Name: t_organigramme FKkewp6700wm0e4yfy5hbis6b3x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_organigramme
    ADD CONSTRAINT "FKkewp6700wm0e4yfy5hbis6b3x" FOREIGN KEY ("ID_MINISTERE") REFERENCES public.tr_ministere("ID_MINISTERE");


--
-- Name: tr_controleur FKl18feassqpjopfiocchpuov0o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_controleur
    ADD CONSTRAINT "FKl18feassqpjopfiocchpuov0o" FOREIGN KEY ("ID_LOCALITE") REFERENCES public.tr_localite("ID_LOCALITE");


--
-- Name: t_message FKl5wpr40svnd7auhn79pmt2i2w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_message
    ADD CONSTRAINT "FKl5wpr40svnd7auhn79pmt2i2w" FOREIGN KEY ("ID_MESSAGE_PARENT") REFERENCES public.t_message("ID_MESSAGE");


--
-- Name: t_ppm FKli5kwu9dlgayyh2qsmfeoa6eu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_ppm
    ADD CONSTRAINT "FKli5kwu9dlgayyh2qsmfeoa6eu" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_dossier FKmdq8lus5sgggt43ympy3e5a5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dossier
    ADD CONSTRAINT "FKmdq8lus5sgggt43ympy3e5a5" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_anomalie FKmngvb93nv8birafjvqr1isoy8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_anomalie
    ADD CONSTRAINT "FKmngvb93nv8birafjvqr1isoy8" FOREIGN KEY ("ID_REGLE_ANOMALIE") REFERENCES public.t_regle_anomalie("ID_REGLE_ANOMALIE");


--
-- Name: t_marche FKmo9ev0yew8770i3p4xduiu405; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_marche
    ADD CONSTRAINT "FKmo9ev0yew8770i3p4xduiu405" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_message FKn8dbj6yxthx4186ym5yb4li9x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_message
    ADD CONSTRAINT "FKn8dbj6yxthx4186ym5yb4li9x" FOREIGN KEY ("EXPEDITEUR_IM") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_snapshot_stats FKncqllijfmpfjxrpu3a7hpj4d7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_snapshot_stats
    ADD CONSTRAINT "FKncqllijfmpfjxrpu3a7hpj4d7" FOREIGN KEY ("ID_LOCALITE") REFERENCES public.tr_localite("ID_LOCALITE");


--
-- Name: t_verification FKnscde3bownxythnod7mwo0v4b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_verification
    ADD CONSTRAINT "FKnscde3bownxythnod7mwo0v4b" FOREIGN KEY ("ID_PV") REFERENCES public.t_pv_examen("ID_PV");


--
-- Name: tr_entite_contract FKo91xnx84767b6vyfhxudb2iuh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_entite_contract
    ADD CONSTRAINT "FKo91xnx84767b6vyfhxudb2iuh" FOREIGN KEY ("ID_ENTITE_PARENT") REFERENCES public.tr_entite_contract("ID_ENTITE_CONTRACT");


--
-- Name: t_message FKopp7cusoed2pd4vp7tie50t7h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_message
    ADD CONSTRAINT "FKopp7cusoed2pd4vp7tie50t7h" FOREIGN KEY ("DESTINATAIRE_IM") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_reception FKoti6fusft2c0l0rln70nrprlo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reception
    ADD CONSTRAINT "FKoti6fusft2c0l0rln70nrprlo" FOREIGN KEY ("IM_CTRL_RECEPT") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_delegation_profil FKprbfye1829vayfrfla34t55v0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delegation_profil
    ADD CONSTRAINT "FKprbfye1829vayfrfla34t55v0" FOREIGN KEY ("ID_PROFILE_DELEGANT") REFERENCES public.tr_profile("ID_PROFILE");


--
-- Name: t_dispatch FKq5jueh0h0pfxr2nx0odttr2lh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_dispatch
    ADD CONSTRAINT "FKq5jueh0h0pfxr2nx0odttr2lh" FOREIGN KEY ("IM_CTRL_MEMBRE") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_tranche FKq6waym2p60mhih1xit12dwdij; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_tranche
    ADD CONSTRAINT "FKq6waym2p60mhih1xit12dwdij" FOREIGN KEY ("ID_LOT") REFERENCES public.t_lot("ID_LOT");


--
-- Name: t_lettre_renvoi FKqvikyx51a0djjll40hqjpytn3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi
    ADD CONSTRAINT "FKqvikyx51a0djjll40hqjpytn3" FOREIGN KEY ("ID_EXAMEN") REFERENCES public.t_examen("ID_EXAMEN");


--
-- Name: tr_controleur FKqwa1ayiamfjawbmtt924ti77m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tr_controleur
    ADD CONSTRAINT "FKqwa1ayiamfjawbmtt924ti77m" FOREIGN KEY ("ID_PROFILE") REFERENCES public.tr_profile("ID_PROFILE");


--
-- Name: t_pv_examen FKr0mj89eef8yl3ryvpvkpcyn28; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT "FKr0mj89eef8yl3ryvpvkpcyn28" FOREIGN KEY ("IM_CTRL_MEMBRE") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_reception FKr13elvopl982nefxvuu3yt3cl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reception
    ADD CONSTRAINT "FKr13elvopl982nefxvuu3yt3cl" FOREIGN KEY ("ID_RECEPTION_PREC") REFERENCES public.t_reception("ID_RECEPTION");


--
-- Name: t_audit_log FKr1qn0v522wyn3h3a7cyq93v8v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_audit_log
    ADD CONSTRAINT "FKr1qn0v522wyn3h3a7cyq93v8v" FOREIGN KEY ("SESSION_ID") REFERENCES public.t_session_utilisateur("ID_SESSION");


--
-- Name: t_message FKr51atbyph2bwcitf2xp41vp5x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_message
    ADD CONSTRAINT "FKr51atbyph2bwcitf2xp41vp5x" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_pv_examen FKr6gk2ia86n863vbgng6jmacw3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_pv_examen
    ADD CONSTRAINT "FKr6gk2ia86n863vbgng6jmacw3" FOREIGN KEY ("ID_EXAMEN") REFERENCES public.t_examen("ID_EXAMEN");


--
-- Name: t_prmp_entite FKra6wi6qdtx782sv901vd3skg6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_prmp_entite
    ADD CONSTRAINT "FKra6wi6qdtx782sv901vd3skg6" FOREIGN KEY ("ID_PRMP") REFERENCES public.t_prmp("ID_PRMP");


--
-- Name: t_echeance FKrw276tcpdyfctsufwp6gmsvsj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_echeance
    ADD CONSTRAINT "FKrw276tcpdyfctsufwp6gmsvsj" FOREIGN KEY ("ID_DETAIL") REFERENCES public.t_marche("ID_DETAIL");


--
-- Name: t_demande_retrait FKs8jrp1qoxu9aqsftnyml53kou; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait
    ADD CONSTRAINT "FKs8jrp1qoxu9aqsftnyml53kou" FOREIGN KEY ("IM_CTRL_CC") REFERENCES public.tr_controleur("IM_CONTROLEUR");


--
-- Name: t_anomalie FKsajf1wx1c8k4jlqq8twblky82; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_anomalie
    ADD CONSTRAINT "FKsajf1wx1c8k4jlqq8twblky82" FOREIGN KEY ("ID_PPM") REFERENCES public.t_ppm("ID_PPM");


--
-- Name: t_reception FKspcoc585llcufu553tixlxtc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_reception
    ADD CONSTRAINT "FKspcoc585llcufu553tixlxtc" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_demande_retrait FKt5xn6ktyedtb5jylgercvedue; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_demande_retrait
    ADD CONSTRAINT "FKt5xn6ktyedtb5jylgercvedue" FOREIGN KEY ("ID_DOSSIER") REFERENCES public.t_dossier("ID_DOSSIER");


--
-- Name: t_lettre_renvoi_lue fk_lettre_lue_lettre; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_lettre_renvoi_lue
    ADD CONSTRAINT fk_lettre_lue_lettre FOREIGN KEY ("ID_LETTRE") REFERENCES public.t_lettre_renvoi("ID_LETTRE");


--
-- PostgreSQL database dump complete
--


