-- =====================================================================================================
-- V32 — Pré-contrôle assisté du PPM (assistant IA, lot 3) : LE SOCLE DE DONNÉES.
--
-- Ce que le lot 3 demande (docs/plan-assistant-ia.md, §4, lot 3) : signaler à la PRMP les problèmes de
-- son PPM avant qu'elle ne soumette, et au contrôleur les points à regarder avant qu'il n'examine ;
-- chacun pouvant ÉCARTER un signalement en le motivant. Les règles détectent, l'IA explique (3.a).
-- Cette migration ne pose que les DONNÉES qui manquaient — aucune règle, aucun endpoint.
--
-- 1. tr_seuil_marche — LE RÉFÉRENTIEL DE SEUILS, NEUF, DATÉ ET ADMINISTRABLE.
--    t_seuil et t_regle_passation ont été supprimées le 2026-07-04 (c432e73) avec la détermination
--    automatique du mode : le PPM officiel ne porte pas de « situation » et le mode y est SAISI. Le
--    lot 3 ne revient pas sur cette décision — ce référentiel ne détermine ni ne bloque rien, il sert
--    UNIQUEMENT À SIGNALER. Sur le modèle d'AGPM_SEUIL_MONTANT : aucune valeur numérique dans le code.
--    Ses valeurs sont celles de l'arrêté n° 13 156/2019-MEF du 4 juillet 2019 (remis par le pilote), et
--    elles sont HORS TAXES — comme les montants estimatifs de PRS (arbitrage pilote du 2026-09-18) :
--    la comparaison est directe, sans conversion.
--    DATÉ, parce qu'un arrêté est remplacé : une valeur a une DATE_EFFET et, une fois remplacée, une
--    DATE_FIN. Le pré-contrôle d'un plan lit le barème en vigueur à sa date, pas le dernier saisi.
--
-- 2. t_marche.CATEGORIE_SEUIL — CE QUI MANQUAIT POUR CHOISIR UNE LIGNE DU BARÈME.
--    L'arrêté distingue quatre catégories de prestations (construction/réhabilitation de routes,
--    entretien routier, travaux non routiers, fournitures et services) ; PRS n'a que trois natures
--    (Travaux, Fournitures, Services). Impossible, avec la seule nature, de dire quel seuil s'applique
--    à un marché de travaux. La catégorie se pose donc SUR LA LIGNE. Elle reste facultative : une ligne
--    sans catégorie n'est pas en faute, elle est seulement moins précise — le moteur de règles évaluera
--    alors les catégories plausibles de sa nature et ne signalera que si elles divergent (3.e, fatigue
--    d'alerte).
--
-- 3. t_anomalie — LE SIGNALEMENT DEVIENT ÉCARTABLE PAR UNE PRMP.
--    La table du MLD portait déjà STATUT + COMMENTAIRE_TRAITEMENT : « écarter en motivant » était
--    modélisé. Mais IM_TRAITEMENT est un varchar(7) joint à tr_controleur, alors qu'un ID_PRMP fait 10
--    caractères : AUCUNE PRMP NE POUVAIT ÊTRE ENREGISTRÉE comme ayant écarté un signalement. C'est le
--    défaut C3 de l'audit du 2026-09-14, pour la troisième fois (V29 sur t_tache_dossier.IM_ACTEUR,
--    V31 sur t_session_utilisateur.IM_CONTROLEUR) : la colonne est élargie, la FK tombe, et un
--    TYPE_ACTEUR_TRAITEMENT dit de quel référentiel la référence vient — comme la claim acteurType du
--    jeton. GRAVITE passe de 10 à 20 caractères : « PRIORITAIRE » en fait 11.
--
-- 4. t_anomalie_ligne — LES SIGNALEMENTS INTER-LIGNES.
--    Le fractionnement illicite est le cœur du lot, et il ne concerne JAMAIS une ligne seule : « ces
--    trois lignes, compte X, cumul Y ≥ seuil Z ». ID_DETAIL (une ligne) ne peut pas le porter. La table
--    enfant liste les lignes visées ; ID_DETAIL reste réservé aux signalements d'une seule ligne.
--
-- CE QUI N'EST PAS ICI, ET C'EST DÉLIBÉRÉ :
--   * les RÈGLES (t_regle_anomalie) et le point de contrôle « fractionnement » de la grille
--     (tr_points_ctrl) sont des données de référentiel qui accompagnent le code des règles : elles
--     viendront avec lui, par un seeder idempotent au démarrage — tr_points_ctrl porte deux FK vers des
--     référentiels qu'aucune migration ne crée (voir l'encadré de V16) ;
--   * aucun seuil de PROCÉDURE n'est posé pour les prestations intellectuelles : l'arrêté n'en fixe
--     pas. Leur publicité relève du décret n° 2019-1310 (modifié par le décret n° 2022-1091) ; le
--     pilote a tranché le 2026-09-18 la seule valeur qui manquait — 100 000 000 Ar — et elle est semée
--     ci-dessous avec sa base légale, donc corrigeable sans redéploiement le jour où elle bouge.
--
-- Idempotente : CREATE TABLE / ADD COLUMN / CREATE INDEX IF NOT EXISTS, DROP CONSTRAINT dynamique,
-- semis borné par NOT EXISTS, et l'élargissement d'un varchar est une opération de métadonnées en
-- PostgreSQL (pas de réécriture de table), sans effet rejoué sur une colonne déjà élargie.
-- =====================================================================================================

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 1. Le référentiel de seuils
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.tr_seuil_marche (
    "ID_SEUIL"        integer GENERATED BY DEFAULT AS IDENTITY,
    "TYPE_SEUIL"      character varying(40) NOT NULL,
    "CATEGORIE_SEUIL" character varying(40) NOT NULL,
    "BAREME"          character varying(20) NOT NULL,
    "MONTANT"         numeric(38,2) NOT NULL,
    "DELAI_MIN_JOURS" integer,
    "DATE_EFFET"      date NOT NULL,
    "DATE_FIN"        date,
    "BASE_LEGALE"     character varying(300),
    "IM_ACTEUR"       character varying(10),
    "DATE_MAJ"        timestamp(6) without time zone,
    CONSTRAINT tr_seuil_marche_pkey PRIMARY KEY ("ID_SEUIL"),
    CONSTRAINT uq_seuil_marche_effet UNIQUE ("TYPE_SEUIL", "CATEGORIE_SEUIL", "BAREME", "DATE_EFFET"),
    CONSTRAINT ck_seuil_marche_type CHECK ("TYPE_SEUIL" IN (
        'CONTROLE_A_PRIORI', 'APPEL_OFFRES_OUVERT', 'CONSULTATION',
        'MANIFESTATION_INTERET_PRESSE', 'MANIFESTATION_INTERET_AFFICHAGE')),
    CONSTRAINT ck_seuil_marche_categorie CHECK ("CATEGORIE_SEUIL" IN (
        'ROUTES_CONSTRUCTION', 'ENTRETIEN_ROUTIER', 'TRAVAUX_NON_ROUTIERS',
        'FOURNITURES_SERVICES', 'PRESTATIONS_INTELLECTUELLES')),
    CONSTRAINT ck_seuil_marche_bareme CHECK ("BAREME" IN ('CENTRAL', 'DECONCENTRE')),
    CONSTRAINT ck_seuil_marche_montant CHECK ("MONTANT" >= 0),
    CONSTRAINT ck_seuil_marche_periode CHECK ("DATE_FIN" IS NULL OR "DATE_FIN" > "DATE_EFFET")
);

CREATE INDEX IF NOT EXISTS idx_seuil_marche_vigueur
    ON public.tr_seuil_marche USING btree ("TYPE_SEUIL", "CATEGORIE_SEUIL", "BAREME", "DATE_EFFET");

COMMENT ON TABLE public.tr_seuil_marche IS
    'Referentiel DATE des seuils de marches publics (arrete n 13 156/2019-MEF du 4 juillet 2019). '
    'Montants HORS TAXES, en Ariary. Sert UNIQUEMENT a signaler : le mode de passation reste saisi, '
    'rien n''est determine ni bloque. Administrable sans redeploiement.';
COMMENT ON COLUMN public.tr_seuil_marche."TYPE_SEUIL" IS
    'CONTROLE_A_PRIORI = au-dela, le marche est soumis au controle a priori de la Commission. '
    'APPEL_OFFRES_OUVERT / CONSULTATION = seuils de procedure (art. 2, 2). '
    'MANIFESTATION_INTERET_* = forme de publicite des prestations intellectuelles.';
COMMENT ON COLUMN public.tr_seuil_marche."BAREME" IS
    'CENTRAL = Etat, organismes publics centraux, etablissements publics nationaux, societes a '
    'participation majoritaire publique, entites beneficiant de financement public. DECONCENTRE = '
    'organismes deconcentres, collectivites decentralisees et leurs etablissements publics. Le bareme '
    'd''une entite se DEDUIT de son organisme de controle : CNM (tr_localite ANT) -> CENTRAL, CRM -> '
    'DECONCENTRE (arbitrage pilote du 2026-09-18).';
COMMENT ON COLUMN public.tr_seuil_marche."DELAI_MIN_JOURS" IS
    'Delai minimal de publicite attache au franchissement, quand le texte en attache un (prestations '
    'intellectuelles : 30 jours par voie de presse, 10 jours par affichage). NULL sinon.';
COMMENT ON COLUMN public.tr_seuil_marche."DATE_FIN" IS
    'NULL = valeur en vigueur. Une valeur remplacee n''est jamais effacee : elle est bornee, pour que '
    'le pre-controle d''un plan ancien reste lisible avec le bareme de son temps.';

-- ── Le barème de l'arrêté n° 13 156/2019-MEF, semé une fois. Le pilote et les chefs l'ajustent ensuite
--    depuis l'administration ; cette migration ne réécrit jamais une ligne déjà présente.
--    ⚠️ L'arrêté écrit, pour l'appel d'offres ouvert des routes en organisme déconcentré, « Deux
--    milliards cinq cent MILLE Ariary (2.500.000.000 Ar) » : les lettres et les chiffres divergent. Le
--    chiffre est le bon — moitié des 5 milliards du barème central, et valeur du tableau de seuils.pptx.
INSERT INTO public.tr_seuil_marche
    ("TYPE_SEUIL", "CATEGORIE_SEUIL", "BAREME", "MONTANT", "DELAI_MIN_JOURS", "DATE_EFFET", "BASE_LEGALE")
SELECT v."TYPE_SEUIL", v."CATEGORIE_SEUIL", v."BAREME", v."MONTANT", v."DELAI_MIN_JOURS",
       v."DATE_EFFET", v."BASE_LEGALE"
FROM (VALUES
    -- Seuils de contrôle a priori — art. 2, 1°) a) et b)
    ('CONTROLE_A_PRIORI', 'ROUTES_CONSTRUCTION',         'CENTRAL',     10000000000.00, NULL::integer, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) a)'),
    ('CONTROLE_A_PRIORI', 'ENTRETIEN_ROUTIER',           'CENTRAL',      5000000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) a)'),
    ('CONTROLE_A_PRIORI', 'TRAVAUX_NON_ROUTIERS',        'CENTRAL',       750000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) a)'),
    ('CONTROLE_A_PRIORI', 'FOURNITURES_SERVICES',        'CENTRAL',       300000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) a)'),
    ('CONTROLE_A_PRIORI', 'PRESTATIONS_INTELLECTUELLES', 'CENTRAL',       300000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) a) — même seuil que fournitures et services'),
    ('CONTROLE_A_PRIORI', 'ROUTES_CONSTRUCTION',         'DECONCENTRE',  5000000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) b)'),
    ('CONTROLE_A_PRIORI', 'ENTRETIEN_ROUTIER',           'DECONCENTRE',  2500000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) b)'),
    ('CONTROLE_A_PRIORI', 'TRAVAUX_NON_ROUTIERS',        'DECONCENTRE',   350000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) b)'),
    ('CONTROLE_A_PRIORI', 'FOURNITURES_SERVICES',        'DECONCENTRE',   150000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) b)'),
    ('CONTROLE_A_PRIORI', 'PRESTATIONS_INTELLECTUELLES', 'DECONCENTRE',   150000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 1°) b) — même seuil que fournitures et services'),
    -- Seuils de procédure : appel d'offres ouvert obligatoire — art. 2, 2°) i°) a) et b)
    ('APPEL_OFFRES_OUVERT', 'ROUTES_CONSTRUCTION',       'CENTRAL',      5000000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) a)'),
    ('APPEL_OFFRES_OUVERT', 'ENTRETIEN_ROUTIER',         'CENTRAL',      2000000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) a)'),
    ('APPEL_OFFRES_OUVERT', 'TRAVAUX_NON_ROUTIERS',      'CENTRAL',       500000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) a)'),
    ('APPEL_OFFRES_OUVERT', 'FOURNITURES_SERVICES',      'CENTRAL',       150000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) a)'),
    ('APPEL_OFFRES_OUVERT', 'ROUTES_CONSTRUCTION',       'DECONCENTRE',  2500000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) b)'),
    ('APPEL_OFFRES_OUVERT', 'ENTRETIEN_ROUTIER',         'DECONCENTRE',  1000000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) b)'),
    ('APPEL_OFFRES_OUVERT', 'TRAVAUX_NON_ROUTIERS',      'DECONCENTRE',   250000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) b)'),
    ('APPEL_OFFRES_OUVERT', 'FOURNITURES_SERVICES',      'DECONCENTRE',    75000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) i°) b)'),
    -- Seuils de procédure : consultation d'entrepreneurs, fournisseurs ou prestataires — art. 2, 2°) ii°)
    ('CONSULTATION', 'ROUTES_CONSTRUCTION',              'CENTRAL',        50000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) a)'),
    ('CONSULTATION', 'ENTRETIEN_ROUTIER',                'CENTRAL',        30000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) a)'),
    ('CONSULTATION', 'TRAVAUX_NON_ROUTIERS',             'CENTRAL',        20000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) a)'),
    ('CONSULTATION', 'FOURNITURES_SERVICES',             'CENTRAL',         2500000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) a)'),
    ('CONSULTATION', 'ROUTES_CONSTRUCTION',              'DECONCENTRE',    25000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) b)'),
    ('CONSULTATION', 'ENTRETIEN_ROUTIER',                'DECONCENTRE',    15000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) b)'),
    ('CONSULTATION', 'TRAVAUX_NON_ROUTIERS',             'DECONCENTRE',    10000000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) b)'),
    ('CONSULTATION', 'FOURNITURES_SERVICES',             'DECONCENTRE',     1500000.00, NULL, DATE '2019-07-04', 'Arrêté n° 13 156/2019-MEF du 4 juillet 2019, art. 2, 2°) ii°) b)'),
    -- Publicité des prestations intellectuelles — hors arrêté (décret n° 2019-1310, arbitrage pilote du 2026-09-18)
    ('MANIFESTATION_INTERET_PRESSE',    'PRESTATIONS_INTELLECTUELLES', 'CENTRAL',     100000000.00, 30, DATE '2019-07-03', 'Décret n° 2019-1310 du 3 juillet 2019 modifié par le décret n° 2022-1091 ; manuel CNM de contrôle a priori (février 2026), p. 16 — arbitrage pilote du 2026-09-18'),
    ('MANIFESTATION_INTERET_PRESSE',    'PRESTATIONS_INTELLECTUELLES', 'DECONCENTRE', 100000000.00, 30, DATE '2019-07-03', 'Décret n° 2019-1310 du 3 juillet 2019 modifié par le décret n° 2022-1091 ; manuel CNM de contrôle a priori (février 2026), p. 16 — arbitrage pilote du 2026-09-18'),
    ('MANIFESTATION_INTERET_AFFICHAGE', 'PRESTATIONS_INTELLECTUELLES', 'CENTRAL',             0.00, 10, DATE '2019-07-03', 'Décret n° 2019-1310 du 3 juillet 2019 modifié par le décret n° 2022-1091 — publicité par affichage en dessous du seuil de la voie de presse'),
    ('MANIFESTATION_INTERET_AFFICHAGE', 'PRESTATIONS_INTELLECTUELLES', 'DECONCENTRE',         0.00, 10, DATE '2019-07-03', 'Décret n° 2019-1310 du 3 juillet 2019 modifié par le décret n° 2022-1091 — publicité par affichage en dessous du seuil de la voie de presse')
) AS v("TYPE_SEUIL", "CATEGORIE_SEUIL", "BAREME", "MONTANT", "DELAI_MIN_JOURS", "DATE_EFFET", "BASE_LEGALE")
WHERE NOT EXISTS (
    SELECT 1 FROM public.tr_seuil_marche s
    WHERE s."TYPE_SEUIL" = v."TYPE_SEUIL" AND s."CATEGORIE_SEUIL" = v."CATEGORIE_SEUIL"
      AND s."BAREME" = v."BAREME" AND s."DATE_EFFET" = v."DATE_EFFET"
);

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 2. La catégorie de seuil de la ligne
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_marche
    ADD COLUMN IF NOT EXISTS "CATEGORIE_SEUIL" character varying(40);

ALTER TABLE public.t_marche DROP CONSTRAINT IF EXISTS "ck_marche_categorie_seuil";
ALTER TABLE public.t_marche ADD CONSTRAINT "ck_marche_categorie_seuil"
    CHECK ("CATEGORIE_SEUIL" IS NULL OR "CATEGORIE_SEUIL" IN (
        'ROUTES_CONSTRUCTION', 'ENTRETIEN_ROUTIER', 'TRAVAUX_NON_ROUTIERS',
        'FOURNITURES_SERVICES', 'PRESTATIONS_INTELLECTUELLES'));

COMMENT ON COLUMN public.t_marche."CATEGORIE_SEUIL" IS
    'Categorie de prestations de l''arrete n 13 156/2019-MEF, qui choisit la ligne du bareme. '
    'FACULTATIVE : NULL = non precisee, le pre-controle evalue alors les categories plausibles de la '
    'nature et ne signale que si elles divergent. Ne determine ni ne bloque rien.';

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 3. Le signalement : écartable par une PRMP, rattaché à la grille, réconcilié d'une exécution à
--    l'autre
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- (a) La FK vers tr_controleur d'abord : une PRMP n'y figure pas, l'écartement serait refusé en 23503.
--     Retrait par recherche dans le catalogue et non par nom en dur : « FK46sxegbovs81uk7h7bx7634hx »
--     est un nom engendré par Hibernate (V1, issu d'un pg_dump), qu'une base recréée autrement n'a pas.
DO $$
DECLARE nom text;
BEGIN
    SELECT con.conname INTO nom
    FROM pg_constraint con
    JOIN pg_class ref ON ref.oid = con.confrelid
    JOIN pg_class tab ON tab.oid = con.conrelid
    WHERE tab.relname = 't_anomalie' AND ref.relname = 'tr_controleur' AND con.contype = 'f'
    LIMIT 1;
    IF nom IS NOT NULL THEN
        EXECUTE format('ALTER TABLE public.t_anomalie DROP CONSTRAINT %I', nom);
    END IF;
END $$;

ALTER TABLE public.t_anomalie ALTER COLUMN "IM_TRAITEMENT" TYPE character varying(10);
ALTER TABLE public.t_anomalie ALTER COLUMN "GRAVITE" TYPE character varying(20);

-- Même élargissement sur la gravité par défaut d'une RÈGLE : « A_VERIFIER » tient tout juste dans 10
-- caractères, « PRIORITAIRE » en fait 11 — une règle de fractionnement n'aurait pas pu déclarer sa
-- gravité par défaut.
ALTER TABLE public.t_regle_anomalie ALTER COLUMN "GRAVITE_DEFAUT" TYPE character varying(20);

ALTER TABLE public.t_anomalie
    ADD COLUMN IF NOT EXISTS "TYPE_ACTEUR_TRAITEMENT" character varying(20),
    ADD COLUMN IF NOT EXISTS "ID_POINT_CTRL"          integer,
    ADD COLUMN IF NOT EXISTS "CLE_SIGNALEMENT"        character varying(200),
    ADD COLUMN IF NOT EXISTS "SUGGESTION"             text,
    ADD COLUMN IF NOT EXISTS "DATE_LEVEE"             timestamp(6) without time zone,
    ADD COLUMN IF NOT EXISTS "DETAIL_LEVEE"           text,
    ADD COLUMN IF NOT EXISTS "FIGE"                   boolean NOT NULL DEFAULT false;

ALTER TABLE public.t_anomalie DROP CONSTRAINT IF EXISTS "fk_anomalie_point_ctrl";
ALTER TABLE public.t_anomalie ADD CONSTRAINT "fk_anomalie_point_ctrl"
    FOREIGN KEY ("ID_POINT_CTRL") REFERENCES public.tr_points_ctrl("ID_POINT_CTRL");

-- ⚠️ CHECK « NOT VALID » : la table est vide dans toutes les bases connues (rien ne l'écrit depuis la
--    baseline), mais une base inconnue n'a pas à faire échouer la migration sur une ligne héritée. Les
--    contraintes s'appliquent donc aux écritures nouvelles, et les lignes anciennes sont tolérées.
ALTER TABLE public.t_anomalie DROP CONSTRAINT IF EXISTS "ck_anomalie_statut";
ALTER TABLE public.t_anomalie ADD CONSTRAINT "ck_anomalie_statut"
    CHECK ("STATUT" IS NULL OR "STATUT" IN ('OUVERT', 'ECARTE', 'LEVE_MODIFICATION')) NOT VALID;
ALTER TABLE public.t_anomalie DROP CONSTRAINT IF EXISTS "ck_anomalie_source";
ALTER TABLE public.t_anomalie ADD CONSTRAINT "ck_anomalie_source"
    CHECK ("SOURCE" IS NULL OR "SOURCE" IN ('REGLE', 'IA')) NOT VALID;
ALTER TABLE public.t_anomalie DROP CONSTRAINT IF EXISTS "ck_anomalie_gravite";
ALTER TABLE public.t_anomalie ADD CONSTRAINT "ck_anomalie_gravite"
    CHECK ("GRAVITE" IS NULL OR "GRAVITE" IN ('A_VERIFIER', 'PRIORITAIRE')) NOT VALID;
ALTER TABLE public.t_anomalie DROP CONSTRAINT IF EXISTS "ck_anomalie_type_acteur";
ALTER TABLE public.t_anomalie ADD CONSTRAINT "ck_anomalie_type_acteur"
    CHECK ("TYPE_ACTEUR_TRAITEMENT" IS NULL OR "TYPE_ACTEUR_TRAITEMENT" IN ('CONTROLEUR', 'PRMP')) NOT VALID;

-- Réconciliation d'une exécution à l'autre : la clé dit L'IDENTITÉ du signalement (règle + objet visé),
-- indépendamment de son numéro. Le même défaut re-détecté RETROUVE sa ligne — donc son écartement et
-- son motif ; un signalement qui ne ressort plus est LEVÉ, jamais effacé (3.f, condition 3).
CREATE UNIQUE INDEX IF NOT EXISTS uq_anomalie_cle
    ON public.t_anomalie USING btree ("ID_PPM", "CLE_SIGNALEMENT")
    WHERE "CLE_SIGNALEMENT" IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_anomalie_ppm_statut
    ON public.t_anomalie USING btree ("ID_PPM", "STATUT");

COMMENT ON COLUMN public.t_anomalie."IM_TRAITEMENT" IS
    'Reference de l''acteur qui a traite le signalement : IM_CONTROLEUR (7) OU ID_PRMP (10). La FK vers '
    'tr_controleur a ete retiree en V32 — une PRMP n''y figure pas. TYPE_ACTEUR_TRAITEMENT dit laquelle.';
COMMENT ON COLUMN public.t_anomalie."CLE_SIGNALEMENT" IS
    'Identite stable du signalement dans son PPM (code de regle + objet vise, normalise) : permet de '
    'RETROUVER un signalement deja ecarte au lieu d''en creer un double, et de reperer celui qui a '
    'disparu apres modification du plan.';
COMMENT ON COLUMN public.t_anomalie."FIGE" IS
    'Vrai des la soumission du plan : un ecartement fige ne se defait plus (3.f, condition 3).';
COMMENT ON COLUMN public.t_anomalie."DETAIL_LEVEE" IS
    'Ce qui a change dans le plan et a fait disparaitre le signalement — c''est ce que le controleur lit '
    'quand une PRMP fait taire l''alarme en modifiant ses lignes.';

-- La séquence de PK manquait : V5 a généralisé les séquences mais a sauté t_anomalie, qu'aucun code
-- n'alimentait. Le pré-contrôle, lui, en crée.
CREATE SEQUENCE IF NOT EXISTS public.seq_anomalie;
SELECT setval('public.seq_anomalie', COALESCE((SELECT MAX("ID_ANOMALIE") FROM public.t_anomalie), 0) + 1, false);

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 4. Les lignes visées par un signalement inter-lignes
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_anomalie_ligne (
    "ID_ANOMALIE" integer NOT NULL,
    "ID_DETAIL"   integer NOT NULL,
    "MONTANT"     numeric(38,2),
    CONSTRAINT t_anomalie_ligne_pkey PRIMARY KEY ("ID_ANOMALIE", "ID_DETAIL"),
    CONSTRAINT fk_anomalie_ligne_anomalie FOREIGN KEY ("ID_ANOMALIE")
        REFERENCES public.t_anomalie("ID_ANOMALIE") ON DELETE CASCADE,
    CONSTRAINT fk_anomalie_ligne_detail FOREIGN KEY ("ID_DETAIL")
        REFERENCES public.t_marche("ID_DETAIL") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_anomalie_ligne_detail
    ON public.t_anomalie_ligne USING btree ("ID_DETAIL");

COMMENT ON TABLE public.t_anomalie_ligne IS
    'Lignes de marche visees par un signalement INTER-LIGNES (fractionnement : « ces trois lignes, '
    'compte X, cumul Y >= seuil Z »). MONTANT = montant en vigueur de la ligne au moment de la '
    'detection, garde pour que l''explication reste lisible apres modification du plan.';
