-- =====================================================================================================
-- V34 — L'INTÉRIM DÉSIGNÉ dans le circuit de contrôle, lot 1 : Président et Chef de commission
-- (demande front du 2026-09-21, frontend/docs/demande-backend-2026-09-21-gestion-interim.md, arbitrée
-- par le pilote le 2026-09-21 ; ADR-0008).
--
-- LE CONSTAT. L'intérim n'existait que comme exception ponctuelle, auto-déclarée AU MOMENT DE L'ACTE :
-- t_dispatch.INTERIM_DISPATCH (un CC dispatche hors de sa localité en levant le drapeau) et le visa par
-- intérim (V11 : un P/CC du périmètre, non dispatcheur, vise en joignant une note PDF). Personne ne
-- savait à l'avance qui supplée qui ; le Président n'était suppléé par personne — visa de ses dispatchs,
-- pré-dispatch central, part Président : un point unique de défaillance.
--
-- CE QUI EST AJOUTÉ. Une DÉSIGNATION datée : « X (titulaire, Président ou CC) est absent du D1 au D2 ;
-- Y (intérimaire) agit à sa place, dans SON périmètre, sous sa PROPRE identité ». Calquée sur le mandat
-- PRMP (période, référence, pièce, jamais modifiée ni effacée, close par une révocation) et croisée avec
-- la garde centrale des délégations, qui devient « titulaire OU délégation OU intérimaire actif ».
--
-- LE STATUT N'EST PAS UNE COLONNE. A_VENIR, ACTIF, ACHEVE, REVOQUE se déduisent des dates à la date du
-- jour (comme StatutMandat) ; ici la colonne-cache de t_mandat n'est même pas reprise : elle ne serait
-- qu'une copie de la dérivation, libre de diverger à minuit. Seule DATE_REVOCATION est un acte.
--
-- LA PIÈCE DANS UNE TABLE À PART. Obligatoire (arbitrage Q4) et posée dans le même geste que la
-- désignation (multipart) : en base et non sur le FSX, pour la raison de V11 — un rollback ne doit pas
-- laisser de fichier orphelin. Mais PAS en colonne de t_interim, contrairement à la note de V11 : cette
-- table est lue à CHAQUE requête d'un CC ou d'un Membre (contexte d'intérim, garde centrale, accueil
-- « À faire »), et charger un PDF de plusieurs mégaoctets pour savoir qui supplée qui serait absurde.
-- Même raisonnement que t_piece_demande_retrait (« pour que les listes ne chargent jamais le contenu
-- binaire »). Clé primaire PARTAGÉE : une pièce par intérim, jamais orpheline (FK ON DELETE CASCADE, la
-- seule FK de cette migration — un intérim ne se supprime pas, mais si l'on purgeait une base de recette
-- la pièce partirait avec lui).
--
-- LES TRACES « PAR INTÉRIM DE X » (ID_INTERIM + INTERIM_DE) sur cinq tables :
--   t_dispatch      : le dispatch posé par un intérimaire. ⚠️ IM_CTRL_DISPATCH porte le TITULAIRE, pas
--                     l'intérimaire (ADR-0008) : tout l'aval — « le dispatcheur vise », discriminant de
--                     la navette à deux niveaux (profil du dispatcheur), retrait par le dispatcheur —
--                     lit cette colonne, et doit continuer de désigner celui dont c'est le rôle. Qui a
--                     cliqué se lit sur ID_INTERIM (t_interim.IM_INTERIMAIRE) et au journal.
--   t_pv_examen     : le visa posé par un intérimaire désigné. VISE_PAR_INTERIM (V11) reste vrai — c'est
--                     la même qualification, et la même mention « — par intérim » sur les PV régionaux
--                     (arbitrage Q5) — mais NOTE_INTERIM reste nulle : la désignation EST la
--                     justification. ID_INTERIM non nul distingue l'intérim désigné du repli ponctuel.
--   t_action_dossier, t_tache_dossier : journal et chronométrage — l'acteur reste celui qui a agi
--                     (l'intérimaire, sous sa propre identité) ; INTERIM_DE dit au nom de qui.
--   t_notification  : la COPIE adressée à l'intérimaire actif d'un titulaire notifié (arbitrage Q6 :
--                     copie, jamais redirection — le titulaire garde son historique).
--
-- PAS DE CLÉ ÉTRANGÈRE de ces cinq colonnes vers t_interim, comme en V19/V30 : t_action_dossier,
-- t_tache_dossier et t_notification sont purgées avec le circuit, et t_dispatch supprimée au retrait ;
-- une FK n'y protégerait rien et compliquerait la purge. INTERIM_DE est dimensionnée à 10 comme toute
-- référence d'acteur depuis V29/V31.
--
-- AUCUNE REPRISE. Aucun intérim n'a jamais été désigné : les tables neuves sont vides, les colonnes
-- neuves nulles — c'est la valeur juste.
--
-- Idempotente : CREATE TABLE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS, CREATE INDEX IF NOT EXISTS.
-- =====================================================================================================

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 1. La désignation
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_interim (
    "ID_INTERIM"               integer GENERATED BY DEFAULT AS IDENTITY,
    "IM_TITULAIRE"             character varying(10) NOT NULL,
    "NOM_TITULAIRE"            character varying(200) NOT NULL,
    "PROFIL_TITULAIRE"         character varying(30) NOT NULL,
    "ID_LOCALITE_TITULAIRE"    character varying(5),
    "IM_INTERIMAIRE"           character varying(10) NOT NULL,
    "NOM_INTERIMAIRE"          character varying(200) NOT NULL,
    "PROFIL_INTERIMAIRE"       character varying(30) NOT NULL,
    "ID_LOCALITE_INTERIMAIRE"  character varying(5),
    "DATE_DEBUT"               date NOT NULL,
    "DATE_FIN"                 date,
    "MOTIF"                    character varying(20) NOT NULL,
    "REFERENCE"                character varying(100) NOT NULL,
    "PIECE_NOM"                character varying(255),
    "PIECE_TAILLE"             bigint,
    "DESIGNE_PAR"              character varying(10) NOT NULL,
    "NOM_DESIGNE_PAR"          character varying(200),
    "DATE_DESIGNATION"         timestamp(6) without time zone NOT NULL,
    "DATE_REVOCATION"          date,
    "MOTIF_REVOCATION"         character varying(255),
    "REVOQUE_PAR"              character varying(10),
    CONSTRAINT t_interim_pkey PRIMARY KEY ("ID_INTERIM"),
    CONSTRAINT ck_interim_personnes CHECK ("IM_TITULAIRE" <> "IM_INTERIMAIRE"),
    CONSTRAINT ck_interim_profil_titulaire CHECK ("PROFIL_TITULAIRE" IN ('PRESIDENT', 'CHEF_COMMISSION')),
    CONSTRAINT ck_interim_motif CHECK ("MOTIF" IN ('CONGE', 'MISSION', 'MALADIE', 'VACANCE_POSTE', 'AUTRE')),
    CONSTRAINT ck_interim_periode CHECK ("DATE_FIN" IS NULL OR "DATE_FIN" >= "DATE_DEBUT"),
    CONSTRAINT ck_interim_fin_obligatoire CHECK ("DATE_FIN" IS NOT NULL OR "MOTIF" = 'VACANCE_POSTE')
);

-- Lecture 1 — qui supplée X aujourd'hui (garde centrale étendue, copie des notifications).
CREATE INDEX IF NOT EXISTS idx_interim_titulaire
    ON public.t_interim USING btree ("IM_TITULAIRE", "DATE_DEBUT");

-- Lecture 2 — qui Y supplée aujourd'hui (contexte d'intérim posé à chaque requête d'un CC ou d'un Membre).
CREATE INDEX IF NOT EXISTS idx_interim_interimaire
    ON public.t_interim USING btree ("IM_INTERIMAIRE", "DATE_DEBUT");

COMMENT ON TABLE public.t_interim IS
    'Interim DESIGNE (lot 1, 2026-09-21) : le titulaire (President ou CC) absent designe lui-meme '
    'son interimaire, qui agit a sa place dans SON perimetre sous sa PROPRE identite. Jamais modifie '
    'ni efface : une prolongation est un nouvel interim, une fin avant terme une revocation. Le statut '
    '(A_VENIR, ACTIF, ACHEVE, REVOQUE) se DEDUIT des dates a la date du jour, il n''est pas stocke.';
COMMENT ON COLUMN public.t_interim."NOM_TITULAIRE" IS
    'Nom FIGE a la designation (« NOM Prenoms »), comme t_mandat.TITULAIRE : l''historique reste lisible '
    'meme si la fiche change.';
COMMENT ON COLUMN public.t_interim."PROFIL_TITULAIRE" IS
    'Profil du titulaire a la designation, celui que l''interimaire exerce : PRESIDENT ou CHEF_COMMISSION '
    'dans ce lot. Les autres profils ne declarent pas d''absence (lot 2 sur demande).';
COMMENT ON COLUMN public.t_interim."ID_LOCALITE_TITULAIRE" IS
    'Localite du titulaire a la designation ; NULL pour le President (toutes localites). C''est le '
    'perimetre dans lequel l''interimaire agit.';
COMMENT ON COLUMN public.t_interim."DATE_FIN" IS
    'Borne INCLUSE. Obligatoire, sauf motif VACANCE_POSTE (contrainte ck_interim_fin_obligatoire) : une '
    'absence a un terme ; une prolongation est un NOUVEL interim, comme la reconduction d''un mandat.';
COMMENT ON COLUMN public.t_interim."DATE_REVOCATION" IS
    'Fin avant terme, a effet a cette date (au plus tot le jour de la revocation). REVOQUE prime sur les '
    'dates des ce jour ; les actes poses avant restent ceux de l''interimaire, traces comme tels.';
COMMENT ON COLUMN public.t_interim."DESIGNE_PAR" IS
    'Qui a cree : le titulaire lui-meme (regle), ou l''Administrateur (repli quand l''absent n''a rien '
    'declare, §B3 de la demande, a confirmer par le pilote).';

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 2. La pièce, à part
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_interim_piece (
    "ID_INTERIM"  integer NOT NULL,
    "CONTENU"     bytea NOT NULL,
    CONSTRAINT t_interim_piece_pkey PRIMARY KEY ("ID_INTERIM"),
    CONSTRAINT fk_interim_piece_interim FOREIGN KEY ("ID_INTERIM")
        REFERENCES public.t_interim ("ID_INTERIM") ON DELETE CASCADE
);

COMMENT ON TABLE public.t_interim_piece IS
    'Piece PDF de la designation (note de service, decision), OBLIGATOIRE (arbitrage Q4). Table a part '
    'pour que t_interim, lue a chaque requete d''un CC ou d''un Membre, ne charge jamais le binaire. '
    'Format reconnu sur les octets d''en-tete, jamais sur le nom : seul le PDF est accepte, d''ou '
    'l''absence de colonne FORMAT (comme en V11). Nom et taille sont sur t_interim (PIECE_NOM, '
    'PIECE_TAILLE), pour servir la liste sans jointure.';

-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- 3. Les traces « par intérim de X »
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_dispatch ADD COLUMN IF NOT EXISTS "ID_INTERIM" integer;
COMMENT ON COLUMN public.t_dispatch."ID_INTERIM" IS
    'V34 : non nul quand le dispatch (ou la reattribution) a ete pose par un interimaire DESIGNE. '
    'IM_CTRL_DISPATCH porte alors le TITULAIRE, pas l''interimaire (ADR-0008) : c''est le dispatcheur '
    'que l''aval reconnait (visa, retrait, discriminant du deux-niveaux). L''auteur reel se lit sur '
    't_interim.IM_INTERIMAIRE. Distinct d''INTERIM_DISPATCH, le repli ponctuel sans designation.';

ALTER TABLE public.t_pv_examen ADD COLUMN IF NOT EXISTS "ID_INTERIM" integer;
ALTER TABLE public.t_pv_examen ADD COLUMN IF NOT EXISTS "INTERIM_DE" character varying(10);
COMMENT ON COLUMN public.t_pv_examen."ID_INTERIM" IS
    'V34 : visa pose par un interimaire DESIGNE (t_interim). VISE_PAR_INTERIM est alors vrai et '
    'NOTE_INTERIM nulle : la designation est la justification. Nul pour le visa par intérim PONCTUEL '
    'de V11 (note PDF) comme pour un visa normal.';
COMMENT ON COLUMN public.t_pv_examen."INTERIM_DE" IS
    'V34 : le titulaire supplee (dispatcheur, ou President sur une navette a deux niveaux). Le viseur '
    'reste porte par IM_CTRL_PRESIDENT / IM_CTRL_CC : c''est l''interimaire, sous sa propre identite.';

ALTER TABLE public.t_action_dossier ADD COLUMN IF NOT EXISTS "ID_INTERIM" integer;
ALTER TABLE public.t_action_dossier ADD COLUMN IF NOT EXISTS "INTERIM_DE" character varying(10);
COMMENT ON COLUMN public.t_action_dossier."INTERIM_DE" IS
    'V34 : geste pose PAR INTERIM de ce titulaire (matricule). L''auteur de la ligne reste celui qui a '
    'agi. Nul hors interim designe.';

ALTER TABLE public.t_tache_dossier ADD COLUMN IF NOT EXISTS "ID_INTERIM" integer;
ALTER TABLE public.t_tache_dossier ADD COLUMN IF NOT EXISTS "INTERIM_DE" character varying(10);
COMMENT ON COLUMN public.t_tache_dossier."INTERIM_DE" IS
    'V34 : passage d''etape tenu PAR INTERIM de ce titulaire. IM_ACTEUR reste l''interimaire (celui qui '
    'a agi), PROFIL le profil du titulaire (celui sous lequel l''etape a ete tenue).';

ALTER TABLE public.t_notification ADD COLUMN IF NOT EXISTS "ID_INTERIM" integer;
ALTER TABLE public.t_notification ADD COLUMN IF NOT EXISTS "INTERIM_DE" character varying(10);
COMMENT ON COLUMN public.t_notification."INTERIM_DE" IS
    'V34 : COPIE adressee a l''interimaire actif du titulaire nomme ici (arbitrage Q6 : copie, jamais '
    'redirection). La ligne du titulaire, elle, ne porte rien. Une copie n''est jamais recopiee '
    '(intérim non transitif).';
