-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V38 — Les documents générés depuis la fiche marché (demande front du 2026-09-23, lot 2a)
--
-- 1. t_document_fiche_marche : les documents d'une VERSION validée de la fiche (clé ID_FICHE, pas ID_DMC),
--    un par (type de document, extension). Produits dans la transaction de la validation, jamais modifiés,
--    jamais effacés : les versions précédentes restent lisibles.
-- 2. t_piece_jointe_dossier.ID_DOCUMENT_FICHE : une pièce jointe produite par la fiche (non nulle) ne se
--    supprime pas à la main.
-- 3. Le type de pièce « Dossier d'appel d'offres complet » reçoit le code stable DAO_COMPLET (le serveur le
--    retrouve sans dépendre de son identifiant ni de son libellé) — seulement s'il n'a pas déjà un code.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_document_fiche_marche (
    "ID_DOCUMENT"      integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"         integer NOT NULL,
    "TYPE"             character varying(10) NOT NULL,
    "EXTENSION"        character varying(5) NOT NULL,
    "NOM_FICHIER"      character varying(255) NOT NULL,
    "TAILLE_OCTETS"    bigint NOT NULL,
    "EMPREINTE"        character varying(64) NOT NULL,
    "DATE_GENERATION"  timestamp(6) without time zone NOT NULL,
    "CONTENU"          bytea NOT NULL,
    CONSTRAINT t_document_fiche_marche_pkey PRIMARY KEY ("ID_DOCUMENT"),
    CONSTRAINT uq_document_fiche_marche UNIQUE ("ID_FICHE", "TYPE", "EXTENSION"),
    CONSTRAINT fk_document_fiche_marche_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE"),
    CONSTRAINT ck_document_fiche_marche_type CHECK ("TYPE" IN ('DPAO', 'DPAC', 'AE', 'CCAP')),
    CONSTRAINT ck_document_fiche_marche_extension CHECK ("EXTENSION" IN ('docx', 'pdf'))
);

COMMENT ON TABLE public.t_document_fiche_marche IS
    'Documents generes a la validation d''une version de fiche marche (DPAO, CCAP, AE ; docx et pdf). Cle ID_FICHE : '
    'la version porte ses documents ; ceux des versions precedentes restent lisibles. EMPREINTE = SHA-256 du contenu.';

ALTER TABLE public.t_piece_jointe_dossier ADD COLUMN IF NOT EXISTS "ID_DOCUMENT_FICHE" integer;

ALTER TABLE public.t_piece_jointe_dossier
    ADD CONSTRAINT fk_piece_jointe_document_fiche FOREIGN KEY ("ID_DOCUMENT_FICHE")
        REFERENCES public.t_document_fiche_marche ("ID_DOCUMENT");

CREATE INDEX IF NOT EXISTS idx_piece_jointe_document_fiche
    ON public.t_piece_jointe_dossier USING btree ("ID_DOCUMENT_FICHE");

COMMENT ON COLUMN public.t_piece_jointe_dossier."ID_DOCUMENT_FICHE" IS
    'Document de fiche marche dont cette piece est la copie jointe au dossier (lot 2a) ; NULL pour une piece '
    'televersee. Une piece produite par la fiche ne se supprime pas a la main : on corrige la fiche.';

UPDATE public.t_type_piece_jointe SET "CODE" = 'DAO_COMPLET'
 WHERE "CODE" IS NULL AND "ID_TYPE_DOSSIER" = 'DMC' AND "LIBELLE_PIECE" = 'Dossier d''appel d''offres complet'
   AND NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe WHERE "CODE" = 'DAO_COMPLET');
