-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V41 — Le référentiel des travaux et réhabilitation : bloc B11 et 96 rubriques (demande front du 2026-09-24)
--
-- Structure seulement (blocs et rubriques sont figés par migration) ; les 257 champs se chargent par l'import des
-- deux fichiers de correspondance du front (referentiel-champs-fiche-dao-travaux.csv, 140 champs, quantité fixe et à
-- commande ; …-travaux-contrat-cadre.csv, 117 champs), qui portent la colonne categories = TRAVAUX.
--
-- 1. Bloc neuf B11 « Annexes et formulaires », rang 11, catégorie TRAVAUX, trois types de marché.
-- 2. 96 rubriques, catégorie TRAVAUX, reprises telles quelles du tableau du document de conversion
--    (referentiel-champs-fiche-dao-travaux.md, § « Les rubriques à semer par migration ») : code, bloc, libellé,
--    rang (61 et suivants, après les rubriques des fournitures), document maître, compte attendu, types de marché.
-- Insertion idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

INSERT INTO public.tr_bloc_fiche_marche ("CODE", "LIBELLE", "RANG", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B11', 'Annexes et formulaires', 11, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX')
ON CONFLICT ("CODE") DO NOTHING;

INSERT INTO public.tr_rubrique_fiche_marche
    ("CODE", "CODE_BLOC", "CODE_COURT", "LIBELLE", "RANG", "DOCUMENT_MAITRE", "NB_ATTENDU", "TYPES_MARCHE", "CATEGORIES") VALUES
    ('B02-CT', 'B02', 'CT', 'Contrôle technique', 61, 'DPAC', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B02-DK', 'B02', 'DK', 'Décomposition et durée de la consultation', 62, 'DPAC', 5, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B02-LT', 'B02', 'LT', 'Lots, variantes et tranches', 63, 'DPAO', 5, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B02-MC', 'B02', 'MC', 'Maîtrise d’œuvre', 64, 'DPAC', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B02-MW', 'B02', 'MW', 'Maîtrise d''ouvrage et maîtrise d''œuvre', 65, 'AE', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B02-OC', 'B02', 'OC', 'Objet et étendue du contrat-cadre', 66, 'DPAC', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B02-OT', 'B02', 'OT', 'Objet et consistance des travaux', 67, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B02-SN', 'B02', 'SN', 'Signature et engagement des parties', 68, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B02-SW', 'B02', 'SW', 'Personne responsable et délégation', 69, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B03-GM', 'B03', 'GM', 'Membres du groupement', 61, 'AE', 6, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B03-GT', 'B03', 'GT', 'Groupement', 62, 'DPAO', 5, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B03-NT', 'B03', 'NT', 'Nantissement', 63, 'AE', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B03-QT', 'B03', 'QT', 'Capacité et qualifications des candidats', 64, 'DPAO', 11, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B03-SM', 'B03', 'SM', 'Sous-traitance des marchés subséquents', 65, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B03-SU', 'B03', 'SU', 'Sous-traitance', 66, 'AE', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B03-TT', 'B03', 'TT', 'Titulaire', 67, 'AE', 5, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-CD', 'B04', 'CD', 'Composition du dossier', 61, 'DPAO', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-CT', 'B04', 'CT', 'Calendrier prévisionnel', 62, 'DPAC', 5, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-DK', 'B04', 'DK', 'Dossier de consultation', 63, 'DPAC', 4, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-DV', 'B04', 'DV', 'Délai de validité des offres', 64, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-EQ', 'B04', 'EQ', 'Demande d''éclaircissement', 65, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-FP', 'B04', 'FP', 'Remise des offres — forme des plis', 66, 'DPAO', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-LG', 'B04', 'LG', 'Langue', 67, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-OV', 'B04', 'OV', 'Ouverture des plis', 68, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-PI', 'B04', 'PI', 'Contenu de l''offre', 69, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-PT', 'B04', 'PT', 'Présentation des candidatures et des offres', 70, 'DPAC', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-RN', 'B04', 'RN', 'Renseignements complémentaires', 71, 'DPAC', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-RP', 'B04', 'RP', 'Réunion préparatoire', 72, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-RT', 'B04', 'RT', 'Conditions de remise des plis', 73, 'DPAC', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-VL', 'B04', 'VL', 'Visite des lieux', 74, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B04-VS', 'B04', 'VS', 'Visites sur site', 75, 'DPAC', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B04-VT', 'B04', 'VT', 'Délai de validité des offres', 76, 'DPAC', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B05-AG', 'B05', 'AG', 'Autres garanties', 61, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-GA', 'B05', 'GA', 'Garantie de restitution d''avance', 62, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-GE', 'B05', 'GE', 'Garantie de bonne exécution', 63, 'CCAP', 4, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-GQ', 'B05', 'GQ', 'Garantie de soumission', 64, 'DPAO', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-MC', 'B05', 'MC', 'Montant du contrat-cadre', 65, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B05-MN', 'B05', 'MN', 'Monnaie', 66, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-PT', 'B05', 'PT', 'Type de prix', 67, 'AE', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-PX', 'B05', 'PX', 'Prix des marchés subséquents', 68, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B05-RG', 'B05', 'RG', 'Retenue de garantie', 69, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B05-UT', 'B05', 'UT', 'Unité monétaire', 70, 'DPAC', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B05-VR', 'B05', 'VR', 'Variation des prix', 71, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B06-ET', 'B06', 'ET', 'Examen des candidatures et des offres', 61, 'DPAC', 4, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B06-EV', 'B06', 'EV', 'Évaluation des offres', 62, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B06-PN', 'B06', 'PN', 'Marge de préférence nationale', 63, 'DPAO', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B06-RC', 'B06', 'RC', 'Relations avec les candidats', 64, 'DPAO', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B07-AT', 'B07', 'AT', 'Modalités d''attribution des marchés subséquents', 61, 'AE', 5, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-DT', 'B07', 'DT', 'Durée et reconduction', 62, 'AE', 7, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-FT', 'B07', 'FT', 'Forme des marchés subséquents', 63, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-NC', 'B07', 'NC', 'Termes non couverts par le contrat-cadre', 64, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-OM', 'B07', 'OM', 'Objet des marchés subséquents', 65, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-PJ', 'B07', 'PJ', 'Pièces contractuelles', 66, 'AE', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-PT', 'B07', 'PT', 'Passation des marchés subséquents', 67, 'DPAC', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-PY', 'B07', 'PY', 'Pénalités de retard', 68, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B07-XE', 'B07', 'XE', 'Délais d''exécution des marchés subséquents', 69, 'AE', 4, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B08-AF', 'B08', 'AF', 'Avances', 61, 'CCAP', 5, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-AP', 'B08', 'AP', 'Acomptes sur approvisionnements', 62, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-AT', 'B08', 'AT', 'Financement et sûretés des marchés subséquents', 63, 'AE', 5, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B08-DB', 'B08', 'DB', 'Domiciliation bancaire', 64, 'AE', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-EF', 'B08', 'EF', 'Engagements financiers du maître de l’ouvrage', 65, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-FT', 'B08', 'FT', 'Facturation et paiement', 66, 'AE', 9, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B08-MO', 'B08', 'MO', 'Intérêts moratoires', 67, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-MR', 'B08', 'MR', 'Modalités de règlement des comptes', 68, 'CCAP', 4, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B08-RE', 'B08', 'RE', 'Règlement des comptes', 69, 'CCAP', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-AC', 'B09', 'AC', 'Assurances', 61, 'CCAP', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-AT', 'B09', 'AT', 'Assurance', 62, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B09-CH', 'B09', 'CH', 'Conditions de chantier et prix du marché', 63, 'CCAP', 5, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-DC', 'B09', 'DC', 'Documents contractuels', 64, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-DL', 'B09', 'DL', 'Délai d''exécution', 65, 'AE', 5, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-DT', 'B09', 'DT', 'Date d''effet', 66, 'AE', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-FM', 'B09', 'FM', 'Cas de force majeure', 67, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-GQ', 'B09', 'GQ', 'Garanties contractuelles particulières', 68, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B09-GT', 'B09', 'GT', 'Délai de garantie', 69, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-MA', 'B09', 'MA', 'Masse des travaux', 70, 'CCAP', 4, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-MD', 'B09', 'MD', 'Modification des délais d''exécution', 71, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-NE', 'B09', 'NE', 'Notifications à l''entrepreneur', 72, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-OD', 'B09', 'OD', 'Obligation de discrétion et mesures de sécurité', 73, 'CCAP', 3, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-PE', 'B09', 'PE', 'Pénalités et retenues', 74, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-PM', 'B09', 'PM', 'Matériaux fournis par le maître de l’ouvrage', 75, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-PT', 'B09', 'PT', 'Préparation des travaux', 76, 'CCAP', 4, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-PV', 'B09', 'PV', 'Contrôle des prix de revient', 77, 'CCAP', 2, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-RP', 'B09', 'RP', 'Réception provisoire', 78, 'CCAP', 4, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-VQ', 'B09', 'VQ', 'Vérification qualitative des matériaux', 79, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-VT', 'B09', 'VT', 'Vérification et admission des prestations', 80, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B09-VX', 'B09', 'VX', 'Visa des documents d''exécution', 81, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B09-XM', 'B09', 'XM', 'Modalités d’exécution administrative', 82, 'AE', 3, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B10-DR', 'B10', 'DR', 'Dérogations aux documents généraux', 61, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B10-LT', 'B10', 'LT', 'Litiges', 62, 'DPAC', 1, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B10-MC', 'B10', 'MC', 'Modifications relatives au titulaire', 63, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B10-PC', 'B10', 'PC', 'Procédure contentieuse', 64, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B10-RE', 'B10', 'RE', 'Résiliation aux torts de l’entrepreneur', 65, 'CCAP', 1, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B10-RT', 'B10', 'RT', 'Résiliations', 66, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B11-AN', 'B11', 'AN', 'Annexes de l''acte d''engagement', 61, 'AE', 6, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX'),
    ('B11-AT', 'B11', 'AT', 'Annexes du contrat-cadre', 62, 'AE', 2, 'CONTRAT_CADRE', 'TRAVAUX'),
    ('B11-FR', 'B11', 'FR', 'Formulaires à remplir', 63, 'CCAP', 6, 'QUANTITE_FIXE,A_COMMANDE', 'TRAVAUX')
ON CONFLICT ("CODE") DO NOTHING;
