-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V45 — Le besoin par lot et les formulaires du candidat (demande front du 2026-09-25,
-- demande-backend-2026-09-25-formulaires-du-candidat.md, §B1 à §B4)
--
-- 1. Bloc B12 « Besoin » (le premier code libre ; B11 et ses champs ne sont pas touchés), fournitures et services
--    seulement en V1, et sa rubrique B12-BE — sans champ : le besoin n'est pas fait de champs.
-- 2. Le besoin est une RESSOURCE rattachée à la version de fiche (comme ses valeurs : figé à la validation, copié à la
--    révision) : t_fiche_article (un article d'un lot) et t_fiche_caracteristique (une exigence d'un article).
--    REDIGE_PAR / PROFIL_REDACTEUR réservent la place du rédacteur (service bénéficiaire, à confirmer par le pilote) :
--    renseignés, jamais exigés.
-- 3. Les documents générés admettent le bordereau des prix (BP) et le tableau de conformité (TC), classeurs xlsx,
--    et la liste des fournitures et calendrier de livraison (LF).
-- 4. B04-CD « Composition du dossier » vaut aussi pour les prestations intellectuelles : les fiches A1 à A4 et les
--    garanties C1/C2 valent pour toutes les catégories.
-- 5. Paramètres administrables du contrôle du taux de garantie (référence 2 %, bornes à fixer par le pilote) et taux
--    de TVA des bordereaux (20 %) : aucune valeur n'est écrite dans le code.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

INSERT INTO public.tr_bloc_fiche_marche ("CODE", "LIBELLE", "RANG", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B12', 'Besoin', 12, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'FOURNITURES_SERVICES')
ON CONFLICT ("CODE") DO NOTHING;

INSERT INTO public.tr_rubrique_fiche_marche
    ("CODE", "CODE_BLOC", "CODE_COURT", "LIBELLE", "RANG", "DOCUMENT_MAITRE", "NB_ATTENDU", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B12-BE', 'B12', 'BE', 'Articles et caractéristiques exigées, par lot', 1, 'DPAO', 0,
        'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'FOURNITURES_SERVICES')
ON CONFLICT ("CODE") DO NOTHING;

CREATE TABLE IF NOT EXISTS public.t_fiche_article (
    "ID_ARTICLE"        integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"          integer NOT NULL,
    "LOT"               integer,
    "ORDRE"             integer NOT NULL,
    "DESIGNATION"       character varying(500) NOT NULL,
    "UNITE"             character varying(20) NOT NULL,
    "QUANTITE_MIN"      integer,
    "QUANTITE_MAX"      integer,
    "QUANTITE"          integer,
    "REDIGE_PAR"        character varying(50),
    "PROFIL_REDACTEUR"  character varying(30),
    CONSTRAINT t_fiche_article_pkey PRIMARY KEY ("ID_ARTICLE"),
    CONSTRAINT fk_fiche_article_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE") ON DELETE CASCADE,
    CONSTRAINT ck_fiche_article_lot CHECK ("LOT" IS NULL OR "LOT" >= 1),
    CONSTRAINT ck_fiche_article_quantites CHECK (("QUANTITE_MIN" IS NULL OR "QUANTITE_MIN" >= 0)
        AND ("QUANTITE_MAX" IS NULL OR "QUANTITE_MAX" >= 0) AND ("QUANTITE" IS NULL OR "QUANTITE" >= 0))
);
CREATE INDEX IF NOT EXISTS idx_fiche_article_fiche ON public.t_fiche_article ("ID_FICHE", "LOT", "ORDRE");

CREATE TABLE IF NOT EXISTS public.t_fiche_caracteristique (
    "ID_CARACTERISTIQUE" integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_ARTICLE"         integer NOT NULL,
    "ORDRE"              integer NOT NULL,
    "LIBELLE"            character varying(300) NOT NULL,
    "EXIGENCE"           character varying(500) NOT NULL,
    CONSTRAINT t_fiche_caracteristique_pkey PRIMARY KEY ("ID_CARACTERISTIQUE"),
    CONSTRAINT fk_fiche_caracteristique_article FOREIGN KEY ("ID_ARTICLE")
        REFERENCES public.t_fiche_article ("ID_ARTICLE") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_fiche_caracteristique_article ON public.t_fiche_caracteristique ("ID_ARTICLE", "ORDRE");

ALTER TABLE public.t_document_fiche_marche DROP CONSTRAINT IF EXISTS ck_document_fiche_marche_type;
ALTER TABLE public.t_document_fiche_marche ADD CONSTRAINT ck_document_fiche_marche_type
    CHECK ("TYPE" IN ('DPAO', 'DPAC', 'DPIC', 'AE', 'CCAP', 'LF', 'BP', 'TC'));
ALTER TABLE public.t_document_fiche_marche DROP CONSTRAINT IF EXISTS ck_document_fiche_marche_extension;
ALTER TABLE public.t_document_fiche_marche ADD CONSTRAINT ck_document_fiche_marche_extension
    CHECK ("EXTENSION" IN ('docx', 'pdf', 'xlsx'));

-- 6. Un champ peut porter plusieurs options (B04-CD-01 : les fiches A1 à A4 jointes).
ALTER TABLE public.tr_champ_fiche_marche DROP CONSTRAINT IF EXISTS ck_champ_fiche_marche_type;
ALTER TABLE public.tr_champ_fiche_marche ADD CONSTRAINT ck_champ_fiche_marche_type CHECK ("TYPE" IN (
    'TEXTE', 'TEXTE_LONG', 'NOMBRE', 'MONTANT', 'POURCENTAGE', 'DATE', 'LISTE', 'LISTE_MULTIPLE', 'OUI_NON', 'PIECE'));

UPDATE public.tr_rubrique_fiche_marche SET "CATEGORIES" = "CATEGORIES" || ',PRESTATIONS_INTELLECTUELLES'
 WHERE "CODE" = 'B04-CD' AND ',' || "CATEGORIES" || ',' NOT LIKE '%,PRESTATIONS_INTELLECTUELLES,%';

INSERT INTO public.t_parametre ("CLE", "VALEUR", "DATE_MAJ") VALUES
    ('FICHE_GARANTIE_TAUX_REFERENCE', '2', now()),
    ('FICHE_TAUX_TVA', '20', now())
ON CONFLICT ("CLE") DO NOTHING;

COMMENT ON TABLE public.t_fiche_article IS
    'Besoin d''une version de fiche DAO (fournitures) : un article d''un lot (rang au plan, NULL si non alloti).';
COMMENT ON TABLE public.t_fiche_caracteristique IS 'Caracteristique technique exigee d''un article du besoin.';
