-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V50 — Préparer la fiche DAO à la remise électronique des offres (demande front du 2026-09-27,
-- demande-backend-2026-09-27-remise-electronique.md ; cahier des charges du pilote du 27/09, « selon les
-- recommandations » ; ADR-0010).
--
-- Périmètre : la fiche seulement — champs, règles, impression —, un écran séparé de paramètres internes, un rôle
-- « Responsable de la procédure » par procédure. Papier ou électronique, pas de mode mixte.
--
-- 1. §B1.2 — deux types de champ : DATE_HEURE (ISO local AAAA-MM-JJTHH:MM) et URL (texte <= 500, http/https).
-- 2. §B1.1 — la rubrique B04-SE « Remise électronique » (bloc B04, après B04-CD, trois formes, trois catégories) ;
--    B04-VE-01 / B04-VE-02 désactivés (jamais de DELETE) : B04-SE-01 les remplace (Q1). Les champs eux-mêmes se
--    chargent par le fichier de correspondance (docs/referentiel/2026-09-27-remise-electronique.sql pour une base
--    déjà chargée).
-- 3. §B1.4 — les paramètres administrables de la remise électronique (patron fiche-taux-tva) ; t_parametre.VALEUR
--    passe à 1000 caractères (adresse de la plateforme, texte d'assistance).
-- 4. §B1.4 / §B5.1 — t_fiche_marche_valeur.CALCULEE : la valeur a été posée par le serveur à l'enregistrement du
--    bloc (champsCalcules, affichée « calculée » en lecture seule par le front).
-- 5. §B4 — t_parametre_interne_procedure (INT-SE-01 membres, INT-SE-02 = leur nombre, INT-SE-03 quorum, INT-SE-04
--    cérémonie des clés ; INT-SE-05 = le responsable) : hors référentiel, hors moteur de rendu, servis au seul
--    titulaire du rôle ; journal dédié t_parametre_interne_journal avec ancienne / nouvelle valeur (Q7 : le journal
--    global t_audit_log ne reçoit que la route, sans valeurs).
-- 6. §B5 — t_responsable_procedure : le rôle nominatif par procédure, UN SEUL actif par DMC (index partiel).
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- 1. Types de champ
ALTER TABLE public.tr_champ_fiche_marche DROP CONSTRAINT IF EXISTS ck_champ_fiche_marche_type;
ALTER TABLE public.tr_champ_fiche_marche ADD CONSTRAINT ck_champ_fiche_marche_type CHECK ("TYPE" IN (
    'TEXTE', 'TEXTE_LONG', 'NOMBRE', 'MONTANT', 'POURCENTAGE', 'DATE', 'DATE_HEURE', 'URL', 'LISTE', 'LISTE_MULTIPLE',
    'OUI_NON', 'PIECE'));

-- 2. Rubrique B04-SE (rang 61 comme B04-CD ; l'ordre de lecture est (bloc, rang, code) : B04-CD puis B04-SE)
INSERT INTO public.tr_rubrique_fiche_marche
    ("CODE", "CODE_BLOC", "CODE_COURT", "LIBELLE", "RANG", "DOCUMENT_MAITRE", "NB_ATTENDU", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B04-SE', 'B04', 'SE', 'Remise électronique', 61, 'DPAO', 17,
        'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'FOURNITURES_SERVICES,TRAVAUX,PRESTATIONS_INTELLECTUELLES')
ON CONFLICT ("CODE") DO NOTHING;

UPDATE public.tr_champ_fiche_marche SET "ACTIF" = false WHERE "CODE" IN ('B04-VE-01', 'B04-VE-02');

-- 3. Paramètres administrables
ALTER TABLE public.t_parametre ALTER COLUMN "VALEUR" TYPE character varying(1000);

INSERT INTO public.t_parametre ("CLE", "VALEUR", "DATE_MAJ") VALUES
    ('FICHE_SE_FUSEAU', 'Indian/Antananarivo', now()),
    ('FICHE_SE_SIGNATURE_MIN', 'Avancée', now()),
    ('FICHE_SE_TAILLE_MAX_PLATEFORME_MO', '500', now()),
    ('FICHE_SE_DELAI_MIN_REMISE_JOURS', '30', now()),
    ('FICHE_SE_QUORUM_DEFAUT', '3/5', now())
ON CONFLICT ("CLE") DO NOTHING;

-- 4. Valeur calculée par le serveur
ALTER TABLE public.t_fiche_marche_valeur ADD COLUMN IF NOT EXISTS "CALCULEE" boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN public.t_fiche_marche_valeur."CALCULEE" IS
    'Valeur posée par le serveur a l''enregistrement du bloc (remise electronique, V50) : lecture seule pour le front';

-- 5. Paramètres internes de la procédure et leur journal
CREATE TABLE IF NOT EXISTS public.t_parametre_interne_procedure (
    "ID_DMC"         bigint NOT NULL,
    "MEMBRES_CLE"    character varying(1000),
    "QUORUM"         integer,
    "DATE_CEREMONIE" timestamp without time zone,
    "DATE_MAJ"       timestamp without time zone NOT NULL,
    "IM_MAJ"         character varying(10),
    CONSTRAINT t_parametre_interne_procedure_pkey PRIMARY KEY ("ID_DMC"),
    CONSTRAINT fk_parametre_interne_procedure_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC")
);
COMMENT ON TABLE public.t_parametre_interne_procedure IS
    'Parametres internes d''une procedure en remise electronique (membres detenteurs de parts de cle, quorum, ceremonie) — V50, reserves au responsable de la procedure';

CREATE TABLE IF NOT EXISTS public.t_parametre_interne_journal (
    "ID"              bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"          bigint NOT NULL,
    "DATE"            timestamp without time zone NOT NULL,
    "IM_ACTEUR"       character varying(10),
    "NOM_ACTEUR"      character varying(200),
    "CHAMP"           character varying(50) NOT NULL,
    "ANCIENNE_VALEUR" text,
    "NOUVELLE_VALEUR" text,
    CONSTRAINT t_parametre_interne_journal_pkey PRIMARY KEY ("ID"),
    CONSTRAINT fk_parametre_interne_journal_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC")
);
CREATE INDEX IF NOT EXISTS idx_parametre_interne_journal_dmc ON public.t_parametre_interne_journal ("ID_DMC", "DATE");
COMMENT ON TABLE public.t_parametre_interne_journal IS
    'Journal des parametres internes (qui, quand, quel champ, ancienne et nouvelle valeur) — V50, servi au seul responsable ; t_audit_log ne recoit que la route';

-- 6. Responsable de la procédure
CREATE TABLE IF NOT EXISTS public.t_responsable_procedure (
    "ID"               bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"           bigint NOT NULL,
    "IM_RESPONSABLE"   character varying(10) NOT NULL,
    "NOM_RESPONSABLE"  character varying(200),
    "DESIGNE_PAR"      character varying(10),
    "DATE_DESIGNATION" timestamp without time zone NOT NULL,
    "RETIRE_PAR"       character varying(10),
    "DATE_RETRAIT"     timestamp without time zone,
    CONSTRAINT t_responsable_procedure_pkey PRIMARY KEY ("ID"),
    CONSTRAINT fk_responsable_procedure_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC")
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_responsable_procedure_actif
    ON public.t_responsable_procedure ("ID_DMC") WHERE "DATE_RETRAIT" IS NULL;
COMMENT ON TABLE public.t_responsable_procedure IS
    'Role nominatif « Responsable de la procedure » par DMC (ADR-0010) : un seul actif par DMC, designe et retire par l''Administrateur — V50';
