-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V60 — Le matériel et le personnel exigés d'une fiche DAO de travaux, en listes (demande front du 2026-10-03,
-- demande-backend-2026-10-03-materiel-personnel-travaux.md, lot 3 du plan « fiche travaux structurée »).
--
-- 1. Deux ressources de la VERSION de fiche (comme le besoin, V45 : figées à la validation, copiées à la révision,
--    supprimées avec la fiche) : t_fiche_materiel (un engin exigé) et t_fiche_personnel (un poste clé exigé). Une seule
--    liste par fiche : le drapeau PAR_LOT dit qu'une ligne vaut pour chaque lot.
-- 2. Bloc B13 « Matériel et personnel exigés », rendu MOYENS (l'écran y montre les deux listes), servi aux travaux dans
--    les trois types de marché, avec deux rubriques sans champ : B13-MA (matériel) et B13-PE (personnel).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_fiche_materiel (
    "ID_MATERIEL"       integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"          integer NOT NULL,
    "ORDRE"             integer NOT NULL,
    "DESIGNATION"       character varying(200) NOT NULL,
    "CARACTERISTIQUE"   character varying(200),
    "NOMBRE"            integer NOT NULL,
    "MINIMUM_EN_PROPRE" integer,
    "PAR_LOT"           boolean NOT NULL DEFAULT false,
    CONSTRAINT t_fiche_materiel_pkey PRIMARY KEY ("ID_MATERIEL"),
    CONSTRAINT fk_fiche_materiel_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE") ON DELETE CASCADE,
    CONSTRAINT ck_fiche_materiel_nombre CHECK ("NOMBRE" >= 1),
    CONSTRAINT ck_fiche_materiel_minimum CHECK ("MINIMUM_EN_PROPRE" IS NULL
        OR ("MINIMUM_EN_PROPRE" >= 0 AND "MINIMUM_EN_PROPRE" <= "NOMBRE"))
);
CREATE INDEX IF NOT EXISTS idx_fiche_materiel_fiche ON public.t_fiche_materiel ("ID_FICHE", "ORDRE");

CREATE TABLE IF NOT EXISTS public.t_fiche_personnel (
    "ID_PERSONNEL"        integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"            integer NOT NULL,
    "ORDRE"               integer NOT NULL,
    "POSTE"               character varying(200) NOT NULL,
    "NOMBRE"              integer NOT NULL DEFAULT 1,
    "DIPLOME"             character varying(500),
    "EXPERIENCE_ANNEES"   integer,
    "DOMAINE_EXPERIENCE"  character varying(200),
    "JUSTIFICATIFS"       character varying(500),
    "PAR_LOT"             boolean NOT NULL DEFAULT false,
    CONSTRAINT t_fiche_personnel_pkey PRIMARY KEY ("ID_PERSONNEL"),
    CONSTRAINT fk_fiche_personnel_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE") ON DELETE CASCADE,
    CONSTRAINT ck_fiche_personnel_nombre CHECK ("NOMBRE" >= 1),
    CONSTRAINT ck_fiche_personnel_experience CHECK ("EXPERIENCE_ANNEES" IS NULL OR "EXPERIENCE_ANNEES" >= 0)
);
CREATE INDEX IF NOT EXISTS idx_fiche_personnel_fiche ON public.t_fiche_personnel ("ID_FICHE", "ORDRE");

COMMENT ON TABLE public.t_fiche_materiel IS
    'Materiel exige d''une version de fiche DAO de travaux (clause 6.3 du DPAO-T) ; PAR_LOT : le nombre vaut pour chaque lot.';
COMMENT ON TABLE public.t_fiche_personnel IS
    'Personnel cle exige d''une version de fiche DAO de travaux (clause 6.3 du DPAO-T) ; PAR_LOT : pour chaque lot.';

ALTER TABLE public.tr_bloc_fiche_marche DROP CONSTRAINT IF EXISTS ck_bloc_fiche_marche_rendu;
ALTER TABLE public.tr_bloc_fiche_marche ADD CONSTRAINT ck_bloc_fiche_marche_rendu
    CHECK ("RENDU" IS NULL OR "RENDU" IN ('BESOIN', 'MOYENS'));

INSERT INTO public.tr_bloc_fiche_marche ("CODE", "LIBELLE", "RANG", "TYPES_MARCHE", "CATEGORIES", "RENDU")
VALUES ('B13', 'Matériel et personnel exigés', 13, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX', 'MOYENS')
ON CONFLICT ("CODE") DO NOTHING;

INSERT INTO public.tr_rubrique_fiche_marche
    ("CODE", "CODE_BLOC", "CODE_COURT", "LIBELLE", "RANG", "DOCUMENT_MAITRE", "NB_ATTENDU", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B13-MA', 'B13', 'MA', 'Matériel exigé', 1, 'DPAO', 0, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX'),
       ('B13-PE', 'B13', 'PE', 'Personnel clé exigé', 2, 'DPAO', 0, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX')
ON CONFLICT ("CODE") DO NOTHING;
