-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V61 — Les pièces de l'offre d'une fiche DAO de travaux, typées (demande front du 2026-10-03,
-- demande-backend-2026-10-03-pieces-offre-travaux.md, lot 4 du plan « fiche travaux structurée »).
--
-- 1. Une ressource de la VERSION de fiche (comme le besoin et les moyens : figée à la validation, copiée à la révision,
--    supprimée avec la fiche) : t_fiche_piece, une pièce exigée, de la rubrique ADMINISTRATIVE (2° de la clause 6.2 du
--    DPAO-T) ou OFFRE (1°). Une seule liste par fiche ; PAR_LOT : une pièce par lot.
-- 2. Bloc B14 « Pièces de l'offre », rendu PIECES, servi aux travaux dans les trois types de marché, avec deux rubriques
--    sans champ : B14-AD (pièces administratives) et B14-OF (autres pièces de l'offre).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_fiche_piece (
    "ID_PIECE"            integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"            integer NOT NULL,
    "ORDRE"               integer NOT NULL,
    "RUBRIQUE"            character varying(20) NOT NULL,
    "NUMERO"              character varying(10),
    "LIBELLE"             character varying(300) NOT NULL,
    "FORME"               character varying(200),
    "ANCIENNETE_MAX_MOIS" integer,
    "PAR_LOT"             boolean NOT NULL DEFAULT false,
    "MODELE"              character varying(200),
    CONSTRAINT t_fiche_piece_pkey PRIMARY KEY ("ID_PIECE"),
    CONSTRAINT fk_fiche_piece_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE") ON DELETE CASCADE,
    CONSTRAINT ck_fiche_piece_rubrique CHECK ("RUBRIQUE" IN ('ADMINISTRATIVE', 'OFFRE')),
    CONSTRAINT ck_fiche_piece_anciennete CHECK ("ANCIENNETE_MAX_MOIS" IS NULL OR "ANCIENNETE_MAX_MOIS" >= 1)
);
CREATE INDEX IF NOT EXISTS idx_fiche_piece_fiche ON public.t_fiche_piece ("ID_FICHE", "ORDRE");

COMMENT ON TABLE public.t_fiche_piece IS
    'Piece exigee d''une version de fiche DAO de travaux (clause 6.2 du DPAO-T) : ADMINISTRATIVE (2°) ou OFFRE (1°).';

ALTER TABLE public.tr_bloc_fiche_marche DROP CONSTRAINT IF EXISTS ck_bloc_fiche_marche_rendu;
ALTER TABLE public.tr_bloc_fiche_marche ADD CONSTRAINT ck_bloc_fiche_marche_rendu
    CHECK ("RENDU" IS NULL OR "RENDU" IN ('BESOIN', 'MOYENS', 'PIECES'));

INSERT INTO public.tr_bloc_fiche_marche ("CODE", "LIBELLE", "RANG", "TYPES_MARCHE", "CATEGORIES", "RENDU")
VALUES ('B14', 'Pièces de l''offre', 14, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX', 'PIECES')
ON CONFLICT ("CODE") DO NOTHING;

INSERT INTO public.tr_rubrique_fiche_marche
    ("CODE", "CODE_BLOC", "CODE_COURT", "LIBELLE", "RANG", "DOCUMENT_MAITRE", "NB_ATTENDU", "TYPES_MARCHE", "CATEGORIES")
VALUES ('B14-AD', 'B14', 'AD', 'Pièces administratives', 1, 'DPAO', 0, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX'),
       ('B14-OF', 'B14', 'OF', 'Autres pièces de l''offre', 2, 'DPAO', 0, 'QUANTITE_FIXE,A_COMMANDE,CONTRAT_CADRE', 'TRAVAUX')
ON CONFLICT ("CODE") DO NOTHING;
