-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V63 — Les comptes candidats (demande front du 2026-10-04, soumission en ligne, lot 1a : §B2 et §B7).
--
-- 1. t_compte_candidat : la fiche d'un candidat (entreprise externe inscrite par elle-même). Son identifiant court
--    (C + 9 chiffres, 10 caractères) est la REF_ACTEUR de son compte de connexion t_compte_auth, dont le LOGIN est
--    l'adresse électronique (en minuscules) et le TYPE_ACTEUR « CANDIDAT ». ETAT : A_CONFIRMER (inscrit, codes non
--    saisis), CONFIRME, ARCHIVE (inactif ; se réactive par un nouveau code).
-- 2. t_code_candidat : les codes de confirmation (six chiffres, à usage unique, 15 minutes, 5 essais), stockés hachés
--    (BCrypt), par canal (EMAIL, TELEPHONE).
-- 3. Les paramètres administrables des candidats (t_parametre).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE SEQUENCE IF NOT EXISTS public.seq_compte_candidat START 1;

CREATE TABLE IF NOT EXISTS public.t_compte_candidat (
    "ID_CANDIDAT"          character varying(10) NOT NULL,
    "EMAIL"                character varying(100) NOT NULL,
    "TELEPHONE"            character varying(30) NOT NULL,
    "NOM"                  character varying(100) NOT NULL,
    "PRENOM"               character varying(100) NOT NULL,
    "ETAT"                 character varying(20) NOT NULL,
    "TELEPHONE_CONFIRME"   boolean NOT NULL DEFAULT false,
    "DATE_INSCRIPTION"     timestamp without time zone NOT NULL,
    "DATE_CONFIRMATION"    timestamp without time zone,
    "DERNIERE_CONNEXION"   timestamp without time zone,
    "DATE_ARCHIVAGE"       timestamp without time zone,
    CONSTRAINT t_compte_candidat_pkey PRIMARY KEY ("ID_CANDIDAT"),
    CONSTRAINT uq_compte_candidat_email UNIQUE ("EMAIL"),
    CONSTRAINT ck_compte_candidat_etat CHECK ("ETAT" IN ('A_CONFIRMER', 'CONFIRME', 'ARCHIVE'))
);
CREATE INDEX IF NOT EXISTS idx_compte_candidat_telephone ON public.t_compte_candidat ("TELEPHONE");

CREATE TABLE IF NOT EXISTS public.t_code_candidat (
    "ID_CODE"        integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_CANDIDAT"    character varying(10) NOT NULL,
    "CANAL"          character varying(10) NOT NULL,
    "HASH_CODE"      character varying(100) NOT NULL,
    "DATE_EMISSION"  timestamp without time zone NOT NULL,
    "EXPIRATION"     timestamp without time zone NOT NULL,
    "ESSAIS"         integer NOT NULL DEFAULT 0,
    "UTILISE"        boolean NOT NULL DEFAULT false,
    CONSTRAINT t_code_candidat_pkey PRIMARY KEY ("ID_CODE"),
    CONSTRAINT fk_code_candidat_compte FOREIGN KEY ("ID_CANDIDAT") REFERENCES public.t_compte_candidat ("ID_CANDIDAT")
        ON DELETE CASCADE,
    CONSTRAINT ck_code_candidat_canal CHECK ("CANAL" IN ('EMAIL', 'TELEPHONE'))
);
CREATE INDEX IF NOT EXISTS idx_code_candidat_compte ON public.t_code_candidat ("ID_CANDIDAT", "CANAL");

COMMENT ON TABLE public.t_compte_candidat IS
    'Compte candidat (soumission en ligne) : son ID est la REF_ACTEUR du compte de connexion (LOGIN = adresse electronique).';
COMMENT ON TABLE public.t_code_candidat IS
    'Code de confirmation d''un compte candidat (6 chiffres, 15 min, 5 essais), stocke hache (BCrypt).';

INSERT INTO public.t_parametre ("CLE", "VALEUR", "DATE_MAJ") VALUES
    ('CANDIDAT_VERIFICATION_NIF', 'SUR_PIECES', now()),
    ('CANDIDAT_CONFIRMATION_TELEPHONE', 'NON', now()),
    ('CANDIDAT_INSCRIPTIONS_PAR_JOUR', '5', now()),
    ('CANDIDAT_DELAI_CONFIRMATION_JOURS', '7', now()),
    ('CANDIDAT_DELAI_INACTIVITE_MOIS', '24', now()),
    ('CANDIDAT_TAILLE_MAX_PIECE_MO', '10', now())
ON CONFLICT ("CLE") DO NOTHING;
