-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V64 — L'entreprise d'un candidat, la vérification de son NIF, le répertoire des exclusions de l'ARMP et les
-- rapprochements entre comptes (demande front du 2026-10-04, soumission en ligne, lot 1b : §B3 à §B6).
--
-- 1. t_entreprise : un compte candidat = une entreprise. NIF, STAT et RCS, stockés normalisés (sans blancs, en
--    majuscules), sont chacun UNIQUES sur la plateforme. L'adresse normalisée (casse, blancs, accents) sert aux
--    rapprochements. La vérification du NIF (statut, source, date, acteur, motif) est portée par la ligne.
-- 2. t_piece_entreprise : les pièces de l'entreprise (carte fiscale, statuts, pouvoir, autre), contenu en base.
-- 3. t_entreprise_journal : les changements de statut de vérification, avec leurs valeurs.
-- 4. t_exclusion_armp (+ journal) : le répertoire des entreprises exclues par l'ARMP, tenu par l'Administrateur. Une
--    exclusion ne se supprime jamais : on la corrige, ou on avance sa date de fin.
-- 5. t_rapprochement_candidat : les rapprochements calculés entre deux comptes (même téléphone, même signataire, même
--    adresse) ; remis à la commission au lot 4, jamais un refus.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_entreprise (
    "ID_ENTREPRISE"        integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_CANDIDAT"          character varying(10) NOT NULL,
    "RAISON_SOCIALE"       character varying(200) NOT NULL,
    "NIF"                  character varying(30) NOT NULL,
    "STAT"                 character varying(30),
    "RCS"                  character varying(50),
    "ADRESSE"              character varying(300) NOT NULL,
    "ADRESSE_NORMALISEE"   character varying(300) NOT NULL,
    "REP_NOM"              character varying(100) NOT NULL,
    "REP_PRENOM"           character varying(100) NOT NULL,
    "REP_FONCTION"         character varying(100),
    "VERIF_STATUT"         character varying(30) NOT NULL DEFAULT 'NON_VERIFIE',
    "VERIF_SOURCE"         character varying(20),
    "VERIF_DATE"           timestamp without time zone,
    "VERIF_ACTEUR"         character varying(100),
    "VERIF_MOTIF"          character varying(500),
    "DATE_CREATION"        timestamp without time zone NOT NULL,
    "DATE_MAJ"             timestamp without time zone NOT NULL,
    CONSTRAINT t_entreprise_pkey PRIMARY KEY ("ID_ENTREPRISE"),
    CONSTRAINT uq_entreprise_candidat UNIQUE ("ID_CANDIDAT"),
    CONSTRAINT uq_entreprise_nif UNIQUE ("NIF"),
    CONSTRAINT uq_entreprise_stat UNIQUE ("STAT"),
    CONSTRAINT uq_entreprise_rcs UNIQUE ("RCS"),
    CONSTRAINT fk_entreprise_candidat FOREIGN KEY ("ID_CANDIDAT") REFERENCES public.t_compte_candidat ("ID_CANDIDAT")
        ON DELETE CASCADE,
    CONSTRAINT ck_entreprise_verif CHECK ("VERIF_STATUT" IN ('VERIFIE_DGI', 'VERIFIE_SUR_PIECES', 'INCONNU_DGI',
        'REFUSE_SUR_PIECES', 'NON_VERIFIE'))
);
CREATE INDEX IF NOT EXISTS idx_entreprise_verif ON public.t_entreprise ("VERIF_STATUT", "DATE_CREATION");

CREATE TABLE IF NOT EXISTS public.t_piece_entreprise (
    "ID_PIECE"       integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_ENTREPRISE"  integer NOT NULL,
    "TYPE"           character varying(20) NOT NULL,
    "NOM_FICHIER"    character varying(255),
    "FORMAT"         character varying(50) NOT NULL,
    "TAILLE"         bigint NOT NULL,
    "HASH_SHA256"    character varying(64) NOT NULL,
    "CONTENU"        bytea NOT NULL,
    "DATE_DEPOT"     timestamp without time zone NOT NULL,
    CONSTRAINT t_piece_entreprise_pkey PRIMARY KEY ("ID_PIECE"),
    CONSTRAINT fk_piece_entreprise FOREIGN KEY ("ID_ENTREPRISE") REFERENCES public.t_entreprise ("ID_ENTREPRISE")
        ON DELETE CASCADE,
    CONSTRAINT ck_piece_entreprise_type CHECK ("TYPE" IN ('CARTE_FISCALE', 'STATUTS', 'POUVOIR', 'AUTRE'))
);
CREATE INDEX IF NOT EXISTS idx_piece_entreprise ON public.t_piece_entreprise ("ID_ENTREPRISE");

CREATE TABLE IF NOT EXISTS public.t_entreprise_journal (
    "ID_JOURNAL"     integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_ENTREPRISE"  integer NOT NULL,
    "DATE_ACTION"    timestamp without time zone NOT NULL,
    "ACTEUR"         character varying(100),
    "CHAMP"          character varying(50) NOT NULL,
    "ANCIENNE"       character varying(500),
    "NOUVELLE"       character varying(500),
    CONSTRAINT t_entreprise_journal_pkey PRIMARY KEY ("ID_JOURNAL"),
    CONSTRAINT fk_entreprise_journal FOREIGN KEY ("ID_ENTREPRISE") REFERENCES public.t_entreprise ("ID_ENTREPRISE")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.t_exclusion_armp (
    "ID_EXCLUSION"         integer GENERATED BY DEFAULT AS IDENTITY,
    "NIF"                  character varying(30) NOT NULL,
    "RAISON_SOCIALE"       character varying(200) NOT NULL,
    "MOTIF"                character varying(500) NOT NULL,
    "REFERENCE_DECISION"   character varying(100) NOT NULL,
    "DATE_DEBUT"           date NOT NULL,
    "DATE_FIN"             date,
    "DATE_CREATION"        timestamp without time zone NOT NULL,
    CONSTRAINT t_exclusion_armp_pkey PRIMARY KEY ("ID_EXCLUSION"),
    CONSTRAINT ck_exclusion_dates CHECK ("DATE_FIN" IS NULL OR "DATE_FIN" >= "DATE_DEBUT")
);
CREATE INDEX IF NOT EXISTS idx_exclusion_armp_nif ON public.t_exclusion_armp ("NIF");

CREATE TABLE IF NOT EXISTS public.t_exclusion_armp_journal (
    "ID_JOURNAL"     integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_EXCLUSION"   integer NOT NULL,
    "DATE_ACTION"    timestamp without time zone NOT NULL,
    "ACTEUR"         character varying(100),
    "ANCIENNES"      character varying(2000),
    "NOUVELLES"      character varying(2000) NOT NULL,
    CONSTRAINT t_exclusion_armp_journal_pkey PRIMARY KEY ("ID_JOURNAL"),
    CONSTRAINT fk_exclusion_journal FOREIGN KEY ("ID_EXCLUSION") REFERENCES public.t_exclusion_armp ("ID_EXCLUSION")
);

CREATE TABLE IF NOT EXISTS public.t_rapprochement_candidat (
    "ID_RAPPROCHEMENT"   integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_CANDIDAT_A"      character varying(10) NOT NULL,
    "ID_CANDIDAT_B"      character varying(10) NOT NULL,
    "CRITERE"            character varying(20) NOT NULL,
    "VALEUR"             character varying(300) NOT NULL,
    "DATE_CALCUL"        timestamp without time zone NOT NULL,
    CONSTRAINT t_rapprochement_candidat_pkey PRIMARY KEY ("ID_RAPPROCHEMENT"),
    CONSTRAINT uq_rapprochement UNIQUE ("ID_CANDIDAT_A", "ID_CANDIDAT_B", "CRITERE"),
    CONSTRAINT ck_rapprochement_ordre CHECK ("ID_CANDIDAT_A" < "ID_CANDIDAT_B"),
    CONSTRAINT ck_rapprochement_critere CHECK ("CRITERE" IN ('TELEPHONE', 'EMAIL', 'SIGNATAIRE', 'ADRESSE')),
    CONSTRAINT fk_rapprochement_a FOREIGN KEY ("ID_CANDIDAT_A") REFERENCES public.t_compte_candidat ("ID_CANDIDAT")
        ON DELETE CASCADE,
    CONSTRAINT fk_rapprochement_b FOREIGN KEY ("ID_CANDIDAT_B") REFERENCES public.t_compte_candidat ("ID_CANDIDAT")
        ON DELETE CASCADE
);

COMMENT ON TABLE public.t_entreprise IS 'Entreprise d''un compte candidat (un compte = une entreprise) ; NIF, STAT, RCS uniques.';
COMMENT ON TABLE public.t_exclusion_armp IS 'Repertoire des entreprises exclues par l''ARMP ; jamais supprime (correction ou date de fin).';
COMMENT ON TABLE public.t_rapprochement_candidat IS 'Rapprochements entre comptes candidats (alerte de collusion, jamais un refus).';
