-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V65 — Le registre des retraits du DAO en ligne (demande front du 2026-10-04, soumission en ligne, lot 1c, §B8).
--
-- Chaque document du DAO téléchargé par un candidat est journalisé : compte, entreprise (si déclarée), document,
-- version de la fiche, date. La PRMP de la fiche consulte ce registre. Le retrait est libre après inscription.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_retrait_dao (
    "ID_RETRAIT"      integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"          bigint NOT NULL,
    "ID_CANDIDAT"     character varying(10) NOT NULL,
    "ID_ENTREPRISE"   integer,
    "CODE_DOCUMENT"   character varying(255) NOT NULL,
    "VERSION_FICHE"   integer NOT NULL,
    "DATE_RETRAIT"    timestamp without time zone NOT NULL,
    CONSTRAINT t_retrait_dao_pkey PRIMARY KEY ("ID_RETRAIT"),
    CONSTRAINT fk_retrait_dao_candidat FOREIGN KEY ("ID_CANDIDAT") REFERENCES public.t_compte_candidat ("ID_CANDIDAT")
);
CREATE INDEX IF NOT EXISTS idx_retrait_dao_dmc ON public.t_retrait_dao ("ID_DMC", "DATE_RETRAIT");

COMMENT ON TABLE public.t_retrait_dao IS
    'Registre des retraits du DAO en ligne : un document telecharge par un candidat (compte, entreprise, version, date).';
