-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V66 — La cérémonie des clés et la procédure de secours S1 à S4 (demande front du 2026-10-04, soumission en ligne,
-- lot 2 ; ADR-0013 §1, §3, §5, §6).
--
-- 1. Le dépositaire de la part de secours (§B1), porté par les paramètres internes : une désignation nominative,
--    pas un compte.
-- 2. La cérémonie d'une procédure (§B2) : son état, sa date de clôture effective, le premier dépôt (posé par le lot 3).
-- 3. Les clés des détenteurs (§B2.2, §B2.3) : clé publique SPKI et empreinte (publiques), clé privée ENVELOPPÉE par la
--    phrase secrète du détenteur — le serveur en garde la copie, il ne peut pas la lire. Une clé remplacée après le
--    premier dépôt est ARCHIVÉE (DATE_ARCHIVAGE), jamais supprimée : des offres en dépendent (S4).
-- 4. Les défis de vérification d'une part (§B4, S2) : le serveur ne garde que le SHA-256 du clair attendu, 5 minutes,
--    à usage unique.
-- 5. Le délai du rappel de vérification (§B4), paramètre administrable.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- 1. Dépositaire de la part de secours
ALTER TABLE public.t_parametre_interne_procedure ADD COLUMN IF NOT EXISTS "DEPOSITAIRE_NOM"       character varying(200);
ALTER TABLE public.t_parametre_interne_procedure ADD COLUMN IF NOT EXISTS "DEPOSITAIRE_ORGANISME" character varying(200);
ALTER TABLE public.t_parametre_interne_procedure ADD COLUMN IF NOT EXISTS "DEPOSITAIRE_FONCTION"  character varying(200);
ALTER TABLE public.t_parametre_interne_procedure ADD COLUMN IF NOT EXISTS "DEPOSITAIRE_CONTACT"   character varying(300);
COMMENT ON COLUMN public.t_parametre_interne_procedure."DEPOSITAIRE_NOM" IS
    'Depositaire de la part de secours (ADR-0013 S3) : designation nominative par le responsable de la procedure, pas un compte — V66';

-- 2. La cérémonie
CREATE TABLE IF NOT EXISTS public.t_ceremonie_cles (
    "ID_DMC"         bigint NOT NULL,
    "ETAT"           character varying(20) NOT NULL,
    "DATE_CLOTURE"   timestamp without time zone,
    "PREMIER_DEPOT"  boolean NOT NULL DEFAULT false,
    "DATE_MAJ"       timestamp without time zone NOT NULL,
    CONSTRAINT t_ceremonie_cles_pkey PRIMARY KEY ("ID_DMC"),
    CONSTRAINT fk_ceremonie_cles_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC"),
    CONSTRAINT ck_ceremonie_cles_etat CHECK ("ETAT" IN ('A_VENIR', 'CLOSE', 'A_REFAIRE'))
);
COMMENT ON TABLE public.t_ceremonie_cles IS
    'Ceremonie des cles d''une procedure en remise electronique : etat (A_VENIR, CLOSE, A_REFAIRE), date de cloture effective, premier depot (lot 3) — V66';

-- 3. Les clés des détenteurs
CREATE TABLE IF NOT EXISTS public.t_cle_detenteur (
    "ID_CLE"                  bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"                  bigint NOT NULL,
    "ROLE"                    character varying(10) NOT NULL,
    "IM"                      character varying(10),
    "CLE_PUBLIQUE"            text NOT NULL,
    "EMPREINTE"               character varying(64) NOT NULL,
    "ENV_CHIFFRE"             text NOT NULL,
    "ENV_IV"                  character varying(64) NOT NULL,
    "ENV_SEL"                 character varying(64) NOT NULL,
    "ENV_ITERATIONS"          integer NOT NULL,
    "ENV_KDF"                 character varying(30) NOT NULL,
    "ENV_ALGORITHME"          character varying(30) NOT NULL,
    "ETAT_PART"               character varying(10) NOT NULL,
    "DATE_PUBLICATION"        timestamp without time zone NOT NULL,
    "DERNIERE_VERIFICATION"   timestamp without time zone,
    "REMPLACEMENTS"           integer NOT NULL DEFAULT 0,
    "DATE_ARCHIVAGE"          timestamp without time zone,
    CONSTRAINT t_cle_detenteur_pkey PRIMARY KEY ("ID_CLE"),
    CONSTRAINT fk_cle_detenteur_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC"),
    CONSTRAINT ck_cle_detenteur_role CHECK ("ROLE" IN ('MEMBRE', 'SECOURS')),
    CONSTRAINT ck_cle_detenteur_etat CHECK ("ETAT_PART" IN ('PUBLIEE', 'VERIFIEE', 'PERDUE'))
);
-- Une seule clé ACTIVE par détenteur et par procédure (la part de secours n'a pas de matricule).
CREATE UNIQUE INDEX IF NOT EXISTS uq_cle_detenteur_active
    ON public.t_cle_detenteur ("ID_DMC", "ROLE", coalesce("IM", '')) WHERE "DATE_ARCHIVAGE" IS NULL;
CREATE INDEX IF NOT EXISTS idx_cle_detenteur_dmc ON public.t_cle_detenteur ("ID_DMC");
COMMENT ON TABLE public.t_cle_detenteur IS
    'Cle d''un detenteur de part (membre ou part de secours) : SPKI et empreinte publiques, cle privee enveloppee par la phrase secrete (le serveur ne peut pas la lire) ; archivee au remplacement apres le premier depot — V66, ADR-0013';

-- 4. Les défis de vérification (S2)
CREATE TABLE IF NOT EXISTS public.t_defi_cle (
    "ID_DEFI"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"            bigint NOT NULL,
    "ID_CLE"            bigint NOT NULL,
    "IM_APPELANT"       character varying(10),
    "EMPREINTE_CLAIR"   character varying(64) NOT NULL,
    "DATE_CREATION"     timestamp without time zone NOT NULL,
    "EXPIRE"            timestamp without time zone NOT NULL,
    "CONSOMME"          boolean NOT NULL DEFAULT false,
    CONSTRAINT t_defi_cle_pkey PRIMARY KEY ("ID_DEFI"),
    CONSTRAINT fk_defi_cle_cle FOREIGN KEY ("ID_CLE") REFERENCES public.t_cle_detenteur ("ID_CLE") ON DELETE CASCADE
);
COMMENT ON TABLE public.t_defi_cle IS
    'Defi de verification d''une part (ADR-0013 S2) : 32 octets chiffres avec la cle publique du detenteur, seul le SHA-256 du clair est garde, 5 minutes, usage unique — V66';

-- 5. Le rappel de vérification
INSERT INTO public.t_parametre ("CLE", "VALEUR", "DATE_MAJ") VALUES
    ('FICHE_SE_VERIFICATION_PART_JOURS', '7', now())
ON CONFLICT ("CLE") DO NOTHING;
