-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V67 — La commission d'appel d'offres (CAO), détentrice des parts de clé (demande front du 2026-10-04, soumission en
-- ligne, lot 2a ; décision du pilote, Q11 ; ADR-0010 amendé, ADR-0013).
--
-- 1. La CAO d'un DAO : la décision de nomination de la PRMP (référence, date, PDF facultatif).
-- 2. Ses membres : qualité MEMBRE (siège, détient une part) ou EXPERT_ADJOINT (évalue, pas de part) ; un MEMBRE a une
--    origine (agent de l'entité contractante, ou expert de l'objet du DAO) ; un président parmi les MEMBRE.
-- 3. Les comptes des membres (profil MEMBRE_CAO, identifiant K + 9 chiffres) : créés à la désignation, activés par
--    invitation (code à 72 h). Une personne garde son compte d'une CAO à l'autre.
-- 4. Les codes d'invitation réutilisent t_code_candidat : la clé étrangère vers t_compte_candidat est levée, la colonne
--    porte l'identifiant court du compte (C… ou K…).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

-- 1. La CAO
CREATE TABLE IF NOT EXISTS public.t_cao (
    "ID_DMC"               bigint NOT NULL,
    "DECISION_REFERENCE"   character varying(100) NOT NULL,
    "DECISION_DATE"        date NOT NULL,
    "DECISION_NOM_FICHIER" character varying(255),
    "DECISION_TAILLE"      bigint,
    "DECISION_FICHIER"     bytea,
    "DATE_MAJ"             timestamp without time zone NOT NULL,
    "ID_PRMP_MAJ"          character varying(10),
    CONSTRAINT t_cao_pkey PRIMARY KEY ("ID_DMC"),
    CONSTRAINT fk_cao_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC")
);
COMMENT ON TABLE public.t_cao IS
    'Commission d''appel d''offres d''un DAO : decision de nomination de la PRMP (reference, date, PDF facultatif) — V67, lot 2a';

-- 2. Les membres
CREATE TABLE IF NOT EXISTS public.t_cao_membre (
    "ID_MEMBRE"   bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"      bigint NOT NULL,
    "RANG"        integer NOT NULL DEFAULT 0,
    "NOM"         character varying(100) NOT NULL,
    "PRENOM"      character varying(100) NOT NULL,
    "EMAIL"       character varying(255) NOT NULL,
    "TELEPHONE"   character varying(30),
    "QUALITE"     character varying(15) NOT NULL,
    "ORIGINE"     character varying(20),
    "FONCTION"    character varying(200),
    "SERVICE"     character varying(200),
    "ORGANISME"   character varying(200),
    "DOMAINE"     character varying(200),
    "PRESIDENT"   boolean NOT NULL DEFAULT false,
    "ID_COMPTE"   character varying(10),
    CONSTRAINT t_cao_membre_pkey PRIMARY KEY ("ID_MEMBRE"),
    CONSTRAINT fk_cao_membre_cao FOREIGN KEY ("ID_DMC") REFERENCES public.t_cao ("ID_DMC") ON DELETE CASCADE,
    CONSTRAINT ck_cao_membre_qualite CHECK ("QUALITE" IN ('MEMBRE', 'EXPERT_ADJOINT')),
    CONSTRAINT ck_cao_membre_origine CHECK ("ORIGINE" IS NULL OR "ORIGINE" IN ('ENTITE_CONTRACTANTE', 'EXPERT_OBJET'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cao_membre_email ON public.t_cao_membre ("ID_DMC", lower("EMAIL"));
COMMENT ON TABLE public.t_cao_membre IS
    'Membre d''une CAO : qualite MEMBRE (part de cle, compte MEMBRE_CAO) ou EXPERT_ADJOINT (pas de part) ; origine entite contractante ou expert de l''objet ; un president — V67';

-- 3. Les comptes MEMBRE_CAO
CREATE SEQUENCE IF NOT EXISTS public.seq_compte_cao START 1;
CREATE TABLE IF NOT EXISTS public.t_compte_cao (
    "ID_COMPTE"            character varying(10) NOT NULL,
    "EMAIL"                character varying(255) NOT NULL,
    "NOM"                  character varying(100) NOT NULL,
    "PRENOM"               character varying(100) NOT NULL,
    "ETAT"                 character varying(10) NOT NULL,
    "DATE_CREATION"        timestamp without time zone NOT NULL,
    "DATE_INVITATION"      timestamp without time zone,
    "DATE_ACTIVATION"      timestamp without time zone,
    "DERNIERE_CONNEXION"   timestamp without time zone,
    CONSTRAINT t_compte_cao_pkey PRIMARY KEY ("ID_COMPTE"),
    CONSTRAINT uq_compte_cao_email UNIQUE ("EMAIL"),
    CONSTRAINT ck_compte_cao_etat CHECK ("ETAT" IN ('A_ACTIVER', 'ACTIF', 'ARCHIVE'))
);
COMMENT ON TABLE public.t_compte_cao IS
    'Compte d''un membre de CAO (profil MEMBRE_CAO, hors coquille interne) : cree a la designation, active par invitation ; une personne, un compte, plusieurs CAO — V67';

-- 4. Les codes d'invitation partagent la table des codes candidats
ALTER TABLE public.t_code_candidat DROP CONSTRAINT IF EXISTS fk_code_candidat_compte;
COMMENT ON COLUMN public.t_code_candidat."ID_CANDIDAT" IS
    'Identifiant court du compte : C… (candidat, t_compte_candidat) ou K… (membre de CAO, t_compte_cao) — V67';
