-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V68 — Le dépôt scellé d'une offre (demande front du 2026-10-04, soumission en ligne, lot 3 ; ADR-0013 §1, §4, §7).
--
-- 1. L'offre d'un candidat : un conteneur scellé dans son navigateur (en-tête JSON en clair, morceaux AES-256-GCM) que
--    le serveur ne peut pas lire. La base garde ce que le serveur sait — compte, entreprise, lot, horodatage, taille,
--    empreinte, en-tête (donc les empreintes des clés pour lesquelles l'offre est scellée), chemin du fichier — et rien
--    d'autre : ni le contenu, ni un prix. L'identifiant est l'UUID tiré par le navigateur (il figure dans l'en-tête et
--    dans les données authentifiées des morceaux).
-- 2. Les morceaux reçus (le nombre, la taille, l'empreinte ; le contenu est sur disque, app.offres.repertoire).
-- 3. Le journal des offres : création, morceaux, scellement, remplacement, retrait, purge — par compte et par offre.
-- 4. La clôture des dépôts notifiée (DEPOTS_CLOS), une fois par procédure.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_offre (
    "ID_OFFRE"               character varying(36) NOT NULL,
    "ID_DMC"                 bigint NOT NULL,
    "ID_CANDIDAT"            character varying(10) NOT NULL,
    "ID_ENTREPRISE"          integer NOT NULL,
    "NIF"                    character varying(50),
    "RAISON_SOCIALE"         character varying(255),
    "LOT"                    integer,
    "ETAT"                   character varying(10) NOT NULL,
    "DATE_CREATION"          timestamp without time zone NOT NULL,
    "DATE_DEPOT"             timestamp without time zone,
    "DATE_RETRAIT"           timestamp without time zone,
    "NUMERO"                 integer,
    "EN_TETE"                text NOT NULL,
    "NOMBRE_MORCEAUX"        integer NOT NULL,
    "TAILLE_MORCEAU"         integer NOT NULL,
    "TAILLE_CONTENU"         bigint,
    "TAILLE"                 bigint NOT NULL DEFAULT 0,
    "EMPREINTE"              character varying(64),
    "QUORUM"                 integer NOT NULL,
    "N"                      integer NOT NULL,
    "EMPREINTES_DETENTEURS"  text NOT NULL,
    "CHEMIN"                 character varying(500),
    "REMPLACE"               character varying(36),
    "REMPLACEE_PAR"          character varying(36),
    "GROUPEMENT_NIFS"        character varying(1000),
    "DERNIER_MORCEAU"        timestamp without time zone,
    CONSTRAINT t_offre_pkey PRIMARY KEY ("ID_OFFRE"),
    CONSTRAINT fk_offre_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC"),
    CONSTRAINT fk_offre_candidat FOREIGN KEY ("ID_CANDIDAT") REFERENCES public.t_compte_candidat ("ID_CANDIDAT"),
    CONSTRAINT ck_offre_etat CHECK ("ETAT" IN ('EN_COURS', 'DEPOSEE', 'REMPLACEE', 'RETIREE', 'ECARTEE'))
);
CREATE INDEX IF NOT EXISTS idx_offre_dmc ON public.t_offre ("ID_DMC", "ETAT");
CREATE INDEX IF NOT EXISTS idx_offre_candidat ON public.t_offre ("ID_CANDIDAT");
COMMENT ON TABLE public.t_offre IS
    'Offre deposee en ligne : conteneur scelle par le candidat (ADR-0013 §4), que le serveur ne peut pas lire ; ce qu''il sait seulement — V68, lot 3';

CREATE TABLE IF NOT EXISTS public.t_offre_morceau (
    "ID_MORCEAU"   bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_OFFRE"     character varying(36) NOT NULL,
    "RANG"         integer NOT NULL,
    "TAILLE"       integer NOT NULL,
    "EMPREINTE"    character varying(64) NOT NULL,
    "DATE_RECU"    timestamp without time zone NOT NULL,
    CONSTRAINT t_offre_morceau_pkey PRIMARY KEY ("ID_MORCEAU"),
    CONSTRAINT fk_offre_morceau_offre FOREIGN KEY ("ID_OFFRE") REFERENCES public.t_offre ("ID_OFFRE") ON DELETE CASCADE,
    CONSTRAINT uq_offre_morceau UNIQUE ("ID_OFFRE", "RANG")
);
COMMENT ON TABLE public.t_offre_morceau IS 'Morceaux recus d''une offre en cours de depot (taille, empreinte) ; le contenu est sur disque — V68';

CREATE TABLE IF NOT EXISTS public.t_offre_journal (
    "ID"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_OFFRE"     character varying(36) NOT NULL,
    "ID_DMC"       bigint NOT NULL,
    "ID_CANDIDAT"  character varying(10),
    "DATE"         timestamp without time zone NOT NULL,
    "ACTION"       character varying(30) NOT NULL,
    "DETAIL"       text,
    CONSTRAINT t_offre_journal_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS idx_offre_journal_offre ON public.t_offre_journal ("ID_OFFRE", "DATE");
COMMENT ON TABLE public.t_offre_journal IS 'Journal des offres (creation, morceaux, scellement, remplacement, retrait, purge), sans contenu — V68 ; survit a la purge';

ALTER TABLE public.t_ceremonie_cles ADD COLUMN IF NOT EXISTS "DATE_DEPOTS_CLOS" timestamp without time zone;
COMMENT ON COLUMN public.t_ceremonie_cles."DATE_DEPOTS_CLOS" IS 'La cloture des depots notifiee (DEPOTS_CLOS) a la PRMP et au responsable — V68';
