-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V69 — L'ouverture des plis en séance (demande front du 2026-10-04, soumission en ligne, lot 4 ; ADR-0013 §1, §2, §5).
--
-- 1. La séance d'une procédure : état (OUVERTE, DECHIFFREE, ILLISIBLE, CLOSE ; A_VENIR sans ligne), présences, part de
--    secours et son motif, observations, PV (PDF complet, et version publiée sans alertes ni vérification des NIF).
-- 2. Les apports de parts : QUI a apporté ses parts et QUAND — jamais les parts elles-mêmes, qui ne vivent qu'en mémoire du
--    serveur le temps de la séance.
-- 3. Ce que l'ouverture apprend de chaque offre : intégrité (INTACTE, ALTEREE, LECTURE_IMPOSSIBLE), la lecture tirée du
--    manifeste (JSON), le motif d'un écartement ; le contenu en clair va sur disque (app.offres.repertoire, <idOffre>.clair.zip).
-- 4. Le journal de la séance.
-- 5. Les rappels SEANCE_A_VENIR (la veille, une heure avant), une fois chacun.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_seance (
    "ID_DMC"           bigint NOT NULL,
    "ETAT"             character varying(12) NOT NULL,
    "OUVERTE_LE"       timestamp without time zone NOT NULL,
    "DECHIFFREE_LE"    timestamp without time zone,
    "CLOSE_LE"         timestamp without time zone,
    "PRESENTS"         character varying(1000),
    "AUTRES"           text,
    "SECOURS_EMPLOYE"  boolean NOT NULL DEFAULT false,
    "SECOURS_MOTIF"    text,
    "MOTIF_ILLISIBLE"  text,
    "OBSERVATIONS"     text,
    "PV"               bytea,
    "PV_PUBLIC"        bytea,
    "PV_PUBLIE"        boolean NOT NULL DEFAULT false,
    CONSTRAINT t_seance_pkey PRIMARY KEY ("ID_DMC"),
    CONSTRAINT fk_seance_dmc FOREIGN KEY ("ID_DMC") REFERENCES public.t_dossier_mec ("ID_DMC"),
    CONSTRAINT ck_seance_etat CHECK ("ETAT" IN ('OUVERTE', 'DECHIFFREE', 'ILLISIBLE', 'CLOSE'))
);
COMMENT ON TABLE public.t_seance IS
    'Seance d''ouverture des plis d''une procedure en ligne : etat, presences, part de secours, PV — V69, lot 4 (ADR-0013)';

CREATE TABLE IF NOT EXISTS public.t_seance_apport (
    "ID"          bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"      bigint NOT NULL,
    "DETENTEUR"   character varying(10) NOT NULL,
    "NOMBRE"      integer NOT NULL,
    "DATE"        timestamp without time zone NOT NULL,
    CONSTRAINT t_seance_apport_pkey PRIMARY KEY ("ID"),
    CONSTRAINT uq_seance_apport UNIQUE ("ID_DMC", "DETENTEUR")
);
COMMENT ON TABLE public.t_seance_apport IS
    'Apport des parts en seance : le detenteur (K... ou SECOURS), le nombre de parts, l''heure — jamais les parts — V69';

ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "INTEGRITE" character varying(20);
ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "LECTURE" text;
ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "MOTIF_LECTURE" text;
ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "MOTIF_ECARTEMENT" text;
ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "OUVERTE_LE" timestamp without time zone;
COMMENT ON COLUMN public.t_offre."LECTURE" IS 'La lecture tiree du manifeste a l''ouverture (JSON : entreprise, groupement, acte d''engagement, garantie, pieces) — V69';

CREATE TABLE IF NOT EXISTS public.t_seance_journal (
    "ID"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"     bigint NOT NULL,
    "DATE"       timestamp without time zone NOT NULL,
    "ACTEUR"     character varying(100),
    "ACTION"     character varying(30) NOT NULL,
    "DETAIL"     text,
    CONSTRAINT t_seance_journal_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS idx_seance_journal_dmc ON public.t_seance_journal ("ID_DMC", "DATE");
COMMENT ON TABLE public.t_seance_journal IS 'Journal de la seance (ouverture, presences, apports, secours, dechiffrement, ecartements, PV, constat) ; jamais une part — V69';

ALTER TABLE public.t_ceremonie_cles ADD COLUMN IF NOT EXISTS "RAPPEL_VEILLE" timestamp without time zone;
ALTER TABLE public.t_ceremonie_cles ADD COLUMN IF NOT EXISTS "RAPPEL_HEURE" timestamp without time zone;
