-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V70 — Les arbitrages du pilote après le lot 4 (demande front du 2026-10-04, soumission en ligne).
--
-- 1. §B2 — Le PV d'ouverture signé par la CAO : un état PV_A_SIGNER entre DECHIFFREE et CLOSE, les signataires attendus
--    (les membres présents, figés à la production du PV), la date où le PV est entièrement signé, et chaque signature
--    électronique simple (ou l'empêchement constaté par le président, avec son motif).
-- 2. §B4.2 — La conservation des offres : la date de purge d'une offre (conteneur et contenu déchiffré supprimés ; la ligne,
--    l'empreinte, la lecture et le journal restent).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_seance DROP CONSTRAINT IF EXISTS ck_seance_etat;
ALTER TABLE public.t_seance ADD CONSTRAINT ck_seance_etat
    CHECK ("ETAT" IN ('OUVERTE', 'DECHIFFREE', 'PV_A_SIGNER', 'ILLISIBLE', 'CLOSE'));
ALTER TABLE public.t_seance ADD COLUMN IF NOT EXISTS "SIGNATAIRES" character varying(1000);
ALTER TABLE public.t_seance ADD COLUMN IF NOT EXISTS "PV_SIGNE_LE" timestamp without time zone;
COMMENT ON COLUMN public.t_seance."SIGNATAIRES" IS 'Les membres presents appeles a signer le PV (K..., figes a sa production) — V70';

CREATE TABLE IF NOT EXISTS public.t_seance_signature (
    "ID"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"        bigint NOT NULL,
    "IM"            character varying(10) NOT NULL,
    "DATE"          timestamp without time zone NOT NULL,
    "EMPECHEMENT"   boolean NOT NULL DEFAULT false,
    "MOTIF"         text,
    "CONSTATE_PAR"  character varying(100),
    CONSTRAINT t_seance_signature_pkey PRIMARY KEY ("ID"),
    CONSTRAINT uq_seance_signature UNIQUE ("ID_DMC", "IM")
);
COMMENT ON TABLE public.t_seance_signature IS
    'Signature electronique simple du PV d''ouverture par un membre present de la CAO, ou son empechement constate par le president (motif) — V70';

ALTER TABLE public.t_offre ADD COLUMN IF NOT EXISTS "PURGEE_LE" timestamp without time zone;
COMMENT ON COLUMN public.t_offre."PURGEE_LE" IS 'Conteneur et contenu dechiffre supprimes au terme de la conservation (OFFRE_CONSERVATION_ANNEES), par un geste de l''Administrateur — V70';
