-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V72 — Le retrait du DAO après paiement des frais (demande front du 2026-10-06, « Voie B » du pilote).
--
-- 1. §B2 — Le reçu du paiement des frais de dossier, déposé par le candidat pour son entreprise (clé : le NIF), sur un ou
--    plusieurs lots (LOTS nul = tout le dossier), validé ou refusé par la PRMP ou l'UGPM de la fiche. Une décision ne se reprend
--    pas ; l'historique ne s'efface pas. Le fichier se purge avec les offres (V70).
-- 2. §B3 — Le journal des reçus : dépôt, validation, refus (motif).
-- 3. §B6 — Le retrait du registre dit le reçu qui l'a ouvert.
-- 4. H2 — La transition : le retrait est payant pour une procédure dont l'avis est imprimé pour la première fois à partir de
--    RETRAIT_PAYANT_DEPUIS (posé à l'application de V72) ; une procédure déjà lancée garde le retrait libre.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_recu_dao (
    "ID_RECU"             integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"              bigint NOT NULL,
    "ID_ENTREPRISE"       integer,
    "NIF"                 character varying(20) NOT NULL,
    "RAISON_SOCIALE"      character varying(255),
    "ID_CANDIDAT"         character varying(10) NOT NULL,
    "LOTS"                character varying(200),
    "MONTANT"             numeric(15,2),
    "REFERENCE_PAIEMENT"  character varying(100),
    "DATE_PAIEMENT"       date,
    "BANQUE"              character varying(200),
    "NOM_FICHIER"         character varying(255),
    "FORMAT"              character varying(50),
    "TAILLE_OCTETS"       bigint,
    "EMPREINTE"           character varying(64),
    "CONTENU"             bytea,
    "DATE_DEPOT"          timestamp without time zone NOT NULL,
    "ETAT"                character varying(10) NOT NULL,
    "MOTIF_REFUS"         text,
    "DATE_DECISION"       timestamp without time zone,
    "DECIDE_PAR"          character varying(20),
    "LOGIN_DECIDEUR"      character varying(255),
    "PURGE_LE"            timestamp without time zone,
    CONSTRAINT t_recu_dao_pkey PRIMARY KEY ("ID_RECU"),
    CONSTRAINT ck_recu_dao_etat CHECK ("ETAT" IN ('EN_ATTENTE', 'VALIDE', 'REFUSE'))
);
CREATE INDEX IF NOT EXISTS idx_recu_dao_dmc_nif ON public.t_recu_dao ("ID_DMC", "NIF");
COMMENT ON TABLE public.t_recu_dao IS
    'Recu du paiement des frais de dossier (DAO), depose par le candidat pour son entreprise (NIF), valide ou refuse par la PRMP ou l''UGPM de la fiche ; condition du retrait — V72';

CREATE TABLE IF NOT EXISTS public.t_recu_journal (
    "ID"        bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_RECU"   integer NOT NULL,
    "ID_DMC"    bigint NOT NULL,
    "DATE"      timestamp without time zone NOT NULL,
    "ACTEUR"    character varying(255),
    "ACTION"    character varying(30) NOT NULL,
    "DETAIL"    text,
    CONSTRAINT t_recu_journal_pkey PRIMARY KEY ("ID")
);
COMMENT ON TABLE public.t_recu_journal IS 'Journal des recus de frais de dossier : RECU_DEPOSE, RECU_VALIDE, RECU_REFUSE — V72';

ALTER TABLE public.t_retrait_dao ADD COLUMN IF NOT EXISTS "ID_RECU" integer;

INSERT INTO public.t_parametre ("CLE", "VALEUR", "DATE_MAJ") VALUES
    ('RETRAIT_PAYANT_DEPUIS', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'), now())
ON CONFLICT ("CLE") DO NOTHING;
