-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V80 — Évaluation des offres, lot 2, tranche 2b (demande front du 2026-10-07 « de la proposition d'attribution à la notification »,
-- §B3, §B4.1, §B4.2 ; arbitrages du pilote : l'attribution à l'offre proposée par la CAO seule (Q4), modèles provisoires des lettres
-- en attendant les modèles officiels (Q7), signature électronique simple de la PRMP, horodatée et journalisée (Q9) ; loi n° 2016-055,
-- art. 78 : le délai de dix jours francs court de la plus tardive de l'information et de l'affichage).
--
-- 1. Le choix de l'attributaire et l'information des candidats, sur la ligne du lot (t_attribution).
-- 2. Les lettres produites à l'information (une par candidat : rejet ou attribution), signées de la PRMP, avec la date d'envoi du
--    courriel et l'accusé de lecture de la plateforme (art. 52-I : la preuve de la réception).
-- 3. Les demandes d'explication des candidats non retenus et les réponses écrites de la PRMP (art. 52-II).
-- 4. Le rattrapage du PV d'ouverture des dossiers de marché créés sur une séance close avant V70 (constat D1).
-- 5. Les codes CCAG et CCTP des types de pièces du dossier DAO (constat E2).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ID_OFFRE_ATTRIBUEE" character varying(36);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ATTRIBUE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ATTRIBUE_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MOTIF_ATTRIBUTION" text;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MONTANT" numeric(18,2);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MONTANT_TTC" numeric(18,2);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DELAI" character varying(50);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "INFORME_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "INFORME_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "SIGNATAIRE" character varying(200);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DATE_AFFICHAGE" date;

CREATE TABLE IF NOT EXISTS public.t_attribution_lettre (
    "ID"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"        bigint NOT NULL,
    "LOT"           integer NOT NULL,
    "ID_OFFRE"      character varying(36) NOT NULL,
    "TYPE"          character varying(20) NOT NULL,
    "MOTIF"         text,
    "PDF"           bytea,
    "DOCX"          bytea,
    "PRODUITE_LE"   timestamp without time zone NOT NULL,
    "ENVOYEE_LE"    timestamp without time zone,
    "LUE_LE"        timestamp without time zone,
    CONSTRAINT t_attribution_lettre_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_attribution_lettre_type CHECK ("TYPE" IN ('ATTRIBUTION', 'NON_RETENU'))
);
CREATE INDEX IF NOT EXISTS ix_attribution_lettre_lot ON public.t_attribution_lettre ("ID_DMC", "LOT");
CREATE INDEX IF NOT EXISTS ix_attribution_lettre_offre ON public.t_attribution_lettre ("ID_OFFRE");

CREATE TABLE IF NOT EXISTS public.t_attribution_explication (
    "ID"               bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"           bigint NOT NULL,
    "LOT"              integer NOT NULL,
    "ID_OFFRE"         character varying(36) NOT NULL,
    "QUESTION"         text NOT NULL,
    "DEMANDEE_LE"      timestamp without time zone NOT NULL,
    "REPONSE"          text,
    "REPONSE_NOM"      character varying(255),
    "REPONSE_FORMAT"   character varying(50),
    "REPONSE_TAILLE"   bigint,
    "REPONSE_CONTENU"  bytea,
    "REPONDUE_LE"      timestamp without time zone,
    "REPONDUE_PAR"     character varying(100),
    CONSTRAINT t_attribution_explication_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS ix_attribution_explication_dmc ON public.t_attribution_explication ("ID_DMC");
CREATE INDEX IF NOT EXISTS ix_attribution_explication_offre ON public.t_attribution_explication ("ID_OFFRE");

-- 4. Rattrapage (constat D1 de la recette du 07/10) : le PV d'ouverture d'une séance close avant les signatures électroniques (V70)
--    n'a pas de date de signature ; la tranche 2a ne le joignait donc pas au dossier de marché. Il est joint ici aux dossiers de marché
--    qui n'ont pas encore de pièce PV_OUVERTURE (fiche 40, dossier 100371 en recette). Sans effet ailleurs ; idempotent.
INSERT INTO public.t_piece_jointe_dossier ("APRES_LETTRE_RENVOI", "CONTENU", "DATE_UPLOAD", "FORMAT", "ID_DOSSIER", "ID_TYPE_PIECE",
                                          "NOM_FICHIER", "TAILLE")
SELECT false, s."PV", now(), 'PDF', a."ID_DOSSIER", tp."ID_TYPE_PIECE", 'pv-ouverture_' || a."ID_DMC" || '.pdf', length(s."PV")
  FROM public.t_attribution a
  JOIN public.t_seance s ON s."ID_DMC" = a."ID_DMC" AND s."ETAT" = 'CLOSE' AND s."PV" IS NOT NULL
  JOIN public.t_type_piece_jointe tp ON tp."CODE" = 'PV_OUVERTURE'
 WHERE a."ID_DOSSIER" IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM public.t_piece_jointe_dossier p
                    WHERE p."ID_DOSSIER" = a."ID_DOSSIER" AND p."ID_TYPE_PIECE" = tp."ID_TYPE_PIECE");

-- 5. Les codes du CCAG et du CCTP du dossier DAO (constat E2 de la recette du DAO complet) : un dossier qui porte le DAO complet n'a
--    plus à les joindre à part (le CCAG toujours, le CCTP quand la fiche a ses spécifications techniques) ; le code les repère sans
--    dépendre de leur identifiant. Sans effet là où ces types n'existent pas ; idempotent.
UPDATE public.t_type_piece_jointe SET "CODE" = 'CCAG'
 WHERE "ID_TYPE_DOSSIER" = 'DMC' AND "LIBELLE_PIECE" = 'Cahier des clauses administratives générales' AND "CODE" IS NULL
   AND NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe WHERE "CODE" = 'CCAG');
UPDATE public.t_type_piece_jointe SET "CODE" = 'CCTP'
 WHERE "ID_TYPE_DOSSIER" = 'DMC' AND "LIBELLE_PIECE" = 'Cahier des clauses techniques particulières' AND "CODE" IS NULL
   AND NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe WHERE "CODE" = 'CCTP');
