-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V81 — Évaluation des offres, lot 2, tranche 2c (demande front du 2026-10-07 « de la proposition d'attribution à la notification »,
-- §B4.3, §B4.4, §B5 ; arbitrages du pilote : recours déclarés et typés (Q5, loi n° 2016-055 titre VIII), enregistrement = date et
-- pièce justificative, aucune notification sans enregistrement (Q6), modèle provisoire de l'avis d'attribution (Q7), signature
-- électronique simple de la PRMP (Q9)).
--
-- 1. Sur la ligne du lot (t_attribution) : la mise au point, la signature du marché, son enregistrement, sa notification et sa
--    réception, l'avis d'attribution (PDF, Word) et sa publication, le retrait faute de pièces fiscales et sociales.
-- 2. Les recours reçus par la PRMP : réexamen (art. 79), révision ARMP (art. 80), référé (art. 78), et leur décision.
-- 3. Les fichiers de l'attribution : rapport de mise au point, marché signé, justificatif d'enregistrement, pièces des recours et de
--    leurs décisions, pièces fiscales et sociales de l'attributaire (art. 20-I) et leur vérification par la PRMP.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "RAPPORT_MISE_AU_POINT" text;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MISE_AU_POINT_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MISE_AU_POINT_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DATE_SIGNATURE" date;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "SIGNE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "SIGNE_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DATE_ENREGISTREMENT" date;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "REFERENCE_ENREGISTREMENT" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ENREGISTRE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DATE_NOTIFICATION" date;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "NOTIFIE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "NOTIFIE_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "NOTIFICATION_RECUE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "RECEPTION_DECLAREE" boolean;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DATE_PUBLICATION_AVIS" date;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "AVIS_PUBLIE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "AVIS_PUBLIE_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "AVIS_PDF" bytea;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "AVIS_DOCX" bytea;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "RETIRE_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "RETIRE_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MOTIF_RETRAIT" text;

CREATE TABLE IF NOT EXISTS public.t_attribution_recours (
    "ID"              bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"          bigint NOT NULL,
    "LOT"             integer NOT NULL,
    "TYPE"            character varying(20) NOT NULL,
    "DATE_RECEPTION"  date NOT NULL,
    "REQUERANT"       character varying(255) NOT NULL,
    "OBJET"           text NOT NULL,
    "DECLARE_LE"      timestamp without time zone NOT NULL,
    "DECLARE_PAR"     character varying(100),
    "DATE_DECISION"   date,
    "ISSUE"           character varying(20),
    "MOTIF_DECISION"  text,
    "DECIDE_LE"       timestamp without time zone,
    "DECIDE_PAR"      character varying(100),
    CONSTRAINT t_attribution_recours_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_attribution_recours_type CHECK ("TYPE" IN ('REEXAMEN', 'REVISION_ARMP', 'REFERE')),
    CONSTRAINT ck_attribution_recours_issue CHECK ("ISSUE" IS NULL OR "ISSUE" IN ('REJETE', 'ACCUEILLI', 'AUTRE'))
);
CREATE INDEX IF NOT EXISTS ix_attribution_recours_lot ON public.t_attribution_recours ("ID_DMC", "LOT");

CREATE TABLE IF NOT EXISTS public.t_attribution_piece (
    "ID"               bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"           bigint NOT NULL,
    "LOT"              integer NOT NULL,
    "NATURE"           character varying(20) NOT NULL,
    "ID_RECOURS"       bigint,
    "NOM"              character varying(255) NOT NULL,
    "FORMAT"           character varying(50) NOT NULL,
    "TAILLE"           bigint NOT NULL,
    "CONTENU"          bytea NOT NULL,
    "DEPOSE_LE"        timestamp without time zone NOT NULL,
    "DEPOSE_PAR"       character varying(100),
    "DATE_DELIVRANCE"  date,
    "CONFORME"         boolean,
    "MOTIF"            text,
    "VERIFIEE_LE"      timestamp without time zone,
    "VERIFIEE_PAR"     character varying(100),
    CONSTRAINT t_attribution_piece_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_attribution_piece_nature CHECK ("NATURE" IN ('MISE_AU_POINT', 'MARCHE_SIGNE', 'ENREGISTREMENT', 'RECOURS',
        'DECISION_RECOURS', 'FISCALE', 'SOCIALE'))
);
CREATE INDEX IF NOT EXISTS ix_attribution_piece_lot ON public.t_attribution_piece ("ID_DMC", "LOT");
