-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V82 — L'appel à manifestation d'intérêt en ligne (prestations intellectuelles), tranche AMI-a (demande front du 2026-10-07,
-- `demande-backend-2026-10-07-ami-pi.md`, §B1, §B2 ; loi n° 2016-055, art. 32 et 42-II ; arbitrages du pilote : expressions lues
-- après la date limite seulement (Q2), liste restreinte publiée et notifiée (Q5), rapport joint au dossier de la demande de
-- propositions (Q4) ; le seuil de dispense de publicité (Q1) reste au juriste : la PRMP déclare la dispense, avec son motif).
--
-- 1. L'AMI d'une procédure de prestations intellectuelles (une fiche, un AMI) : critères de sélection pondérés, pièces attendues,
--    note minimale de qualification, nombre de candidats à retenir (six, art. 42-II), date limite, avis produit (PDF, Word), supports
--    de publication déclarés ; ou la dispense de publicité déclarée.
-- 2. Les expressions d'intérêt déposées par les candidats (en clair, sans scellement ; illisibles de l'administration avant la date
--    limite), avec leurs pièces ; remplacement et retrait avant la date limite.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_ami (
    "ID_DMC"           bigint NOT NULL,
    "ETAT"             character varying(20) NOT NULL,
    "OBJET"            text,
    "DATE_LIMITE"      timestamp without time zone,
    "CRITERES"         text,
    "PIECES"           text,
    "NOTE_MINIMALE"    numeric(5,2),
    "NOMBRE_RETENUS"   integer NOT NULL DEFAULT 6,
    "MOTIF_DISPENSE"   text,
    "PUBLICATIONS"     text,
    "AVIS_PDF"         bytea,
    "AVIS_DOCX"        bytea,
    "AVIS_PRODUIT_LE"  timestamp without time zone,
    "PUBLIE_LE"        timestamp without time zone,
    "PUBLIE_PAR"       character varying(100),
    "CREE_LE"          timestamp without time zone NOT NULL,
    "CREE_PAR"         character varying(100),
    "MODIFIE_LE"       timestamp without time zone,
    CONSTRAINT t_ami_pkey PRIMARY KEY ("ID_DMC"),
    CONSTRAINT ck_ami_etat CHECK ("ETAT" IN ('BROUILLON', 'PUBLIE', 'DISPENSE'))
);

CREATE TABLE IF NOT EXISTS public.t_ami_expression (
    "ID"              character varying(36) NOT NULL,
    "ID_DMC"          bigint NOT NULL,
    "ID_CANDIDAT"     character varying(10) NOT NULL,
    "NIF"             character varying(50),
    "RAISON_SOCIALE"  character varying(255),
    "NUMERO"          integer,
    "ETAT"            character varying(20) NOT NULL,
    "CONTENU"         text NOT NULL,
    "EMPREINTE"       character varying(64) NOT NULL,
    "DEPOSEE_LE"      timestamp without time zone NOT NULL,
    "RETIREE_LE"      timestamp without time zone,
    "REMPLACEE_PAR"   character varying(36),
    CONSTRAINT t_ami_expression_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_ami_expression_etat CHECK ("ETAT" IN ('DEPOSEE', 'REMPLACEE', 'RETIREE'))
);
CREATE INDEX IF NOT EXISTS ix_ami_expression_dmc ON public.t_ami_expression ("ID_DMC");
CREATE UNIQUE INDEX IF NOT EXISTS uq_ami_expression_deposee ON public.t_ami_expression ("ID_DMC", "ID_CANDIDAT") WHERE "ETAT" = 'DEPOSEE';

CREATE TABLE IF NOT EXISTS public.t_ami_expression_piece (
    "ID"             bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_EXPRESSION"  character varying(36) NOT NULL,
    "LIBELLE"        character varying(255) NOT NULL,
    "NOM"            character varying(255) NOT NULL,
    "FORMAT"         character varying(50) NOT NULL,
    "TAILLE"         bigint NOT NULL,
    "EMPREINTE"      character varying(64) NOT NULL,
    "CONTENU"        bytea NOT NULL,
    CONSTRAINT t_ami_expression_piece_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS ix_ami_expression_piece ON public.t_ami_expression_piece ("ID_EXPRESSION");
