-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V83 — L'appel à manifestation d'intérêt en ligne, tranche AMI-b (demande front du 2026-10-07, `demande-backend-2026-10-07-ami-pi.md`,
-- §B3, §B4 ; arbitrages du pilote : moins de six qualifiés, la liste s'arrête avec eux et le nombre est motivé, ou l'AMI est relancé
-- (Q3) ; le rapport et la liste sont joints d'office au dossier de la demande de propositions (Q4) ; la liste est publiée et notifiée
-- (Q5)).
--
-- 1. La déclaration préalable des membres de la commission sur l'AMI (absence de conflit d'intérêts, confidentialité).
-- 2. La notation des expressions d'intérêt, critère par critère (une note retenue par critère, motivée), et leur écartement motivé.
-- 3. La liste restreinte arrêtée par le président (rang, candidat, note), le rapport de présélection (PDF, Word) et ses signatures ;
--    la relance de l'AMI ; l'AMI infructueux (art. 56-II).
-- 4. Le type de pièce « Rapport de présélection (AMI) » du dossier de la demande de propositions (famille DMC), facultatif, code
--    RAPPORT_PRESELECTION ; sans effet là où la famille n'existe pas.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_ami DROP CONSTRAINT IF EXISTS ck_ami_etat;
ALTER TABLE public.t_ami ADD CONSTRAINT ck_ami_etat CHECK ("ETAT" IN ('BROUILLON', 'PUBLIE', 'DISPENSE', 'INFRUCTUEUX'));
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "LISTE_ARRETEE_LE" timestamp without time zone;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "LISTE_ARRETEE_PAR" character varying(100);
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "MOTIF_NOMBRE" text;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "OBSERVATIONS" text;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "RAPPORT_PDF" bytea;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "RAPPORT_DOCX" bytea;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "SIGNATAIRES" character varying(1000);
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "LISTE_DEFINITIVE_LE" timestamp without time zone;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "NOMBRE_RELANCES" integer NOT NULL DEFAULT 0;
ALTER TABLE public.t_ami ADD COLUMN IF NOT EXISTS "MOTIF_INFRUCTUEUX" text;

ALTER TABLE public.t_ami_expression ADD COLUMN IF NOT EXISTS "MOTIF_ECARTEMENT" text;
ALTER TABLE public.t_ami_expression ADD COLUMN IF NOT EXISTS "ECARTEE_LE" timestamp without time zone;
ALTER TABLE public.t_ami_expression ADD COLUMN IF NOT EXISTS "ECARTEE_PAR" character varying(100);

CREATE TABLE IF NOT EXISTS public.t_ami_declaration (
    "ID"         bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"     bigint NOT NULL,
    "IM"         character varying(20) NOT NULL,
    "SIGNEE_LE"  timestamp without time zone NOT NULL,
    "CONFLIT"    boolean NOT NULL DEFAULT false,
    "PRECISION"  text,
    CONSTRAINT t_ami_declaration_pkey PRIMARY KEY ("ID"),
    CONSTRAINT uq_ami_declaration UNIQUE ("ID_DMC", "IM")
);

CREATE TABLE IF NOT EXISTS public.t_ami_note (
    "ID"             bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"         bigint NOT NULL,
    "ID_EXPRESSION"  character varying(36) NOT NULL,
    "CODE_CRITERE"   character varying(20) NOT NULL,
    "NOTE"           numeric(6,2) NOT NULL,
    "MOTIF"          text,
    "PAR"            character varying(100),
    "LE"             timestamp without time zone NOT NULL,
    CONSTRAINT t_ami_note_pkey PRIMARY KEY ("ID"),
    CONSTRAINT uq_ami_note UNIQUE ("ID_EXPRESSION", "CODE_CRITERE")
);
CREATE INDEX IF NOT EXISTS ix_ami_note_dmc ON public.t_ami_note ("ID_DMC");

CREATE TABLE IF NOT EXISTS public.t_ami_liste (
    "ID_DMC"          bigint NOT NULL,
    "RANG"            integer NOT NULL,
    "ID_EXPRESSION"   character varying(36) NOT NULL,
    "ID_CANDIDAT"     character varying(10) NOT NULL,
    "NIF"             character varying(50),
    "RAISON_SOCIALE"  character varying(255),
    "NOTE"            numeric(6,2),
    CONSTRAINT t_ami_liste_pkey PRIMARY KEY ("ID_DMC", "RANG")
);

CREATE TABLE IF NOT EXISTS public.t_ami_signature (
    "ID"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"        bigint NOT NULL,
    "IM"            character varying(20) NOT NULL,
    "DATE"          timestamp without time zone NOT NULL,
    "EMPECHEMENT"   boolean NOT NULL DEFAULT false,
    "MOTIF"         text,
    "CONSTATE_PAR"  character varying(100),
    "OBSERVATION"   text,
    CONSTRAINT t_ami_signature_pkey PRIMARY KEY ("ID"),
    CONSTRAINT uq_ami_signature UNIQUE ("ID_DMC", "IM")
);

-- ⚠️ L'identifiant est posé explicitement (MAX + 1) : la séquence d'identité peut être en retard sur les lignes existantes (cas de
-- DBPRS20 le 08/10 : séquence à 22, maximum à 23) ; elle est recalée ensuite sur le maximum.
INSERT INTO public.t_type_piece_jointe ("ID_TYPE_PIECE", "ID_TYPE_DOSSIER", "LIBELLE_PIECE", "OBLIGATOIRE", "ORDRE", "CODE")
SELECT (SELECT COALESCE(MAX("ID_TYPE_PIECE"), 0) + 1 FROM public.t_type_piece_jointe), 'DMC', 'Rapport de présélection (AMI)', false,
       (SELECT COALESCE(MAX("ORDRE"), 0) + 1 FROM public.t_type_piece_jointe WHERE "ID_TYPE_DOSSIER" = 'DMC'), 'RAPPORT_PRESELECTION'
 WHERE EXISTS (SELECT 1 FROM public.tr_type_dossier WHERE "ID_TYPE_DOSSIER" = 'DMC')
   AND NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe WHERE "CODE" = 'RAPPORT_PRESELECTION');
SELECT setval(pg_get_serial_sequence('public.t_type_piece_jointe', 'ID_TYPE_PIECE'), MAX("ID_TYPE_PIECE"))
  FROM public.t_type_piece_jointe HAVING MAX("ID_TYPE_PIECE") IS NOT NULL;
