-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V84 — Évaluation des offres, lot 3 (prestations intellectuelles), tranche PI-a (demande front du 2026-10-07,
-- `demande-backend-2026-10-07-evaluation-pi.md`, §B1 ; arbitrages du pilote : sous-critères techniques saisis dans la fiche (Q3)).
--
-- 1. Les sous-critères techniques d'une version de fiche PI : chaque critère B06-TP-02 à B06-TP-06 se détaille en sous-critères
--    pondérés, dont la somme fait les points du critère ; remplacés en bloc, figés à la validation, copiés à la révision.
-- 2. Les invitations de la consultation restreinte : un candidat de la liste (AMI, avec son compte) ou saisi (avec son adresse
--    électronique, par laquelle son compte lui sera rattaché), son rang, sa lettre. La procédure n'est visible que des invités.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_fiche_sous_critere (
    "ID_SOUS_CRITERE"  integer GENERATED BY DEFAULT AS IDENTITY,
    "ID_FICHE"         integer NOT NULL,
    "CRITERE"          character varying(20) NOT NULL,
    "ORDRE"            integer NOT NULL,
    "LIBELLE"          character varying(300) NOT NULL,
    "POINTS"           numeric(7,2) NOT NULL,
    CONSTRAINT t_fiche_sous_critere_pkey PRIMARY KEY ("ID_SOUS_CRITERE"),
    CONSTRAINT fk_fiche_sous_critere_fiche FOREIGN KEY ("ID_FICHE") REFERENCES public.t_fiche_marche ("ID_FICHE") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_fiche_sous_critere_fiche ON public.t_fiche_sous_critere ("ID_FICHE");

CREATE TABLE IF NOT EXISTS public.t_invitation (
    "ID"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"        bigint NOT NULL,
    "RANG"          integer NOT NULL,
    "SOURCE"        character varying(10) NOT NULL,
    "ID_CANDIDAT"   character varying(10),
    "EMAIL"         character varying(150),
    "NOM"           character varying(255) NOT NULL,
    "ID_DOCUMENT"   integer,
    "INVITE_LE"     timestamp without time zone NOT NULL,
    CONSTRAINT t_invitation_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_invitation_source CHECK ("SOURCE" IN ('AMI', 'SAISIE'))
);
CREATE INDEX IF NOT EXISTS ix_invitation_dmc ON public.t_invitation ("ID_DMC");
CREATE INDEX IF NOT EXISTS ix_invitation_candidat ON public.t_invitation ("ID_CANDIDAT");
