-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V91 — Attribution (lot 2), tranche 2d-1 (demande front du 2026-10-07, `demande-backend-2026-10-07-attribution-notification.md`,
-- §B6 infructuosité, Q3, §B7 ; arbitrages du pilote : Q3 après un avis défavorable, la PRMP choisit avec un motif entre la reprise de
-- l'évaluation — rouverte en entier, rapport archivé — et l'infructuosité ; jamais d'infructuosité après l'attribution, art. 56-VI).
--
-- 1. t_attribution : la déclaration d'infructuosité du lot (décision de la PRMP, sa référence, sa date, la suite déclarée) ; les
--    alertes déjà émises (délai d'attente écoulé, échéance de l'avis d'attribution).
-- 2. t_attribution_recours : l'alerte de l'échéance d'un réexamen.
-- 3. t_attribution_reprise : chaque reprise de l'évaluation après un avis défavorable — le dossier de marché refusé, son avis, le
--    motif, et le rapport d'évaluation archivé (PDF, Word, dates, signatures).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "INFRUCTUEUX_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "INFRUCTUEUX_PAR" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "MOTIF_INFRUCTUOSITE" text;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DECISION_REFERENCE" character varying(100);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "DECISION_DATE" date;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "SUITE" character varying(12);
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ALERTE_DELAI_LE" timestamp without time zone;
ALTER TABLE public.t_attribution ADD COLUMN IF NOT EXISTS "ALERTE_AVIS_LE" timestamp without time zone;

ALTER TABLE public.t_attribution_recours ADD COLUMN IF NOT EXISTS "ALERTE_LE" timestamp without time zone;

CREATE TABLE IF NOT EXISTS public.t_attribution_reprise (
    "ID"                  bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"              bigint NOT NULL,
    "LOT"                 integer NOT NULL,
    "ID_DOSSIER"          integer,
    "ID_OFFRE_PROPOSEE"   character varying(36),
    "AVIS"                character varying(10),
    "MOTIF"               text NOT NULL,
    "LE"                  timestamp without time zone NOT NULL,
    "PAR"                 character varying(100),
    "RAPPORT_PRODUIT_LE"  timestamp without time zone,
    "RAPPORT_SIGNE_LE"    timestamp without time zone,
    "RAPPORT_SIGNATURES"  text,
    "RAPPORT_PDF"         bytea,
    "RAPPORT_DOCX"        bytea,
    CONSTRAINT t_attribution_reprise_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS ix_attribution_reprise_dmc ON public.t_attribution_reprise ("ID_DMC", "LOT");
