-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V93 — Attribution (lot 2), tranche 2d-3 (demande front du 2026-10-07, `demande-backend-2026-10-07-attribution-notification.md`,
-- §B6 « sans suite », Q10 ; loi n° 2016-055, art. 55 ; arbitrages du pilote du 2026-10-08 : une famille propre DSS ; les 5 jours de
-- l'organe de contrôle courent de la réception du dossier ; le circuit de signature tel qu'il est ; le sans suite déclaré par un
-- geste de la PRMP après l'avis favorable).
--
-- 1. La famille et le sous-type « DSS — Déclaration sans suite » (circuit de la Commission), et sa pièce « Motifs de la déclaration
--    sans suite » (code MOTIFS_SANS_SUITE, produite par le serveur ; identifiant explicite puis recalage de la séquence, cf. V83).
-- 2. t_sans_suite : chaque demande de la PRMP (motifs, dossier DSS), l'avis rendu, la déclaration, les alertes.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

INSERT INTO public.tr_type_dossier ("ID_TYPE_DOSSIER", "LIBELLE_TYPE")
SELECT 'DSS', 'Déclaration sans suite'
WHERE NOT EXISTS (SELECT 1 FROM public.tr_type_dossier WHERE "ID_TYPE_DOSSIER" = 'DSS');

INSERT INTO public.tr_sous_type_dossier ("ID_SOUS_TYPE", "ID_TYPE_DOSSIER", "LIBELLE_SOUS_TYPE")
SELECT 'DSS', 'DSS', 'Déclaration sans suite'
WHERE NOT EXISTS (SELECT 1 FROM public.tr_sous_type_dossier WHERE "ID_SOUS_TYPE" = 'DSS');

INSERT INTO public.t_type_piece_jointe ("ID_TYPE_PIECE", "ID_TYPE_DOSSIER", "LIBELLE_PIECE", "OBLIGATOIRE", "ORDRE", "CODE")
SELECT COALESCE((SELECT MAX("ID_TYPE_PIECE") FROM public.t_type_piece_jointe), 0) + 1, 'DSS', 'Motifs de la déclaration sans suite',
       true, 1, 'MOTIFS_SANS_SUITE'
WHERE NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe WHERE "CODE" = 'MOTIFS_SANS_SUITE');

SELECT setval(pg_get_serial_sequence('public.t_type_piece_jointe', 'ID_TYPE_PIECE'),
              GREATEST((SELECT COALESCE(MAX("ID_TYPE_PIECE"), 0) FROM public.t_type_piece_jointe), 1));

CREATE TABLE IF NOT EXISTS public.t_sans_suite (
    "ID"                  bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_DMC"              bigint NOT NULL,
    "MOTIFS"              text NOT NULL,
    "DEMANDE_LE"          timestamp without time zone NOT NULL,
    "DEMANDE_PAR"         character varying(100),
    "ID_DOSSIER"          integer,
    "MOTIFS_PDF"          bytea,
    "MOTIFS_DOCX"         bytea,
    "AVIS"                character varying(10),
    "AVIS_CONSTATE_LE"    timestamp without time zone,
    "ALERTE_LE"           timestamp without time zone,
    "DECISION_REFERENCE"  character varying(100),
    "DECISION_DATE"       date,
    "DECLARE_LE"          timestamp without time zone,
    "DECLARE_PAR"         character varying(100),
    CONSTRAINT t_sans_suite_pkey PRIMARY KEY ("ID")
);
CREATE INDEX IF NOT EXISTS ix_sans_suite_dmc ON public.t_sans_suite ("ID_DMC");
