-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V95 — Le référentiel du contrôle aligné sur le Manuel de contrôle a priori, tranche M2 : les pièces exigées PAR SOUS-TYPE (demande
-- front du 2026-10-08 `demande-backend-2026-10-08-manuel-controle-a-priori.md`, §B2 ; arbitrages du pilote du 08/10 : les pièces « * »
-- du manuel exigées dès M2 ; les plans PPM / PPM-AGPM inchangés ; sans fiche, les pièces qui dépendent de la catégorie sont servies
-- sans obligation).
--
-- 1. t_piece_sous_type : l'association d'un type de pièce à un sous-type — obligation, ordre, et condition sur la CATEGORIE de la fiche
--    (FOURNITURES_SERVICES, TRAVAUX, PRESTATIONS_INTELLECTUELLES) et sur la FORME (CONTRAT_CADRE ; AUTRE = toute autre forme). Un
--    sous-type qui a une liste n'utilise qu'elle ; les autres gardent les pièces de leur famille (comportement d'avant).
-- 2. La bibliothèque des pièces du manuel (types sans famille : ID_TYPE_DOSSIER nul, servis par leurs associations), codes stables ;
--    identifiants explicites (MAX + rang) puis recalage de la séquence (cf. V83).
-- 3. Les listes du manuel, sous-type par sous-type ; les pièces que l'application joint d'office y sont reprises par leur code
--    (DAO_COMPLET, RAPPORT_PRESELECTION, PROJET_MARCHE, CAHIER_CHARGES, DEVIS_ESTIMATIF, PV_OUVERTURE, RAPPORT_ANALYSE,
--    MOTIFS_SANS_SUITE). Les associations ne s'écrivent que pour les sous-types présents au référentiel.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_piece_sous_type (
    "ID"             bigint GENERATED BY DEFAULT AS IDENTITY,
    "ID_TYPE_PIECE"  integer NOT NULL REFERENCES public.t_type_piece_jointe ("ID_TYPE_PIECE"),
    "ID_SOUS_TYPE"   character varying(20) NOT NULL REFERENCES public.tr_sous_type_dossier ("ID_SOUS_TYPE"),
    "OBLIGATOIRE"    boolean NOT NULL,
    "ORDRE"          integer NOT NULL,
    "CATEGORIE"      character varying(40),
    "FORME"          character varying(20),
    CONSTRAINT t_piece_sous_type_pkey PRIMARY KEY ("ID"),
    CONSTRAINT ck_piece_sous_type_forme CHECK ("FORME" IS NULL OR "FORME" IN ('CONTRAT_CADRE', 'AUTRE'))
);
CREATE INDEX IF NOT EXISTS ix_piece_sous_type ON public.t_piece_sous_type ("ID_SOUS_TYPE", "ORDRE");
CREATE UNIQUE INDEX IF NOT EXISTS uk_piece_sous_type ON public.t_piece_sous_type
    ("ID_TYPE_PIECE", "ID_SOUS_TYPE", COALESCE("CATEGORIE", ''), COALESCE("FORME", ''));

-- La bibliothèque des pièces du manuel.
WITH base AS (SELECT COALESCE(MAX("ID_TYPE_PIECE"), 0) AS m FROM public.t_type_piece_jointe),
lib(n, code, libelle) AS (VALUES
    (1,  'FICHE_PRESENTATION',  'Fiche de présentation datée et signée'),
    (2,  'CALENDRIER',          'Calendrier annuel de passation mis à jour et signé'),
    (3,  'AGPM_CONTROLE',       'AGPM (ou PPM) signé et contrôlé, avec le PV de la Commission'),
    (4,  'PUBLICATION_AGPM',    'Publication de l''AGPM (journal)'),
    (5,  'AVIS_SPECIFIQUE',     'Projet d''avis spécifique (imprimé du SIGMP)'),
    (6,  'CANEVAS_RAPPORT',     'Canevas de rapport d''évaluation'),
    (7,  'BORDEREAU_PRIX',      'Bordereau des prix estimatifs signé'),
    (8,  'DQE',                 'Devis quantitatif et estimatif signé'),
    (9,  'TABLEAU_COUTS',       'Tableau des coûts estimatifs signé'),
    (10, 'PPM_CONTROLE',        'PPM signé et contrôlé portant la prestation'),
    (11, 'DOSSIER_PREQUAL',     'Projet de dossier de pré-qualification'),
    (12, 'LETTRE_INVITATION',   'Projet de lettre d''invitation (imprimé du SIGMP)'),
    (13, 'PV_LISTE_RESTREINTE', 'PV de validation de la liste restreinte par la CAO'),
    (14, 'PUBLICATION_AMI',     'Journal de publication de l''AMI'),
    (15, 'PV_AMI',              'PV d''ouverture et PV de validation de l''AMI'),
    (16, 'DECISION_LISTE',      'Projet de décision autorisant la liste restreinte'),
    (17, 'RAPPORT_JUSTIF',      'Rapport justificatif signé'),
    (18, 'PROJET_DECISION_GAG', 'Projet de décision autorisant le gré à gré'),
    (19, 'DECISION_GAG',        'Décision autorisant le gré à gré, signée'),
    (20, 'PIECES_APPUI',        'Pièces d''appui'),
    (21, 'PV_CHOIX_TITULAIRE',  'PV de validation du choix du titulaire et du montant par la CAO'),
    (22, 'PUBLICATION_AVIS',    'Journal de première publication de l''avis (ou lettres d''invitation avec accusé)'),
    (23, 'DECISION_PREQUAL',    'Décision portant liste des pré-qualifiés'),
    (24, 'PV_CNM_DMC',          'PV de la Commission sur le dossier de mise en concurrence'),
    (25, 'PV_VALIDATION_CAO',   'PV de validation de l''évaluation par la CAO'),
    (26, 'DECISION_AO_RESTR',   'Décision autorisant l''appel d''offres restreint'),
    (27, 'LETTRES_ACCUSE',      'Lettres d''invitation avec accusé de réception'),
    (28, 'RAPPORT_TECHNIQUE',   'Rapport d''évaluation technique'),
    (29, 'PV_VALID_TECHNIQUE',  'PV de validation technique de la CAO'),
    (30, 'LETTRES_RESULTATS',   'Lettres de notification des résultats techniques et d''information de l''ouverture financière, avec accusé'),
    (31, 'PV_OUV_FINANCIERE',   'PV d''ouverture des propositions financières'),
    (32, 'PV_VALID_FINALE',     'PV de validation finale de la CAO'),
    (33, 'MARCHE_INITIAL',      'Marché initial signé et approuvé (et avenants antérieurs)'),
    (34, 'PV_CNM_MARCHE',       'PV de la Commission sur le marché'),
    (35, 'ACCORD_PARTIES',      'Accord de l''Autorité contractante et du titulaire'),
    (36, 'ELEMENT_DECLENCHEUR', 'Élément déclencheur'),
    (37, 'PV_NOUVEAUX_PRIX',    'PV de validation des nouveaux prix par la CAO'),
    (38, 'PROJET_AVENANT',      'Projet d''avenant'),
    (39, 'PROJET_DECISION',     'Projet de décision'),
    (40, 'JUSTIFICATIFS',       'Justificatifs (correspondances, calculs, constats, mises en demeure)')
)
INSERT INTO public.t_type_piece_jointe ("ID_TYPE_PIECE", "ID_TYPE_DOSSIER", "LIBELLE_PIECE", "OBLIGATOIRE", "ORDRE", "CODE")
SELECT base.m + lib.n, NULL, lib.libelle, false, NULL, lib.code
FROM base, lib
WHERE NOT EXISTS (SELECT 1 FROM public.t_type_piece_jointe t WHERE t."CODE" = lib.code);

SELECT setval(pg_get_serial_sequence('public.t_type_piece_jointe', 'ID_TYPE_PIECE'),
              GREATEST((SELECT COALESCE(MAX("ID_TYPE_PIECE"), 0) FROM public.t_type_piece_jointe), 1));

-- Les listes du manuel (§B2). Colonnes : sous-type, code, obligatoire, ordre, catégorie, forme.
INSERT INTO public.t_piece_sous_type ("ID_TYPE_PIECE", "ID_SOUS_TYPE", "OBLIGATOIRE", "ORDRE", "CATEGORIE", "FORME")
SELECT t."ID_TYPE_PIECE", v.st, v.obl, v.ordre, v.cat, v.forme
FROM (VALUES
    -- DAOO (et ses variantes DAOOI, DAOOPREQUAL) : fournitures, travaux ; contrat-cadre allégé.
    ('DAOO', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DAOO', 'CALENDRIER', true, 2, NULL, NULL),
    ('DAOO', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DAOO', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DAOO', 'AVIS_SPECIFIQUE', true, 5, NULL, NULL), ('DAOO', 'CANEVAS_RAPPORT', true, 6, NULL, 'AUTRE'),
    ('DAOO', 'BORDEREAU_PRIX', true, 7, 'FOURNITURES_SERVICES', 'AUTRE'), ('DAOO', 'DQE', true, 7, 'TRAVAUX', 'AUTRE'),
    ('DAOO', 'DAO_COMPLET', true, 8, NULL, NULL),
    ('DAOOI', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DAOOI', 'CALENDRIER', true, 2, NULL, NULL),
    ('DAOOI', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DAOOI', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DAOOI', 'AVIS_SPECIFIQUE', true, 5, NULL, NULL), ('DAOOI', 'CANEVAS_RAPPORT', true, 6, NULL, 'AUTRE'),
    ('DAOOI', 'BORDEREAU_PRIX', true, 7, 'FOURNITURES_SERVICES', 'AUTRE'), ('DAOOI', 'DQE', true, 7, 'TRAVAUX', 'AUTRE'),
    ('DAOOI', 'DAO_COMPLET', true, 8, NULL, NULL),
    ('DAOOPREQUAL', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DAOOPREQUAL', 'CALENDRIER', true, 2, NULL, NULL),
    ('DAOOPREQUAL', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DAOOPREQUAL', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DAOOPREQUAL', 'AVIS_SPECIFIQUE', true, 5, NULL, NULL), ('DAOOPREQUAL', 'CANEVAS_RAPPORT', true, 6, NULL, 'AUTRE'),
    ('DAOOPREQUAL', 'BORDEREAU_PRIX', true, 7, 'FOURNITURES_SERVICES', 'AUTRE'), ('DAOOPREQUAL', 'DQE', true, 7, 'TRAVAUX', 'AUTRE'),
    ('DAOOPREQUAL', 'DAO_COMPLET', true, 8, NULL, NULL),
    -- DPREQUAL
    ('DPREQUAL', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DPREQUAL', 'CALENDRIER', true, 2, NULL, NULL),
    ('DPREQUAL', 'PUBLICATION_AGPM', true, 3, NULL, NULL), ('DPREQUAL', 'PPM_CONTROLE', true, 4, NULL, NULL),
    ('DPREQUAL', 'AVIS_SPECIFIQUE', true, 5, NULL, NULL), ('DPREQUAL', 'DOSSIER_PREQUAL', true, 6, NULL, NULL),
    -- DAOR / DAORI
    ('DAOR', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DAOR', 'CALENDRIER', true, 2, NULL, NULL),
    ('DAOR', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DAOR', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DAOR', 'LETTRE_INVITATION', true, 5, NULL, NULL), ('DAOR', 'PV_LISTE_RESTREINTE', true, 6, NULL, NULL),
    ('DAOR', 'CANEVAS_RAPPORT', true, 7, NULL, NULL), ('DAOR', 'BORDEREAU_PRIX', true, 8, 'FOURNITURES_SERVICES', NULL),
    ('DAOR', 'DQE', true, 8, 'TRAVAUX', NULL), ('DAOR', 'DAO_COMPLET', true, 9, NULL, NULL),
    ('DAORI', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DAORI', 'CALENDRIER', true, 2, NULL, NULL),
    ('DAORI', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DAORI', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DAORI', 'LETTRE_INVITATION', true, 5, NULL, NULL), ('DAORI', 'PV_LISTE_RESTREINTE', true, 6, NULL, NULL),
    ('DAORI', 'CANEVAS_RAPPORT', true, 7, NULL, NULL), ('DAORI', 'BORDEREAU_PRIX', true, 8, 'FOURNITURES_SERVICES', NULL),
    ('DAORI', 'DQE', true, 8, 'TRAVAUX', NULL), ('DAORI', 'DAO_COMPLET', true, 9, NULL, NULL),
    -- DC (prestations intellectuelles)
    ('DC', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DC', 'CALENDRIER', true, 2, NULL, NULL),
    ('DC', 'AGPM_CONTROLE', true, 3, NULL, NULL), ('DC', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('DC', 'PUBLICATION_AMI', true, 5, NULL, NULL), ('DC', 'PV_AMI', true, 6, NULL, NULL),
    ('DC', 'RAPPORT_PRESELECTION', true, 7, NULL, NULL), ('DC', 'LETTRE_INVITATION', true, 8, NULL, NULL),
    ('DC', 'DECISION_LISTE', true, 9, NULL, NULL), ('DC', 'CANEVAS_RAPPORT', true, 10, NULL, NULL),
    ('DC', 'TABLEAU_COUTS', true, 11, NULL, NULL), ('DC', 'DAO_COMPLET', true, 12, NULL, NULL),
    -- RJ, MGG (gré à gré)
    ('RJ', 'RAPPORT_JUSTIF', true, 1, NULL, NULL), ('RJ', 'PPM_CONTROLE', true, 2, NULL, NULL),
    ('RJ', 'PROJET_DECISION_GAG', true, 3, NULL, NULL), ('RJ', 'PIECES_APPUI', false, 4, NULL, NULL),
    ('MGG', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MGG', 'DECISION_GAG', true, 2, NULL, NULL),
    ('MGG', 'PPM_CONTROLE', true, 3, NULL, NULL), ('MGG', 'PV_CHOIX_TITULAIRE', true, 4, NULL, NULL),
    ('MGG', 'PROJET_MARCHE', true, 5, NULL, NULL),
    -- MAOO (et MAOOI, MAOOPREQUAL)
    ('MAOO', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MAOO', 'PUBLICATION_AVIS', true, 2, NULL, NULL),
    ('MAOO', 'PUBLICATION_AGPM', true, 3, NULL, NULL), ('MAOO', 'PV_CNM_DMC', true, 4, NULL, NULL),
    ('MAOO', 'PV_OUVERTURE', true, 5, NULL, NULL), ('MAOO', 'RAPPORT_ANALYSE', true, 6, NULL, NULL),
    ('MAOO', 'PV_VALIDATION_CAO', true, 7, NULL, NULL), ('MAOO', 'DEVIS_ESTIMATIF', true, 8, NULL, NULL),
    ('MAOO', 'PROJET_MARCHE', true, 9, NULL, NULL), ('MAOO', 'CAHIER_CHARGES', false, 10, NULL, NULL),
    ('MAOOI', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MAOOI', 'PUBLICATION_AVIS', true, 2, NULL, NULL),
    ('MAOOI', 'PUBLICATION_AGPM', true, 3, NULL, NULL), ('MAOOI', 'PV_CNM_DMC', true, 4, NULL, NULL),
    ('MAOOI', 'PV_OUVERTURE', true, 5, NULL, NULL), ('MAOOI', 'RAPPORT_ANALYSE', true, 6, NULL, NULL),
    ('MAOOI', 'PV_VALIDATION_CAO', true, 7, NULL, NULL), ('MAOOI', 'DEVIS_ESTIMATIF', true, 8, NULL, NULL),
    ('MAOOI', 'PROJET_MARCHE', true, 9, NULL, NULL), ('MAOOI', 'CAHIER_CHARGES', false, 10, NULL, NULL),
    ('MAOOPREQUAL', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MAOOPREQUAL', 'PUBLICATION_AVIS', true, 2, NULL, NULL),
    ('MAOOPREQUAL', 'DECISION_PREQUAL', true, 3, NULL, NULL), ('MAOOPREQUAL', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('MAOOPREQUAL', 'PV_CNM_DMC', true, 5, NULL, NULL), ('MAOOPREQUAL', 'PV_OUVERTURE', true, 6, NULL, NULL),
    ('MAOOPREQUAL', 'RAPPORT_ANALYSE', true, 7, NULL, NULL), ('MAOOPREQUAL', 'PV_VALIDATION_CAO', true, 8, NULL, NULL),
    ('MAOOPREQUAL', 'DEVIS_ESTIMATIF', true, 9, NULL, NULL), ('MAOOPREQUAL', 'PROJET_MARCHE', true, 10, NULL, NULL),
    ('MAOOPREQUAL', 'CAHIER_CHARGES', false, 11, NULL, NULL),
    -- MAOR / MAORI
    ('MAOR', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MAOR', 'DECISION_AO_RESTR', true, 2, NULL, NULL),
    ('MAOR', 'LETTRES_ACCUSE', true, 3, NULL, NULL), ('MAOR', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('MAOR', 'PV_CNM_DMC', true, 5, NULL, NULL), ('MAOR', 'PV_OUVERTURE', true, 6, NULL, NULL),
    ('MAOR', 'RAPPORT_ANALYSE', true, 7, NULL, NULL), ('MAOR', 'PV_VALIDATION_CAO', true, 8, NULL, NULL),
    ('MAOR', 'DEVIS_ESTIMATIF', true, 9, NULL, NULL), ('MAOR', 'PROJET_MARCHE', true, 10, NULL, NULL),
    ('MAOR', 'CAHIER_CHARGES', false, 11, NULL, NULL),
    ('MAORI', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MAORI', 'DECISION_AO_RESTR', true, 2, NULL, NULL),
    ('MAORI', 'LETTRES_ACCUSE', true, 3, NULL, NULL), ('MAORI', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('MAORI', 'PV_CNM_DMC', true, 5, NULL, NULL), ('MAORI', 'PV_OUVERTURE', true, 6, NULL, NULL),
    ('MAORI', 'RAPPORT_ANALYSE', true, 7, NULL, NULL), ('MAORI', 'PV_VALIDATION_CAO', true, 8, NULL, NULL),
    ('MAORI', 'DEVIS_ESTIMATIF', true, 9, NULL, NULL), ('MAORI', 'PROJET_MARCHE', true, 10, NULL, NULL),
    ('MAORI', 'CAHIER_CHARGES', false, 11, NULL, NULL),
    -- MPI (deux enveloppes)
    ('MPI', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('MPI', 'LETTRES_ACCUSE', true, 2, NULL, NULL),
    ('MPI', 'DECISION_LISTE', true, 3, NULL, NULL), ('MPI', 'PUBLICATION_AGPM', true, 4, NULL, NULL),
    ('MPI', 'PV_CNM_DMC', true, 5, NULL, NULL), ('MPI', 'PV_OUVERTURE', true, 6, NULL, NULL),
    ('MPI', 'RAPPORT_TECHNIQUE', true, 7, NULL, NULL), ('MPI', 'PV_VALID_TECHNIQUE', true, 8, NULL, NULL),
    ('MPI', 'LETTRES_RESULTATS', true, 9, NULL, NULL), ('MPI', 'PV_OUV_FINANCIERE', true, 10, NULL, NULL),
    ('MPI', 'RAPPORT_ANALYSE', true, 11, NULL, NULL), ('MPI', 'PV_VALID_FINALE', true, 12, NULL, NULL),
    ('MPI', 'DEVIS_ESTIMATIF', true, 13, NULL, NULL), ('MPI', 'PROJET_MARCHE', true, 14, NULL, NULL),
    ('MPI', 'CAHIER_CHARGES', false, 15, NULL, NULL),
    -- AVN (avenant)
    ('AVN', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('AVN', 'MARCHE_INITIAL', true, 2, NULL, NULL),
    ('AVN', 'PV_CNM_MARCHE', true, 3, NULL, NULL), ('AVN', 'ACCORD_PARTIES', true, 4, NULL, NULL),
    ('AVN', 'ELEMENT_DECLENCHEUR', true, 5, NULL, NULL), ('AVN', 'PV_NOUVEAUX_PRIX', false, 6, NULL, NULL),
    ('AVN', 'PIECES_APPUI', false, 7, NULL, NULL), ('AVN', 'PROJET_AVENANT', true, 8, NULL, NULL),
    -- DSS (déclaration sans suite) : les motifs produits par le serveur, plus les pièces du manuel.
    ('DSS', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DSS', 'AGPM_CONTROLE', true, 2, NULL, NULL),
    ('DSS', 'MOTIFS_SANS_SUITE', true, 3, NULL, NULL), ('DSS', 'PROJET_DECISION', true, 4, NULL, NULL),
    ('DSS', 'JUSTIFICATIFS', true, 5, NULL, NULL),
    -- INDEMN, SURSIS, PENAL, DR (actes de gestion contractuelle)
    ('INDEMN', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('INDEMN', 'AGPM_CONTROLE', true, 2, NULL, NULL),
    ('INDEMN', 'PV_CNM_MARCHE', true, 3, NULL, NULL), ('INDEMN', 'MARCHE_INITIAL', true, 4, NULL, NULL),
    ('INDEMN', 'PROJET_DECISION', true, 5, NULL, NULL), ('INDEMN', 'JUSTIFICATIFS', true, 6, NULL, NULL),
    ('SURSIS', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('SURSIS', 'AGPM_CONTROLE', true, 2, NULL, NULL),
    ('SURSIS', 'PV_CNM_MARCHE', true, 3, NULL, NULL), ('SURSIS', 'MARCHE_INITIAL', true, 4, NULL, NULL),
    ('SURSIS', 'PROJET_DECISION', true, 5, NULL, NULL), ('SURSIS', 'JUSTIFICATIFS', true, 6, NULL, NULL),
    ('PENAL', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('PENAL', 'AGPM_CONTROLE', true, 2, NULL, NULL),
    ('PENAL', 'PV_CNM_MARCHE', true, 3, NULL, NULL), ('PENAL', 'MARCHE_INITIAL', true, 4, NULL, NULL),
    ('PENAL', 'PROJET_DECISION', true, 5, NULL, NULL), ('PENAL', 'JUSTIFICATIFS', true, 6, NULL, NULL),
    ('DR', 'FICHE_PRESENTATION', true, 1, NULL, NULL), ('DR', 'AGPM_CONTROLE', true, 2, NULL, NULL),
    ('DR', 'PV_CNM_MARCHE', true, 3, NULL, NULL), ('DR', 'MARCHE_INITIAL', true, 4, NULL, NULL),
    ('DR', 'PROJET_DECISION', true, 5, NULL, NULL), ('DR', 'JUSTIFICATIFS', true, 6, NULL, NULL)
) AS v(st, code, obl, ordre, cat, forme)
JOIN public.t_type_piece_jointe t ON t."CODE" = v.code
WHERE EXISTS (SELECT 1 FROM public.tr_sous_type_dossier s WHERE s."ID_SOUS_TYPE" = v.st)
  AND NOT EXISTS (SELECT 1 FROM public.t_piece_sous_type x WHERE x."ID_TYPE_PIECE" = t."ID_TYPE_PIECE" AND x."ID_SOUS_TYPE" = v.st
                  AND COALESCE(x."CATEGORIE", '') = COALESCE(v.cat, '') AND COALESCE(x."FORME", '') = COALESCE(v.forme, ''));
