-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V97 — Le référentiel du contrôle aligné sur le Manuel de contrôle a priori, tranche M4 : les motifs-types de la conclusion (demande
-- front du 2026-10-08 `demande-backend-2026-10-08-manuel-controle-a-priori.md`, §B4 ; arbitrages du pilote du 08/10, Q5 : oui ; du 09/10 :
-- référentiel administrable semé du manuel, texte inséré par le front, héritage des grilles).
--
-- tr_motif_type : un motif de RENVOI (lettre de demande de compléments) ou d'AVIS_DEFAVORABLE, par famille (ID_SOUS_TYPE nul : commun à
-- la famille) ou par sous-type ; LIBELLE court (la liste), TEXTE inséré dans le projet de PV ou de lettre (modifiable ensuite) ; même
-- condition que les points de contrôle (CATEGORIE de la fiche, FORME) ; ACTIF (un motif désactivé n'est plus servi à l'examen).
-- Les motifs du manuel sont semés au démarrage (MotifsTypesManuelSeeder) : un motif existant n'est jamais réécrit.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.tr_motif_type (
    "ID_MOTIF" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_TYPE_DOSSIER" character varying(10) NOT NULL REFERENCES public.tr_type_dossier ("ID_TYPE_DOSSIER"),
    "ID_SOUS_TYPE" character varying(20) REFERENCES public.tr_sous_type_dossier ("ID_SOUS_TYPE"),
    "NATURE" character varying(20) NOT NULL,
    "LIBELLE" character varying(200) NOT NULL,
    "TEXTE" text NOT NULL,
    "ORDRE" integer,
    "CATEGORIE" character varying(40),
    "FORME" character varying(20),
    "ACTIF" boolean NOT NULL DEFAULT true,
    CONSTRAINT ck_motif_type_nature CHECK ("NATURE" IN ('RENVOI', 'AVIS_DEFAVORABLE')),
    CONSTRAINT ck_motif_type_forme CHECK ("FORME" IS NULL OR "FORME" IN ('CONTRAT_CADRE', 'AUTRE')),
    CONSTRAINT ck_motif_type_categorie CHECK ("CATEGORIE" IS NULL
        OR "CATEGORIE" IN ('FOURNITURES_SERVICES', 'TRAVAUX', 'PRESTATIONS_INTELLECTUELLES'))
);

CREATE INDEX IF NOT EXISTS ix_motif_type_famille ON public.tr_motif_type ("ID_TYPE_DOSSIER", "ID_SOUS_TYPE");
