-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V98 — Le référentiel du contrôle aligné sur le Manuel de contrôle a priori, tranche M5a : les actes de gestion contractuelle déposés
-- depuis le marché et les garde-fous de l'avenant (demande front du 2026-10-08 `demande-backend-2026-10-08-manuel-controle-a-priori.md`,
-- §B1 et §B5 ; arbitrages du pilote du 09/10 : montant initial et catégorie lus — attribution en ligne, fiche — sinon déclarés au dépôt ;
-- cumul des avenants = ceux déjà soumis, hors avis défavorable, montants HT).
--
-- t_acte_gestion : un dossier DGC (avenant, résiliation, indemnité, remise de pénalités, sursis) et le dossier de marché (DDM, au PV
-- favorable) qu'il concerne ; RANG de l'avenant (il entre dans la référence : « …/AVN2/… ») ; MONTANT_HT de l'avenant (hausse ou baisse) ;
-- faits du marché déclarés par la PRMP : MONTANT_INITIAL_HT et CATEGORIE (quand le serveur ne les connaît pas), dates de réception
-- provisoire, définitive et de règlement du solde (garde-fous de l'avenant). Supprimé avec son dossier.
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.t_acte_gestion (
    "ID_ACTE" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_DOSSIER" integer NOT NULL UNIQUE REFERENCES public.t_dossier ("ID_DOSSIER") ON DELETE CASCADE,
    "ID_DOSSIER_MARCHE" integer NOT NULL REFERENCES public.t_dossier ("ID_DOSSIER"),
    "SOUS_TYPE" character varying(20) NOT NULL,
    "RANG" integer,
    "MONTANT_HT" numeric(18, 2),
    "MONTANT_INITIAL_HT" numeric(18, 2),
    "CATEGORIE" character varying(40),
    "DATE_RECEPTION_PROVISOIRE" date,
    "DATE_RECEPTION_DEFINITIVE" date,
    "DATE_SOLDE" date,
    "CREE_LE" timestamp without time zone NOT NULL DEFAULT now(),
    "CREE_PAR" character varying(50),
    CONSTRAINT ck_acte_gestion_categorie CHECK ("CATEGORIE" IS NULL
        OR "CATEGORIE" IN ('FOURNITURES_SERVICES', 'TRAVAUX', 'PRESTATIONS_INTELLECTUELLES'))
);

CREATE INDEX IF NOT EXISTS ix_acte_gestion_marche ON public.t_acte_gestion ("ID_DOSSIER_MARCHE");
