-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V99 — Le référentiel du contrôle aligné sur le Manuel de contrôle a priori, tranche M5b : les délais par sous-type et l'alerte
-- d'examen (demande front du 2026-10-08 `demande-backend-2026-10-08-manuel-controle-a-priori.md`, §B6 ; arbitrages du pilote du 09/10 :
-- aucune valeur de départ — l'Administrateur règle, l'examen reste à son réglage actuel ; alerte au Membre, au Chef de commission et au
-- Président au-delà de 5 jours ouvrés).
--
-- 1. tr_delai_sous_type : le délai d'une étape SURCHARGÉ pour un sous-type (le manuel : « différencié selon le type de dossier ») ; un
--    sous-type sans ligne pour une étape prend le délai standard de l'étape (tr_delai_standard). Née vide.
-- 2. t_alerte_examen : l'alerte de dépassement d'un passage en examen, une seule par passage (dossier + entrée dans l'étape).
-- Idempotente.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.tr_delai_sous_type (
    "ID_SOUS_TYPE" character varying(20) NOT NULL REFERENCES public.tr_sous_type_dossier ("ID_SOUS_TYPE") ON DELETE CASCADE,
    "ETAPE" character varying(30) NOT NULL,
    "DELAI_HEURES" integer NOT NULL,
    CONSTRAINT pk_delai_sous_type PRIMARY KEY ("ID_SOUS_TYPE", "ETAPE"),
    CONSTRAINT ck_delai_sous_type_positif CHECK ("DELAI_HEURES" >= 1)
);

CREATE TABLE IF NOT EXISTS public.t_alerte_examen (
    "ID_ALERTE" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ID_DOSSIER" integer NOT NULL REFERENCES public.t_dossier ("ID_DOSSIER") ON DELETE CASCADE,
    "ENTREE" timestamp without time zone NOT NULL,
    "ECOULE_HEURES" integer NOT NULL,
    "ALERTE_LE" timestamp without time zone NOT NULL,
    CONSTRAINT uq_alerte_examen UNIQUE ("ID_DOSSIER", "ENTREE")
);
